In [1]:
import pandas as pd
import numpy as np

In [2]:
dp03 = pd.read_csv(r'C:\Users\dgarb\OneDrive\Desktop\Capstone Data\census data\ACSDP5Y2020.DP03-2022-03-21T214613.csv')

In [4]:
cols = list(dp03.columns)

In [5]:
new_cols = list(filter(lambda col: "Estimate" in col,cols)) 

new_cols = ['Label (Grouping)'] + new_cols
new_cols

['Label (Grouping)',
 'ZCTA5 50001!!Estimate',
 'ZCTA5 50002!!Estimate',
 'ZCTA5 50003!!Estimate',
 'ZCTA5 50005!!Estimate',
 'ZCTA5 50006!!Estimate',
 'ZCTA5 50007!!Estimate',
 'ZCTA5 50008!!Estimate',
 'ZCTA5 50009!!Estimate',
 'ZCTA5 50010!!Estimate',
 'ZCTA5 50011!!Estimate',
 'ZCTA5 50012!!Estimate',
 'ZCTA5 50014!!Estimate',
 'ZCTA5 50020!!Estimate',
 'ZCTA5 50021!!Estimate',
 'ZCTA5 50022!!Estimate',
 'ZCTA5 50023!!Estimate',
 'ZCTA5 50025!!Estimate',
 'ZCTA5 50026!!Estimate',
 'ZCTA5 50027!!Estimate',
 'ZCTA5 50028!!Estimate',
 'ZCTA5 50029!!Estimate',
 'ZCTA5 50032!!Estimate',
 'ZCTA5 50033!!Estimate',
 'ZCTA5 50034!!Estimate',
 'ZCTA5 50035!!Estimate',
 'ZCTA5 50036!!Estimate',
 'ZCTA5 50038!!Estimate',
 'ZCTA5 50039!!Estimate',
 'ZCTA5 50041!!Estimate',
 'ZCTA5 50042!!Estimate',
 'ZCTA5 50044!!Estimate',
 'ZCTA5 50046!!Estimate',
 'ZCTA5 50047!!Estimate',
 'ZCTA5 50048!!Estimate',
 'ZCTA5 50049!!Estimate',
 'ZCTA5 50050!!Estimate',
 'ZCTA5 50051!!Estimate',
 'ZCTA5 50052!!Estimate',
 'ZCTA5 50054!!Estimate',
 'ZCTA5 50055!!Estimate',
 'ZCTA5 50056!!Estimate',
 'ZCTA5 50057!!Estimate',
 'ZCTA5 50058!!Estimate',
 'ZCTA5 50060!!Estimate',
 'ZCTA5 50061!!Estimate',
 'ZCTA5 50062!!Estimate',
 'ZCTA5 50063!!Estimate',
 'ZCTA5 50064!!Estimate',
 'ZCTA5 50065!!Estimate',
 'ZCTA5 50066!!Estimate',
 'ZCTA5 50067!!Estimate',
 'ZCTA5 50068!!Estimate',
 'ZCTA5 50069!!Estimate',
 'ZCTA5 50070!!Estimate',
 'ZCTA5 50071!!Estimate',
 'ZCTA5 50072!!Estimate',
 'ZCTA5 50073!!Estimate',
 'ZCTA5 50074!!Estimate',
 'ZCTA5 50075!!Estimate',
 'ZCTA5 50076!!Estimate',
 'ZCTA5 50078!!Estimate',
 'ZCTA5 50101!!Estimate',
 'ZCTA5 50102!!Estimate',
 'ZCTA5 50103!!Estimate',
 'ZCTA5 50104!!Estimate',
 'ZCTA5 50105!!Estimate',
 'ZCTA5 50106!!Estimate',
 'ZCTA5 50107!!Estimate',
 'ZCTA5 50108!!Estimate',
 'ZCTA5 50109!!Estimate',
 'ZCTA5 50111!!Estimate',
 'ZCTA5 50112!!Estimate',
 'ZCTA5 50115!!Estimate',
 'ZCTA5 50116!!Estimate',
 'ZCTA5 50117!!Estimate',
 'ZCTA5 50118!!Estimate',
 'ZCTA5 50119!!Estimate',
 'ZCTA5 50120!!Estimate',
 'ZCTA5 50122!!Estimate',
 'ZCTA5 50123!!Estimate',
 'ZCTA5 50124!!Estimate',
 'ZCTA5 50125!!Estimate',
 'ZCTA5 50126!!Estimate',
 'ZCTA5 50127!!Estimate',
 'ZCTA5 50128!!Estimate',
 'ZCTA5 50129!!Estimate',
 'ZCTA5 50130!!Estimate',
 'ZCTA5 50131!!Estimate',
 'ZCTA5 50132!!Estimate',
 'ZCTA5 50133!!Estimate',
 'ZCTA5 50134!!Estimate',
 'ZCTA5 50135!!Estimate',
 'ZCTA5 50136!!Estimate',
 'ZCTA5 50138!!Estimate',
 'ZCTA5 50139!!Estimate',
 'ZCTA5 50140!!Estimate',
 'ZCTA5 50141!!Estimate',
 'ZCTA5 50142!!Estimate',
 'ZCTA5 50143!!Estimate',
 'ZCTA5 50144!!Estimate',
 'ZCTA5 50146!!Estimate',
 'ZCTA5 50147!!Estimate',
 'ZCTA5 50148!!Estimate',
 'ZCTA5 50149!!Estimate',
 'ZCTA5 50150!!Estimate',
 'ZCTA5 50151!!Estimate',
 'ZCTA5 50153!!Estimate',
 'ZCTA5 50154!!Estimate',
 'ZCTA5 50155!!Estimate',
 'ZCTA5 50156!!Estimate',
 'ZCTA5 50157!!Estimate',
 'ZCTA5 50158!!Estimate',
 'ZCTA5 50160!!Estimate',
 'ZCTA5 50161!!Estimate',
 'ZCTA5 50162!!Estimate',
 'ZCTA5 50163!!Estimate',
 'ZCTA5 50164!!Estimate',
 'ZCTA5 50165!!Estimate',
 'ZCTA5 50166!!Estimate',
 'ZCTA5 50167!!Estimate',
 'ZCTA5 50168!!Estimate',
 'ZCTA5 50169!!Estimate',
 'ZCTA5 50170!!Estimate',
 'ZCTA5 50171!!Estimate',
 'ZCTA5 50173!!Estimate',
 'ZCTA5 50174!!Estimate',
 'ZCTA5 50201!!Estimate',
 'ZCTA5 50206!!Estimate',
 'ZCTA5 50207!!Estimate',
 'ZCTA5 50208!!Estimate',
 'ZCTA5 50210!!Estimate',
 'ZCTA5 50211!!Estimate',
 'ZCTA5 50212!!Estimate',
 'ZCTA5 50213!!Estimate',
 'ZCTA5 50214!!Estimate',
 'ZCTA5 50216!!Estimate',
 'ZCTA5 50217!!Estimate',
 'ZCTA5 50218!!Estimate',
 'ZCTA5 50219!!Estimate',
 'ZCTA5 50220!!Estimate',
 'ZCTA5 50222!!Estimate',
 'ZCTA5 50223!!Estimate',
 'ZCTA5 50225!!Estimate',
 'ZCTA5 50226!!Estimate',
 'ZCTA5 50227!!Estimate',
 'ZCTA5 50228!!Estimate',
 'ZCTA5 50229!!Estimate',
 'ZCTA5 50230!!Estimate',
 'ZCTA5 50231!!Estimate',
 'ZCTA5 50232!!Estimate',
 'ZCTA5 50233!!Estimate',
 'ZCTA5 50234!!Estimate',
 'ZCTA5 50235!!Estimate',
 'ZCTA5 50236!!Estimate',
 'ZCTA5 50237!!Estimate',
 'ZCTA5 50238!!Estimate',
 'ZCTA5 50239!!Estimate',
 'ZCTA5 50240!!Estimate',
 'ZCTA5 50242!!Estimate',
 'ZCTA5 50243!!Estimate',
 'ZCTA5 50244!!Estimate',
 'ZCTA5 50246!!Estimate',
 'ZCTA5 50247!!Estimate',
 'ZCTA5 50248!!Estimate',
 'ZCTA5 50249!!Estimate',
 'ZCTA5 50250!!Estimate',
 'ZCTA5 50251!!Estimate',
 'ZCTA5 50252!!Estimate',
 'ZCTA5 50254!!Estimate',
 'ZCTA5 50255!!Estimate',
 'ZCTA5 50256!!Estimate',
 'ZCTA5 50257!!Estimate',
 'ZCTA5 50258!!Estimate',
 'ZCTA5 50261!!Estimate',
 'ZCTA5 50262!!Estimate',
 'ZCTA5 50263!!Estimate',
 'ZCTA5 50264!!Estimate',
 'ZCTA5 50265!!Estimate',
 'ZCTA5 50266!!Estimate',
 'ZCTA5 50268!!Estimate',
 'ZCTA5 50271!!Estimate',
 'ZCTA5 50272!!Estimate',
 'ZCTA5 50273!!Estimate',
 'ZCTA5 50274!!Estimate',
 'ZCTA5 50275!!Estimate',
 'ZCTA5 50276!!Estimate',
 'ZCTA5 50277!!Estimate',
 'ZCTA5 50278!!Estimate',
 'ZCTA5 50309!!Estimate',
 'ZCTA5 50310!!Estimate',
 'ZCTA5 50311!!Estimate',
 'ZCTA5 50312!!Estimate',
 'ZCTA5 50313!!Estimate',
 'ZCTA5 50314!!Estimate',
 'ZCTA5 50315!!Estimate',
 'ZCTA5 50316!!Estimate',
 'ZCTA5 50317!!Estimate',
 'ZCTA5 50319!!Estimate',
 'ZCTA5 50320!!Estimate',
 'ZCTA5 50321!!Estimate',
 'ZCTA5 50322!!Estimate',
 'ZCTA5 50323!!Estimate',
 'ZCTA5 50324!!Estimate',
 'ZCTA5 50325!!Estimate',
 'ZCTA5 50327!!Estimate',
 'ZCTA5 50401!!Estimate',
 'ZCTA5 50420!!Estimate',
 'ZCTA5 50421!!Estimate',
 'ZCTA5 50423!!Estimate',
 'ZCTA5 50424!!Estimate',
 'ZCTA5 50426!!Estimate',
 'ZCTA5 50428!!Estimate',
 'ZCTA5 50430!!Estimate',
 'ZCTA5 50431!!Estimate',
 'ZCTA5 50432!!Estimate',
 'ZCTA5 50433!!Estimate',
 'ZCTA5 50434!!Estimate',
 'ZCTA5 50435!!Estimate',
 'ZCTA5 50436!!Estimate',
 'ZCTA5 50438!!Estimate',
 'ZCTA5 50439!!Estimate',
 'ZCTA5 50440!!Estimate',
 'ZCTA5 50441!!Estimate',
 'ZCTA5 50444!!Estimate',
 'ZCTA5 50446!!Estimate',
 'ZCTA5 50447!!Estimate',
 'ZCTA5 50448!!Estimate',
 'ZCTA5 50449!!Estimate',
 'ZCTA5 50450!!Estimate',
 'ZCTA5 50451!!Estimate',
 'ZCTA5 50452!!Estimate',
 'ZCTA5 50453!!Estimate',
 'ZCTA5 50454!!Estimate',
 'ZCTA5 50455!!Estimate',
 'ZCTA5 50456!!Estimate',
 'ZCTA5 50457!!Estimate',
 'ZCTA5 50458!!Estimate',
 'ZCTA5 50459!!Estimate',
 'ZCTA5 50460!!Estimate',
 'ZCTA5 50461!!Estimate',
 'ZCTA5 50464!!Estimate',
 'ZCTA5 50465!!Estimate',
 'ZCTA5 50466!!Estimate',
 'ZCTA5 50467!!Estimate',
 'ZCTA5 50468!!Estimate',
 'ZCTA5 50469!!Estimate',
 'ZCTA5 50470!!Estimate',
 'ZCTA5 50471!!Estimate',
 'ZCTA5 50472!!Estimate',
 'ZCTA5 50473!!Estimate',
 'ZCTA5 50475!!Estimate',
 'ZCTA5 50476!!Estimate',
 'ZCTA5 50477!!Estimate',
 'ZCTA5 50478!!Estimate',
 'ZCTA5 50479!!Estimate',
 'ZCTA5 50480!!Estimate',
 'ZCTA5 50482!!Estimate',
 'ZCTA5 50483!!Estimate',
 'ZCTA5 50484!!Estimate',
 'ZCTA5 50501!!Estimate',
 'ZCTA5 50510!!Estimate',
 'ZCTA5 50511!!Estimate',
 'ZCTA5 50514!!Estimate',
 'ZCTA5 50515!!Estimate',
 'ZCTA5 50516!!Estimate',
 'ZCTA5 50517!!Estimate',
 'ZCTA5 50518!!Estimate',
 'ZCTA5 50519!!Estimate',
 'ZCTA5 50520!!Estimate',
 'ZCTA5 50521!!Estimate',
 'ZCTA5 50522!!Estimate',
 'ZCTA5 50523!!Estimate',
 'ZCTA5 50524!!Estimate',
 'ZCTA5 50525!!Estimate',
 'ZCTA5 50527!!Estimate',
 'ZCTA5 50528!!Estimate',
 'ZCTA5 50529!!Estimate',
 'ZCTA5 50530!!Estimate',
 'ZCTA5 50531!!Estimate',
 'ZCTA5 50532!!Estimate',
 'ZCTA5 50533!!Estimate',
 'ZCTA5 50535!!Estimate',
 'ZCTA5 50536!!Estimate',
 'ZCTA5 50538!!Estimate',
 'ZCTA5 50539!!Estimate',
 'ZCTA5 50540!!Estimate',
 'ZCTA5 50541!!Estimate',
 'ZCTA5 50542!!Estimate',
 'ZCTA5 50543!!Estimate',
 'ZCTA5 50544!!Estimate',
 'ZCTA5 50545!!Estimate',
 'ZCTA5 50546!!Estimate',
 'ZCTA5 50548!!Estimate',
 'ZCTA5 50551!!Estimate',
 'ZCTA5 50554!!Estimate',
 'ZCTA5 50556!!Estimate',
 'ZCTA5 50557!!Estimate',
 'ZCTA5 50558!!Estimate',
 'ZCTA5 50559!!Estimate',
 'ZCTA5 50560!!Estimate',
 'ZCTA5 50561!!Estimate',
 'ZCTA5 50562!!Estimate',
 'ZCTA5 50563!!Estimate',
 'ZCTA5 50565!!Estimate',
 'ZCTA5 50566!!Estimate',
 'ZCTA5 50567!!Estimate',
 'ZCTA5 50568!!Estimate',
 'ZCTA5 50569!!Estimate',
 'ZCTA5 50570!!Estimate',
 'ZCTA5 50571!!Estimate',
 'ZCTA5 50573!!Estimate',
 'ZCTA5 50574!!Estimate',
 'ZCTA5 50575!!Estimate',
 'ZCTA5 50576!!Estimate',
 'ZCTA5 50577!!Estimate',
 'ZCTA5 50578!!Estimate',
 'ZCTA5 50579!!Estimate',
 'ZCTA5 50581!!Estimate',
 'ZCTA5 50582!!Estimate',
 'ZCTA5 50583!!Estimate',
 'ZCTA5 50585!!Estimate',
 'ZCTA5 50586!!Estimate',
 'ZCTA5 50588!!Estimate',
 'ZCTA5 50590!!Estimate',
 'ZCTA5 50591!!Estimate',
 'ZCTA5 50593!!Estimate',
 'ZCTA5 50594!!Estimate',
 'ZCTA5 50595!!Estimate',
 'ZCTA5 50597!!Estimate',
 'ZCTA5 50598!!Estimate',
 'ZCTA5 50599!!Estimate',
 'ZCTA5 50601!!Estimate',
 'ZCTA5 50602!!Estimate',
 'ZCTA5 50603!!Estimate',
 'ZCTA5 50604!!Estimate',
 'ZCTA5 50605!!Estimate',
 'ZCTA5 50606!!Estimate',
 'ZCTA5 50607!!Estimate',
 'ZCTA5 50609!!Estimate',
 'ZCTA5 50611!!Estimate',
 'ZCTA5 50612!!Estimate',
 'ZCTA5 50613!!Estimate',
 'ZCTA5 50616!!Estimate',
 'ZCTA5 50619!!Estimate',
 'ZCTA5 50620!!Estimate',
 'ZCTA5 50621!!Estimate',
 'ZCTA5 50622!!Estimate',
 'ZCTA5 50624!!Estimate',
 'ZCTA5 50625!!Estimate',
 'ZCTA5 50626!!Estimate',
 'ZCTA5 50627!!Estimate',
 'ZCTA5 50628!!Estimate',
 'ZCTA5 50629!!Estimate',
 'ZCTA5 50630!!Estimate',
 'ZCTA5 50632!!Estimate',
 'ZCTA5 50633!!Estimate',
 'ZCTA5 50634!!Estimate',
 'ZCTA5 50635!!Estimate',
 'ZCTA5 50636!!Estimate',
 'ZCTA5 50638!!Estimate',
 'ZCTA5 50641!!Estimate',
 'ZCTA5 50642!!Estimate',
 'ZCTA5 50643!!Estimate',
 'ZCTA5 50644!!Estimate',
 'ZCTA5 50645!!Estimate',
 'ZCTA5 50647!!Estimate',
 'ZCTA5 50648!!Estimate',
 'ZCTA5 50650!!Estimate',
 'ZCTA5 50651!!Estimate',
 'ZCTA5 50652!!Estimate',
 'ZCTA5 50653!!Estimate',
 'ZCTA5 50654!!Estimate',
 'ZCTA5 50655!!Estimate',
 'ZCTA5 50658!!Estimate',
 'ZCTA5 50659!!Estimate',
 'ZCTA5 50660!!Estimate',
 'ZCTA5 50662!!Estimate',
 'ZCTA5 50664!!Estimate',
 'ZCTA5 50665!!Estimate',
 'ZCTA5 50666!!Estimate',
 'ZCTA5 50667!!Estimate',
 'ZCTA5 50668!!Estimate',
 'ZCTA5 50669!!Estimate',
 'ZCTA5 50670!!Estimate',
 'ZCTA5 50671!!Estimate',
 'ZCTA5 50672!!Estimate',
 'ZCTA5 50673!!Estimate',
 'ZCTA5 50674!!Estimate',
 'ZCTA5 50675!!Estimate',
 'ZCTA5 50676!!Estimate',
 'ZCTA5 50677!!Estimate',
 'ZCTA5 50680!!Estimate',
 'ZCTA5 50681!!Estimate',
 'ZCTA5 50682!!Estimate',
 'ZCTA5 50701!!Estimate',
 'ZCTA5 50702!!Estimate',
 'ZCTA5 50703!!Estimate',
 'ZCTA5 50707!!Estimate',
 'ZCTA5 50801!!Estimate',
 'ZCTA5 50830!!Estimate',
 'ZCTA5 50833!!Estimate',
 'ZCTA5 50835!!Estimate',
 'ZCTA5 50836!!Estimate',
 'ZCTA5 50837!!Estimate',
 'ZCTA5 50839!!Estimate',
 'ZCTA5 50840!!Estimate',
 'ZCTA5 50841!!Estimate',
 'ZCTA5 50842!!Estimate',
 'ZCTA5 50843!!Estimate',
 'ZCTA5 50845!!Estimate',
 'ZCTA5 50846!!Estimate',
 'ZCTA5 50847!!Estimate',
 'ZCTA5 50848!!Estimate',
 'ZCTA5 50849!!Estimate',
 'ZCTA5 50851!!Estimate',
 'ZCTA5 50853!!Estimate',
 'ZCTA5 50854!!Estimate',
 'ZCTA5 50857!!Estimate',
 'ZCTA5 50858!!Estimate',
 'ZCTA5 50859!!Estimate',
 'ZCTA5 50860!!Estimate',
 'ZCTA5 50861!!Estimate',
 'ZCTA5 50862!!Estimate',
 'ZCTA5 50863!!Estimate',
 'ZCTA5 50864!!Estimate',
 'ZCTA5 51001!!Estimate',
 'ZCTA5 51002!!Estimate',
 'ZCTA5 51003!!Estimate',
 'ZCTA5 51004!!Estimate',
 'ZCTA5 51005!!Estimate',
 'ZCTA5 51006!!Estimate',
 'ZCTA5 51007!!Estimate',
 'ZCTA5 51008!!Estimate',
 'ZCTA5 51009!!Estimate',
 'ZCTA5 51010!!Estimate',
 'ZCTA5 51011!!Estimate',
 'ZCTA5 51012!!Estimate',
 'ZCTA5 51014!!Estimate',
 'ZCTA5 51016!!Estimate',
 'ZCTA5 51018!!Estimate',
 'ZCTA5 51019!!Estimate',
 'ZCTA5 51020!!Estimate',
 'ZCTA5 51022!!Estimate',
 'ZCTA5 51023!!Estimate',
 'ZCTA5 51024!!Estimate',
 'ZCTA5 51025!!Estimate',
 'ZCTA5 51026!!Estimate',
 'ZCTA5 51027!!Estimate',
 'ZCTA5 51028!!Estimate',
 'ZCTA5 51029!!Estimate',
 'ZCTA5 51030!!Estimate',
 'ZCTA5 51031!!Estimate',
 'ZCTA5 51033!!Estimate',
 'ZCTA5 51034!!Estimate',
 'ZCTA5 51035!!Estimate',
 'ZCTA5 51036!!Estimate',
 'ZCTA5 51037!!Estimate',
 'ZCTA5 51038!!Estimate',
 'ZCTA5 51039!!Estimate',
 'ZCTA5 51040!!Estimate',
 'ZCTA5 51041!!Estimate',
 'ZCTA5 51044!!Estimate',
 'ZCTA5 51046!!Estimate',
 'ZCTA5 51047!!Estimate',
 'ZCTA5 51048!!Estimate',
 'ZCTA5 51049!!Estimate',
 'ZCTA5 51050!!Estimate',
 'ZCTA5 51051!!Estimate',
 'ZCTA5 51052!!Estimate',
 'ZCTA5 51053!!Estimate',
 'ZCTA5 51054!!Estimate',
 'ZCTA5 51055!!Estimate',
 'ZCTA5 51056!!Estimate',
 'ZCTA5 51058!!Estimate',
 'ZCTA5 51060!!Estimate',
 'ZCTA5 51061!!Estimate',
 'ZCTA5 51062!!Estimate',
 'ZCTA5 51063!!Estimate',
 'ZCTA5 51101!!Estimate',
 'ZCTA5 51103!!Estimate',
 'ZCTA5 51104!!Estimate',
 'ZCTA5 51105!!Estimate',
 'ZCTA5 51106!!Estimate',
 'ZCTA5 51108!!Estimate',
 'ZCTA5 51109!!Estimate',
 'ZCTA5 51111!!Estimate',
 'ZCTA5 51201!!Estimate',
 'ZCTA5 51230!!Estimate',
 'ZCTA5 51231!!Estimate',
 'ZCTA5 51232!!Estimate',
 'ZCTA5 51234!!Estimate',
 'ZCTA5 51235!!Estimate',
 'ZCTA5 51237!!Estimate',
 'ZCTA5 51238!!Estimate',
 'ZCTA5 51239!!Estimate',
 'ZCTA5 51240!!Estimate',
 'ZCTA5 51241!!Estimate',
 'ZCTA5 51242!!Estimate',
 'ZCTA5 51243!!Estimate',
 'ZCTA5 51244!!Estimate',
 'ZCTA5 51245!!Estimate',
 'ZCTA5 51246!!Estimate',
 'ZCTA5 51247!!Estimate',
 'ZCTA5 51248!!Estimate',
 'ZCTA5 51249!!Estimate',
 'ZCTA5 51250!!Estimate',
 'ZCTA5 51301!!Estimate',
 'ZCTA5 51331!!Estimate',
 'ZCTA5 51333!!Estimate',
 'ZCTA5 51334!!Estimate',
 'ZCTA5 51338!!Estimate',
 'ZCTA5 51341!!Estimate',
 'ZCTA5 51342!!Estimate',
 'ZCTA5 51343!!Estimate',
 'ZCTA5 51345!!Estimate',
 'ZCTA5 51346!!Estimate',
 'ZCTA5 51347!!Estimate',
 'ZCTA5 51350!!Estimate',
 'ZCTA5 51351!!Estimate',
 'ZCTA5 51354!!Estimate',
 'ZCTA5 51355!!Estimate',
 'ZCTA5 51357!!Estimate',
 'ZCTA5 51358!!Estimate',
 'ZCTA5 51360!!Estimate',
 'ZCTA5 51363!!Estimate',
 'ZCTA5 51364!!Estimate',
 'ZCTA5 51365!!Estimate',
 'ZCTA5 51366!!Estimate',
 'ZCTA5 51401!!Estimate',
 'ZCTA5 51430!!Estimate',
 'ZCTA5 51431!!Estimate',
 'ZCTA5 51433!!Estimate',
 'ZCTA5 51436!!Estimate',
 'ZCTA5 51439!!Estimate',
 'ZCTA5 51440!!Estimate',
 'ZCTA5 51441!!Estimate',
 'ZCTA5 51442!!Estimate',
 'ZCTA5 51443!!Estimate',
 'ZCTA5 51444!!Estimate',
 'ZCTA5 51445!!Estimate',
 'ZCTA5 51446!!Estimate',
 'ZCTA5 51447!!Estimate',
 'ZCTA5 51448!!Estimate',
 'ZCTA5 51449!!Estimate',
 'ZCTA5 51450!!Estimate',
 'ZCTA5 51451!!Estimate',
 'ZCTA5 51453!!Estimate',
 'ZCTA5 51454!!Estimate',
 'ZCTA5 51455!!Estimate',
 'ZCTA5 51458!!Estimate',
 'ZCTA5 51459!!Estimate',
 'ZCTA5 51461!!Estimate',
 'ZCTA5 51462!!Estimate',
 'ZCTA5 51463!!Estimate',
 'ZCTA5 51465!!Estimate',
 'ZCTA5 51466!!Estimate',
 'ZCTA5 51467!!Estimate',
 'ZCTA5 51501!!Estimate',
 'ZCTA5 51503!!Estimate',
 'ZCTA5 51510!!Estimate',
 'ZCTA5 51520!!Estimate',
 'ZCTA5 51521!!Estimate',
 'ZCTA5 51523!!Estimate',
 'ZCTA5 51525!!Estimate',
 'ZCTA5 51526!!Estimate',
 'ZCTA5 51527!!Estimate',
 'ZCTA5 51528!!Estimate',
 'ZCTA5 51529!!Estimate',
 'ZCTA5 51530!!Estimate',
 'ZCTA5 51531!!Estimate',
 'ZCTA5 51532!!Estimate',
 'ZCTA5 51533!!Estimate',
 'ZCTA5 51534!!Estimate',
 'ZCTA5 51535!!Estimate',
 'ZCTA5 51536!!Estimate',
 'ZCTA5 51537!!Estimate',
 'ZCTA5 51540!!Estimate',
 'ZCTA5 51541!!Estimate',
 'ZCTA5 51542!!Estimate',
 'ZCTA5 51543!!Estimate',
 'ZCTA5 51544!!Estimate',
 'ZCTA5 51545!!Estimate',
 'ZCTA5 51546!!Estimate',
 'ZCTA5 51548!!Estimate',
 'ZCTA5 51549!!Estimate',
 'ZCTA5 51550!!Estimate',
 'ZCTA5 51551!!Estimate',
 'ZCTA5 51552!!Estimate',
 'ZCTA5 51553!!Estimate',
 'ZCTA5 51554!!Estimate',
 'ZCTA5 51555!!Estimate',
 'ZCTA5 51556!!Estimate',
 'ZCTA5 51557!!Estimate',
 'ZCTA5 51558!!Estimate',
 'ZCTA5 51559!!Estimate',
 'ZCTA5 51560!!Estimate',
 'ZCTA5 51561!!Estimate',
 'ZCTA5 51562!!Estimate',
 'ZCTA5 51563!!Estimate',
 'ZCTA5 51564!!Estimate',
 'ZCTA5 51565!!Estimate',
 'ZCTA5 51566!!Estimate',
 'ZCTA5 51570!!Estimate',
 'ZCTA5 51571!!Estimate',
 'ZCTA5 51572!!Estimate',
 'ZCTA5 51573!!Estimate',
 'ZCTA5 51575!!Estimate',
 'ZCTA5 51576!!Estimate',
 'ZCTA5 51577!!Estimate',
 'ZCTA5 51578!!Estimate',
 'ZCTA5 51579!!Estimate',
 'ZCTA5 51601!!Estimate',
 'ZCTA5 51630!!Estimate',
 'ZCTA5 51631!!Estimate',
 'ZCTA5 51632!!Estimate',
 'ZCTA5 51636!!Estimate',
 'ZCTA5 51637!!Estimate',
 'ZCTA5 51638!!Estimate',
 'ZCTA5 51639!!Estimate',
 'ZCTA5 51640!!Estimate',
 'ZCTA5 51645!!Estimate',
 'ZCTA5 51646!!Estimate',
 'ZCTA5 51647!!Estimate',
 'ZCTA5 51648!!Estimate',
 'ZCTA5 51649!!Estimate',
 'ZCTA5 51650!!Estimate',
 'ZCTA5 51652!!Estimate',
 'ZCTA5 51653!!Estimate',
 'ZCTA5 51654!!Estimate',
 'ZCTA5 51656!!Estimate',
 'ZCTA5 52001!!Estimate',
 'ZCTA5 52002!!Estimate',
 'ZCTA5 52003!!Estimate',
 'ZCTA5 52030!!Estimate',
 'ZCTA5 52031!!Estimate',
 'ZCTA5 52032!!Estimate',
 'ZCTA5 52033!!Estimate',
 'ZCTA5 52035!!Estimate',
 'ZCTA5 52037!!Estimate',
 'ZCTA5 52038!!Estimate',
 'ZCTA5 52039!!Estimate',
 'ZCTA5 52040!!Estimate',
 'ZCTA5 52041!!Estimate',
 'ZCTA5 52042!!Estimate',
 'ZCTA5 52043!!Estimate',
 'ZCTA5 52044!!Estimate',
 'ZCTA5 52045!!Estimate',
 'ZCTA5 52046!!Estimate',
 'ZCTA5 52047!!Estimate',
 'ZCTA5 52048!!Estimate',
 'ZCTA5 52049!!Estimate',
 'ZCTA5 52050!!Estimate',
 'ZCTA5 52052!!Estimate',
 'ZCTA5 52053!!Estimate',
 'ZCTA5 52054!!Estimate',
 'ZCTA5 52057!!Estimate',
 'ZCTA5 52060!!Estimate',
 'ZCTA5 52064!!Estimate',
 'ZCTA5 52065!!Estimate',
 'ZCTA5 52066!!Estimate',
 'ZCTA5 52068!!Estimate',
 'ZCTA5 52069!!Estimate',
 'ZCTA5 52070!!Estimate',
 'ZCTA5 52072!!Estimate',
 'ZCTA5 52073!!Estimate',
 'ZCTA5 52074!!Estimate',
 'ZCTA5 52076!!Estimate',
 'ZCTA5 52077!!Estimate',
 'ZCTA5 52078!!Estimate',
 'ZCTA5 52079!!Estimate',
 'ZCTA5 52101!!Estimate',
 'ZCTA5 52132!!Estimate',
 'ZCTA5 52133!!Estimate',
 'ZCTA5 52134!!Estimate',
 'ZCTA5 52135!!Estimate',
 'ZCTA5 52136!!Estimate',
 'ZCTA5 52140!!Estimate',
 'ZCTA5 52141!!Estimate',
 'ZCTA5 52142!!Estimate',
 'ZCTA5 52144!!Estimate',
 'ZCTA5 52146!!Estimate',
 'ZCTA5 52147!!Estimate',
 'ZCTA5 52151!!Estimate',
 'ZCTA5 52154!!Estimate',
 'ZCTA5 52155!!Estimate',
 'ZCTA5 52156!!Estimate',
 'ZCTA5 52157!!Estimate',
 'ZCTA5 52158!!Estimate',
 'ZCTA5 52159!!Estimate',
 'ZCTA5 52160!!Estimate',
 'ZCTA5 52161!!Estimate',
 'ZCTA5 52162!!Estimate',
 'ZCTA5 52163!!Estimate',
 'ZCTA5 52164!!Estimate',
 'ZCTA5 52165!!Estimate',
 'ZCTA5 52166!!Estimate',
 'ZCTA5 52168!!Estimate',
 'ZCTA5 52169!!Estimate',
 'ZCTA5 52170!!Estimate',
 'ZCTA5 52171!!Estimate',
 'ZCTA5 52172!!Estimate',
 'ZCTA5 52175!!Estimate',
 'ZCTA5 52201!!Estimate',
 'ZCTA5 52202!!Estimate',
 'ZCTA5 52203!!Estimate',
 'ZCTA5 52205!!Estimate',
 'ZCTA5 52206!!Estimate',
 'ZCTA5 52207!!Estimate',
 'ZCTA5 52208!!Estimate',
 'ZCTA5 52209!!Estimate',
 'ZCTA5 52210!!Estimate',
 'ZCTA5 52211!!Estimate',
 'ZCTA5 52212!!Estimate',
 'ZCTA5 52213!!Estimate',
 'ZCTA5 52214!!Estimate',
 'ZCTA5 52215!!Estimate',
 'ZCTA5 52216!!Estimate',
 'ZCTA5 52217!!Estimate',
 'ZCTA5 52218!!Estimate',
 'ZCTA5 52219!!Estimate',
 'ZCTA5 52220!!Estimate',
 'ZCTA5 52221!!Estimate',
 'ZCTA5 52222!!Estimate',
 'ZCTA5 52223!!Estimate',
 'ZCTA5 52224!!Estimate',
 'ZCTA5 52225!!Estimate',
 'ZCTA5 52227!!Estimate',
 'ZCTA5 52228!!Estimate',
 'ZCTA5 52229!!Estimate',
 'ZCTA5 52231!!Estimate',
 'ZCTA5 52232!!Estimate',
 'ZCTA5 52233!!Estimate',
 'ZCTA5 52235!!Estimate',
 'ZCTA5 52236!!Estimate',
 'ZCTA5 52237!!Estimate',
 'ZCTA5 52240!!Estimate',
 'ZCTA5 52241!!Estimate',
 'ZCTA5 52242!!Estimate',
 'ZCTA5 52245!!Estimate',
 'ZCTA5 52246!!Estimate',
 'ZCTA5 52247!!Estimate',
 'ZCTA5 52248!!Estimate',
 'ZCTA5 52249!!Estimate',
 'ZCTA5 52251!!Estimate',
 'ZCTA5 52253!!Estimate',
 'ZCTA5 52254!!Estimate',
 'ZCTA5 52255!!Estimate',
 'ZCTA5 52257!!Estimate',
 'ZCTA5 52301!!Estimate',
 'ZCTA5 52302!!Estimate',
 'ZCTA5 52305!!Estimate',
 'ZCTA5 52306!!Estimate',
 'ZCTA5 52307!!Estimate',
 'ZCTA5 52308!!Estimate',
 'ZCTA5 52309!!Estimate',
 'ZCTA5 52310!!Estimate',
 'ZCTA5 52312!!Estimate',
 'ZCTA5 52313!!Estimate',
 'ZCTA5 52314!!Estimate',
 'ZCTA5 52315!!Estimate',
 'ZCTA5 52316!!Estimate',
 'ZCTA5 52317!!Estimate',
 'ZCTA5 52318!!Estimate',
 'ZCTA5 52320!!Estimate',
 'ZCTA5 52321!!Estimate',
 'ZCTA5 52322!!Estimate',
 'ZCTA5 52323!!Estimate',
 'ZCTA5 52324!!Estimate',

In [7]:
dp03_new = dp03[new_cols]
dp03_new

,Label (Grouping),ZCTA5 50001!!Estimate,ZCTA5 50002!!Estimate,ZCTA5 50003!!Estimate,ZCTA5 50005!!Estimate,ZCTA5 50006!!Estimate,ZCTA5 50007!!Estimate,ZCTA5 50008!!Estimate,ZCTA5 50009!!Estimate,ZCTA5 50010!!Estimate,...,ZCTA5 52776!!Estimate,ZCTA5 52777!!Estimate,ZCTA5 52778!!Estimate,ZCTA5 52801!!Estimate,ZCTA5 52802!!Estimate,ZCTA5 52803!!Estimate,ZCTA5 52804!!Estimate,ZCTA5 52806!!Estimate,ZCTA5 52807!!Estimate,ZCTA5 56027!!Estimate
0,EMPLOYMENT STATUS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Population 16 years and over,544,"1,087","6,027",864,"1,268",427,679,"15,507","28,723",...,"3,819","1,000","3,178","1,254","8,053","17,389","23,165","21,451","13,016",530
2,In labor force,385,765,"4,431",498,891,313,461,"10,943","19,022",...,"2,597",620,"2,199",619,"4,613","11,496","14,688","13,828","8,222",346
3,Civilian labor force,385,765,"4,405",498,891,313,461,"10,923","19,015",...,"2,597",620,"2,199",619,"4,613","11,458","14,643","13,808","8,193",346
4,Employed,357,724,"4,232",474,859,309,447,"10,390","18,342",...,"2,552",602,"2,196",556,"4,235","11,067","13,892","13,154","7,952",325
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
140,18 years and over,(X),(X),(X),(X),(X),(X),(X),(X),(X),...,(X),(X),(X),(X),(X),(X),(X),(X),(X),(X)
141,18 to 64 years,(X),(X),(X),(X),(X),(X),(X),(X),(X),...,(X),(X),(X),(X),(X),(X),(X),(X),(X),(X)
142,65 years and over,(X),(X),(X),(X),(X),(X),(X),(X),(X),...,(X),(X),(X),(X),(X),(X),(X),(X),(X),(X)
143,People in families,(X),(X),(X),(X),(X),(X),(X),(X),(X),...,(X),(X),(X),(X),(X),(X),(X),(X),(X),(X)
144,Unrelated individuals 15 years and over,(X),(X),(X),(X),(X),(X),(X),(X),(X),...,(X),(X),(X),(X),(X),(X),(X),(X),(X),(X)

In [9]:
pd.set_option('display.max_rows', 146)
dp03_new.head(146)

,Label (Grouping),ZCTA5 50001!!Estimate,ZCTA5 50002!!Estimate,ZCTA5 50003!!Estimate,ZCTA5 50005!!Estimate,ZCTA5 50006!!Estimate,ZCTA5 50007!!Estimate,ZCTA5 50008!!Estimate,ZCTA5 50009!!Estimate,ZCTA5 50010!!Estimate,...,ZCTA5 52776!!Estimate,ZCTA5 52777!!Estimate,ZCTA5 52778!!Estimate,ZCTA5 52801!!Estimate,ZCTA5 52802!!Estimate,ZCTA5 52803!!Estimate,ZCTA5 52804!!Estimate,ZCTA5 52806!!Estimate,ZCTA5 52807!!Estimate,ZCTA5 56027!!Estimate
0,EMPLOYMENT STATUS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Population 16 years and over,544,"1,087","6,027",864,"1,268",427,679,"15,507","28,723",...,"3,819","1,000","3,178","1,254","8,053","17,389","23,165","21,451","13,016",530
2,In labor force,385,765,"4,431",498,891,313,461,"10,943","19,022",...,"2,597",620,"2,199",619,"4,613","11,496","14,688","13,828","8,222",346
3,Civilian labor force,385,765,"4,405",498,891,313,461,"10,923","19,015",...,"2,597",620,"2,199",619,"4,613","11,458","14,643","13,808","8,193",346
4,Employed,357,724,"4,232",474,859,309,447,"10,390","18,342",...,"2,552",602,"2,196",556,"4,235","11,067","13,892","13,154","7,952",325
5,Unemployed,28,41,173,24,32,4,14,533,673,...,45,18,3,63,378,391,751,654,241,21
6,Armed Forces,0,0,26,0,0,0,0,20,7,...,0,0,0,0,0,38,45,20,29,0
7,Not in labor force,159,322,"1,596",366,377,114,218,"4,564","9,701",...,"1,222",380,979,635,"3,440","5,893","8,477","7,623","4,794",184
8,Civilian labor force,385,765,"4,405",498,891,313,461,"10,923","19,015",...,"2,597",620,"2,199",619,"4,613","11,458","14,643","13,808","8,193",346
9,Unemployment Rate,(X),(X),(X),(X),(X),(X),(X),(X),(X),...,(X),(X),(X),(X),(X),(X),(X),(X),(X),(X)
10,Females 16 years and over,276,540,"3,204",521,605,205,372,"8,429","14,155",...,"1,891",534,"1,566",420,"3,886","8,705","11,806","11,823","6,335",260
11,In labor force,158,367,"2,252",303,400,146,226,"5,480","9,189",...,"1,233",371,"1,059",244,"2,134","5,474","6,791","7,438","3,568",139
12,Civilian labor force,158,367,"2,252",303,400,146,226,"5,480","9,189",...,"1,233",371,"1,059",244,"2,134","5,462","6,791","7,438","3,568",139
13,Employed,157,351,"2,144",290,393,143,220,"5,134","8,873",...,"1,221",371,"1,059",233,"2,007","5,267","6,483","7,059","3,443",133
14,Own children of the householder under 6 years,90,102,608,44,104,6,61,"1,605","1,962",...,323,67,309,43,494,"1,469","1,886","2,276","1,294",31
15,All parents in family in labor force,20,90,424,25,80,6,37,"1,138","1,055",...,311,49,241,36,204,975,"1,323","1,882","1,054",25
16,Own children of the householder 6 to 17 years,124,170,"1,349",146,250,127,123,"3,551","3,296",...,"1,014",401,417,19,"1,545","2,625","3,635","4,262","2,311",67
17,All parents in family in labor force,104,165,"1,233",59,235,117,63,"3,261","2,548",...,913,339,401,19,"1,160","2,179","2,453","3,673","1,796",55
18,COMMUTING TO WORK,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,Workers 16 years and over,357,721,"4,149",458,841,305,441,"10,247","17,967",...,"2,507",582,"2,105",545,"4,123","10,951","13,629","12,885","7,948",312
20,"Car, truck, or van -- drove alone",348,622,"3,254",420,663,255,326,"8,819","11,964",...,"2,169",455,"1,750",372,"3,443","9,150","11,439","11,359","6,950",244
21,"Car, truck, or van -- carpooled",8,72,313,22,57,15,11,546,"1,422",...,159,11,103,34,299,544,"1,007",789,249,27
22,Public transportation (excluding taxicab),0,3,15,0,0,0,0,54,"1,351",...,0,3,0,23,27,97,23,81,50,0
23,Walked,0,13,78,0,14,8,59,10,"1,105",...,90,55,94,116,86,374,488,20,61,10
24,Other means,0,0,54,4,0,2,13,179,740,...,17,4,0,0,15,72,110,101,167,4
25,Worked from home,1,11,435,12,107,25,32,639,"1,385",...,72,54,158,0,253,714,562,535,471,27
26,Mean travel time to work (minutes),30.9,20.5,24.4,21.6,18.8,21.7,17.3,22,16.8,...,19.6,28.3,20.7,18.8,19.2,17.2,18.6,18.3,16.4,22.5
27,OCCUPATION,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,Civilian employed population 16 years and ...,357,724,"4,232",474,859,309,447,"10,390","18,342",...,"2,552",602,"2,196",556,"4,235","11,067","13,892","13,154","7,952",325
29,"Management, business, science, and art...",207,245,"2,073",59,268,184,158,"3,988","9,193",...,647,258,825,320,812,"4,212","3,993","4,226","3,900",100
30,Service occupations,24,77,553,210,118,14,123,"1,453","3,166",...,377,93,353,84,734,"2,051","2,916","2,624",932,61
31,Sales and office occupations,64,196,951,72,168,55,40,"2,897","3,235",...,333,112,327,79,"1,104","2,238","2,732","2,712","1,945",40
32,"Natural resources, construction, and m...",20,83,429,22,153,29,59,702,886,...,280,78,316,30,524,940,"1,342","1,029",401,40
33,"Production, transportation, and materi...",42,123,226,111,152,27,67,"1,350","1,862",...,915,61,375,43,"1,061","1,626","2,909","2,563",774,84
34,INDUSTRY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,Civilian employed population 16 years and ...,357,724,"4,232",474,859,309,447,"10,390","18,342",...,"2,552",602,"2,196",556,"4,235","11,067","13,892","13,154","7,952",325
36,"Agriculture, forestry, fishing and hun...",7,62,125,5,161,2,103,62,363,...,105,37,143,0,0,14,74,97,69,55
37,Construction,14,66,400,10,73,35,29,544,708,...,242,148,160,15,333,657,854,759,460,26
38,Manufacturing,27,111,324,38,122,24,39,941,"1,875",...,934,58,418,112,673,"1,657","2,594","2,040","1,122",59
39,Wholesale trade,17,116,143,12,38,10,0,603,283,...,27,24,109,34,92,191,371,222,169,6
40,Retail trade,37,43,394,93,89,29,46,"1,504","1,914",...,107,55,164,11,434,"1,313","1,764","1,753","1,075",28
41,"Transportation and warehousing, and ut...",16,34,110,15,51,20,19,528,457,...,33,32,245,0,371,473,680,891,224,15
42,Information,0,9,104,5,2,1,3,149,445,...,15,4,51,15,41,291,237,236,77,0
43,"Finance and insurance, and real estate...",46,29,745,19,27,57,6,"1,420","1,027",...,91,18,31,19,294,604,736,458,652,9
44,"Professional, scientific, and manageme...",24,71,522,2,40,13,0,868,"1,498",...,125,31,179,124,330,792,"1,270","1,097",672,8
45,"Educational services, and health care ...",120,100,950,89,147,90,103,"2,436","6,707",...,629,103,558,105,793,"2,848","2,703","3,128","1,882",89
46,"Arts, entertainment, and recreation, a...",27,47,103,8,24,9,28,666,"1,717",...,114,53,9,65,492,"1,180","1,296","1,433",830,14
47,"Other services, except public administ...",18,29,181,132,63,4,13,220,613,...,108,31,42,36,262,727,885,438,417,11
48,Public administration,4,7,131,46,22,15,58,449,735,...,22,8,87,20,120,320,428,602,303,5
49,CLASS OF WORKER,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50,Civilian employed population 16 years and ...,357,724,"4,232",474,859,309,447,"10,390","18,342",...,"2,552",602,"2,196",556,"4,235","11,067","13,892","13,154","7,952",325
51,Private wage and salary workers,321,580,"3,349",355,650,260,287,"8,455","12,134",...,"2,048",488,"1,572",492,"3,680","9,192","11,891","11,075","6,942",255
52,Government workers,28,64,531,113,94,46,105,"1,554","5,317",...,400,48,494,64,313,"1,329","1,335","1,638",739,24
53,Self-employed in own not incorporated ...,8,80,338,6,115,3,55,360,874,...,104,66,118,0,232,545,648,393,271,46
54,Unpaid family workers,0,0,14,0,0,0,0,21,17,...,0,0,12,0,10,1,18,48,0,0
55,INCOME AND BENEFITS (IN 2020 INFLATION-ADJUSTE...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56,Total households,266,595,"3,075",380,687,186,378,"7,327","14,239",...,"1,619",526,"1,603",759,"3,853","8,593","10,782","10,804","6,535",320
57,"Less than $10,000",0,31,125,1,32,0,0,180,"1,540",...,27,21,2,161,451,748,820,715,234,8
58,"$10,000 to $14,999",29,3,72,0,22,3,24,105,523,...,25,18,42,63,184,420,422,495,128,10
59,"$15,000 to $24,999",3,39,187,26,66,1,46,249,"1,253",...,135,57,97,179,426,676,"1,053","1,091",759,46
60,"$25,000 to $34,999",5,82,146,98,57,2,59,564,"1,391",...,111,137,264,102,517,775,"1,077",876,534,38
61,"$35,000 to $49,999",30,110,269,49,129,5,76,955,"1,401",...,188,60,179,95,748,"1,218","1,517","1,730",824,68
62,"$50,000 to $74,999",44,78,513,92,133,23,64,"1,274","2,797",...,454,81,326,87,514,"1,677","2,535","2,084","1,150",59
63,"$75,000 to $99,999",37,72,406,73,103,29,79,"1,326","1,685",...,284,49,236,28,415,"1,143","1,349","1,276",737,22
64,"$100,000 to $149,999",75,113,691,39,114,80,22,"1,475","2,091",...,275,84,160,18,484,"1,170","1,403","1,810",924,46
65,"$150,000 to $199,999",21,18,258,2,15,28,8,816,729,...,71,17,164,19,43,358,391,489,655,12
66,"$200,000 or more",22,49,408,0,16,15,0,383,829,...,49,2,133,7,71,408,215,238,590,11
67,Median household income (dollars),"89,773","64,531","88,875","56,250","56,528","137,917","45,833","80,740","57,915",...,"68,022","42,955","62,388","24,067","42,250","55,010","52,395","55,929","65,984","44,500"
68,Mean household income (dollars),"97,570","84,102","122,915","59,130","67,396","129,520","55,192","94,989","76,964",...,"82,486","56,802","95,395","36,112","57,209","80,916","64,723","67,083","91,932","92,893"
69,With earnings,222,476,"2,452",265,558,157,292,"5,934","11,977",...,"1,383",406,"1,277",483,"2,794","6,800","8,115","7,733","5,112",233
70,Mean earnings (dollars),"97,942","89,366","130,414","64,954","68,869","133,455","52,907","94,852","70,753",...,"75,792","56,337","103,709","45,889","61,409","78,293","67,584","71,024","85,304","74,039"
71,With Social Security,65,186,840,169,223,46,145,"2,098","3,528",...,509,181,487,244,"1,102","2,150","3,319","3,739","2,042",127
72,Mean Social Security income (dollars),"24,432","20,199","24,291","25,518","17,372","31,548","15,673","21,744","22,216",...,"22,191","20,433","17,669","12,089","17,924","20,949","18,855","19,556","23,576","18,041"
73,With retirement income,55,101,644,54,70,35,84,"1,748","2,490",...,246,115,279,34,737,"1,498","2,448","2,426","1,622",52
74,Mean retirement income (dollars),"15,975","13,825","29,749","11,493","15,073","27,686","14,508","21,580","28,221",...,"18,364","9,078","14,230","5,691","17,591","22,583","21,197","26,455","35,933","76,954"
75,With Supplemental Security Income,37,13,68,13,23,5,3,430,325,...,149,26,71,95,716,444,616,568,138,18
76,Mean Supplemental Security Income ...,"9,851","16,669","12,438","7,446","8,078","11,240",N,"6,638","13,500",...,"8,502","10,077","7,296","8,778","11,099","11,791","9,738","10,439","9,662","10,111"
77,With cash public assistance income,1,12,74,7,20,0,21,226,215,...,103,8,10,16,252,190,254,147,0,26
78,Mean cash public assistance income...,N,"2,700","2,051",N,N,-,495,"2,344","3,846",...,N,N,N,N,475,"1,822","2,270","2,844",-,"2,135"
79,With Food Stamp/SNAP benefits in the p...,35,61,190,32,29,4,35,645,667,...,212,54,83,138,725,"1,133","1,530","1,286",370,26
80,Families,230,422,"2,063",309,430,167,235,"5,245","7,026",...,"1,184",364,"1,097",79,"2,265","4,817","6,437","6,673","3,977",174
81,"Less than $10,000",0,0,9,0,9,0,0,37,157,...,8,16,2,18,169,207,353,209,42,1
82,"$10,000 to $14,999",28,0,3,0,0,0,14,87,48,...,0,6,0,0,87,135,182,204,36,0
83,"$15,000 to $24,999",3,11,45,4,24,1,5,65,372,...,47,26,43,11,196,149,606,290,290,25
84,"$25,000 to $34,999",2,48,53,85,41,2,30,319,332,...,60,108,147,11,257,393,364,363,279,27
85,"$35,000 to $49,999",12,68,148,37,100,2,22,504,438,...,125,30,92,0,418,531,847,"1,146",316,18
86,"$50,000 to $74,999",42,50,324,74,64,22,72,953,"1,555",...,331,39,274,0,364,950,"1,457","1,457",654,30
87,"$75,000 to $99,999",37,72,278,68,65,26,62,"1,005","1,022",...,238,44,135,13,286,920,"1,040",873,529,19
88,"$100,000 to $149,999",63,110,586,39,96,71,22,"1,218","1,751",...,255,79,160,0,391,963,"1,086","1,478",691,39
89,"$150,000 to $199,999",21,18,240,2,15,28,8,732,604,...,71,14,148,19,58,316,316,481,580,7
90,"$200,000 or more",22,45,377,0,16,15,0,325,747,...,49,2,96,7,39,253,186,172,560,8
91,Median family income (dollars),"93,889","84,167","109,221","60,884","65,625","141,607","64,375","88,296","91,601",...,"80,114","48,333","74,258",-,"50,299","75,503","61,669","68,517","94,052","67,500"
92,Mean family income (dollars),"101,561","94,488","152,247","63,226","78,946","134,799","67,329","105,188","111,037",...,"95,872","63,685","99,238","82,853","64,305","98,653","74,958","80,191","116,871","94,601"
93,Per capita income (dollars),"35,144","36,769","48,809","24,205","29,356","44,064","24,405","35,729","33,059",...,"28,419","21,826","40,394","22,958","23,068","33,977","26,812","27,641","38,219","46,658"
94,Nonfamily households,36,173,"1,012",71,257,19,143,"2,082","7,213",...,435,162,506,680,"1,588","3,776","4,345","4,131","2,558",146
95,Median nonfamily income (dollars),"40,625","28,250","39,857","33,750","40,982","91,250","33,688","47,647","31,351",...,"40,875","35,417","40,703","23,426","31,092","36,843","34,580","33,355","44,398","40,625"
96,Mean nonfamily income (dollars),"70,342","57,290","60,772","38,620","45,077","83,126","32,457","57,842","42,427",...,"42,389","40,210","83,623","30,078","44,033","57,020","44,925","43,105","50,823","85,671"
97,Median earnings for workers (dollars),"48,250","37,759","46,553","32,333","36,979","56,369","28,393","44,049","26,879",...,"34,449","27,375","42,556","24,257","30,053","34,615","32,123","35,724","38,557","33,553"
98,"Median earnings for male full-time, year-r...","66,346","49,674","70,268","49,273","51,331","82,316","45,455","59,818","55,596",...,"42,102","51,875","53,892","38,056","45,407","46,970","50,026","51,440","52,272","40,500"
99,"Median earnings for female full-time, year...","50,000","54,076","52,431","31,530","37,656","55,789","26,635","50,713","44,263",...,"34,871","27,067","44,698","48,750","34,763","43,301","36,390","40,863","50,225","36,538"
100,HEALTH INSURANCE COVERAGE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
101,Civilian noninstitutionalized population,749,"1,359","7,773","1,060","1,596",557,845,"19,914","33,371",...,"4,944","1,374","3,833","1,011","9,849","20,952","28,078","27,647","15,923",618
102,With health insurance coverage,664,"1,284","7,572",847,"1,566",541,787,"19,537","31,373",...,"4,768","1,206","3,776",915,"8,908","19,449","26,243","26,336","15,162",577
103,With private health insurance,512,"1,057","6,862",520,"1,270",499,552,"16,060","27,646",...,"3,822",706,"3,123",608,"5,100","13,674","18,691","18,686","12,325",386
104,With public coverage,212,432,"1,913",452,508,128,386,"6,137","7,622",...,"1,538",691,"1,160",382,"4,791","7,773","11,088","11,735","4,651",286
105,No health insurance coverage,85,75,201,213,30,16,58,377,"1,998",...,176,168,57,96,941,"1,503","1,835","1,311",761,41
106,Civilian noninstitutionalized population u...,241,304,"2,090",222,374,140,188,"5,514","5,782",...,"1,413",522,863,62,"2,386","4,662","6,062","7,215","3,820",110
107,No health insurance coverage,30,32,12,22,5,4,0,88,172,...,12,25,0,0,235,26,183,324,208,3
108,Civilian noninstitutionalized population 1...,417,816,"4,565",562,971,334,482,"11,568","23,047",...,"2,904",607,"2,335",767,"6,277","13,661","17,663","15,801","9,473",349
109,In labor force:,349,696,"4,097",472,809,287,390,"9,912","17,516",...,"2,456",530,"1,998",608,"4,239","10,580","13,723","12,838","7,374",296
110,Employed:,337,655,"3,933",448,783,283,376,"9,525","16,883",...,"2,423",514,"1,995",556,"3,957","10,248","13,015","12,272","7,133",278
111,With health insurance coverage,319,641,"3,789",278,763,275,334,"9,257","15,784",...,"2,315",390,"1,938",521,"3,535","9,293","11,922","11,579","6,861",255
112,With private health insurance,313,602,"3,733",251,704,272,292,"8,675","14,881",...,"2,223",325,"1,856",491,"2,892","8,420","10,524","10,119","6,378",214
113,With public coverage,7,44,234,41,76,10,48,859,"1,177",...,138,69,102,44,839,"1,124","1,674","1,856",584,43
114,No health insurance coverage,18,14,144,170,20,8,42,268,"1,099",...,108,124,57,35,422,955,"1,093",693,272,23
115,Unemployed:,12,41,164,24,26,4,14,387,633,...,33,16,3,52,282,332,708,566,241,18
116,With health insurance coverage,12,15,164,4,25,4,7,378,606,...,25,2,3,6,228,242,591,411,137,15
117,With private health insurance,6,11,121,2,17,4,0,39,527,...,8,2,3,6,81,81,312,213,100,8
118,With public coverage,6,4,54,2,8,0,7,339,82,...,17,0,0,0,147,161,296,227,50,7
119,No health insurance coverage,0,26,0,20,1,0,7,9,27,...,8,14,0,46,54,90,117,155,104,3
120,Not in labor force:,68,120,468,90,162,47,92,"1,656","5,531",...,448,77,337,159,"2,038","3,081","3,940","2,963","2,099",53
121,With health insurance coverage,31,117,426,89,158,43,83,"1,644","4,835",...,400,72,337,144,"1,808","2,649","3,505","2,855","1,922",41
122,With private health insurance,22,75,307,37,96,24,60,"1,045","4,291",...,355,28,251,57,568,"1,098","1,816","1,284","1,285",12
123,With public coverage,12,54,186,65,77,26,23,805,741,...,89,48,154,94,"1,355","1,599","1,910","1,798",637,32
124,No health insurance coverage,37,3,42,1,4,4,9,12,696,...,48,5,0,15,230,432,435,108,177,12
125,PERCENTAGE OF FAMILIES AND PEOPLE WHOSE INCOME...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
126,All families,(X),(X),(X),(X),(X),(X),(X),(X),(X),...,(X),(X),(X),(X),(X),(X),(X),(X),(X),(X)
127,With related children of the household...,(X),(X),(X),(X),(X),(X),(X),(X),(X),...,(X),(X),(X),(X),(X),(X),(X),(X),(X),(X)
128,With related children of the house...,(X),(X),(X),(X),(X),(X),(X),(X),(X),...,(X),(X),(X),(X),(X),(X),(X),(X),(X),(X)
129,Married couple families,(X),(X),(X),(X),(X),(X),(X),(X),(X),...,(X),(X),(X),(X),(X),(X),(X),(X),(X),(X)
130,With related children of the house...,(X),(X),(X),(X),(X),(X),(X),(X),(X),...,(X),(X),(X),(X),(X),(X),(X),(X),(X),(X)
131,With related children of the h...,(X),(X),(X),(X),(X),(X),(X),(X),(X),...,(X),(X),(X),(X),(X),(X),(X),(X),(X),(X)
132,"Families with female householder, no s...",(X),(X),(X),(X),(X),(X),(X),(X),(X),...,(X),(X),(X),(X),(X),(X),(X),(X),(X),(X)
133,With related children of the house...,(X),(X),(X),(X),(X),(X),(X),(X),(X),...,(X),(X),(X),(X),(X),(X),(X),(X),(X),(X)
134,With related children of the h...,(X),(X),(X),(X),(X),(X),(X),(X),(X),...,(X),(X),(X),(X),(X),(X),(X),(X),(X),(X)
135,All people,(X),(X),(X),(X),(X),(X),(X),(X),(X),...,(X),(X),(X),(X),(X),(X),(X),(X),(X),(X)
136,Under 18 years,(X),(X),(X),(X),(X),(X),(X),(X),(X),...,(X),(X),(X),(X),(X),(X),(X),(X),(X),(X)
137,Related children of the householde...,(X),(X),(X),(X),(X),(X),(X),(X),(X),...,(X),(X),(X),(X),(X),(X),(X),(X),(X),(X)
138,Related children of the househ...,(X),(X),(X),(X),(X),(X),(X),(X),(X),...,(X),(X),(X),(X),(X),(X),(X),(X),(X),(X)
139,Related children of the househ...,(X),(X),(X),(X),(X),(X),(X),(X),(X),...,(X),(X),(X),(X),(X),(X),(X),(X),(X),(X)
140,18 years and over,(X),(X),(X),(X),(X),(X),(X),(X),(X),...,(X),(X),(X),(X),(X),(X),(X),(X),(X),(X)
141,18 to 64 years,(X),(X),(X),(X),(X),(X),(X),(X),(X),...,(X),(X),(X),(X),(X),(X),(X),(X),(X),(X)
142,65 years and over,(X),(X),(X),(X),(X),(X),(X),(X),(X),...,(X),(X),(X),(X),(X),(X),(X),(X),(X),(X)
143,People in families,(X),(X),(X),(X),(X),(X),(X),(X),(X),...,(X),(X),(X),(X),(X),(X),(X),(X),(X),(X)
144,Unrelated individuals 15 years and over,(X),(X),(X),(X),(X),(X),(X),(X),(X),...,(X),(X),(X),(X),(X),(X),(X),(X),(X),(X)

In [12]:
dp03_new = dp03_new.drop(range(0,27))

In [16]:
dp03_new = dp03_new.reset_index()

In [18]:
 dp03_new = dp03_new.drop(range(7,28))

In [20]:
dp03_new = dp03_new.reset_index()

In [23]:
dp03_new = dp03_new.drop(range(20,97))

In [30]:
pd.set_option('display.max_rows', 20)
# dp03_new.head(20)

In [28]:
dp03_new = dp03_new.drop(['level_0', 'index'],axis=1)

In [29]:
dp03_new

,Label (Grouping),ZCTA5 50001!!Estimate,ZCTA5 50002!!Estimate,ZCTA5 50003!!Estimate,ZCTA5 50005!!Estimate,ZCTA5 50006!!Estimate,ZCTA5 50007!!Estimate,ZCTA5 50008!!Estimate,ZCTA5 50009!!Estimate,ZCTA5 50010!!Estimate,...,ZCTA5 52776!!Estimate,ZCTA5 52777!!Estimate,ZCTA5 52778!!Estimate,ZCTA5 52801!!Estimate,ZCTA5 52802!!Estimate,ZCTA5 52803!!Estimate,ZCTA5 52804!!Estimate,ZCTA5 52806!!Estimate,ZCTA5 52807!!Estimate,ZCTA5 56027!!Estimate
0,OCCUPATION,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Civilian employed population 16 years and ...,357,724,"4,232",474,859,309,447,"10,390","18,342",...,"2,552",602,"2,196",556,"4,235","11,067","13,892","13,154","7,952",325
2,"Management, business, science, and art...",207,245,"2,073",59,268,184,158,"3,988","9,193",...,647,258,825,320,812,"4,212","3,993","4,226","3,900",100
3,Service occupations,24,77,553,210,118,14,123,"1,453","3,166",...,377,93,353,84,734,"2,051","2,916","2,624",932,61
4,Sales and office occupations,64,196,951,72,168,55,40,"2,897","3,235",...,333,112,327,79,"1,104","2,238","2,732","2,712","1,945",40
5,"Natural resources, construction, and m...",20,83,429,22,153,29,59,702,886,...,280,78,316,30,524,940,"1,342","1,029",401,40
6,"Production, transportation, and materi...",42,123,226,111,152,27,67,"1,350","1,862",...,915,61,375,43,"1,061","1,626","2,909","2,563",774,84
7,INCOME AND BENEFITS (IN 2020 INFLATION-ADJUSTE...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Total households,266,595,"3,075",380,687,186,378,"7,327","14,239",...,"1,619",526,"1,603",759,"3,853","8,593","10,782","10,804","6,535",320
9,"Less than $10,000",0,31,125,1,32,0,0,180,"1,540",...,27,21,2,161,451,748,820,715,234,8
10,"$10,000 to $14,999",29,3,72,0,22,3,24,105,523,...,25,18,42,63,184,420,422,495,128,10
11,"$15,000 to $24,999",3,39,187,26,66,1,46,249,"1,253",...,135,57,97,179,426,676,"1,053","1,091",759,46
12,"$25,000 to $34,999",5,82,146,98,57,2,59,564,"1,391",...,111,137,264,102,517,775,"1,077",876,534,38
13,"$35,000 to $49,999",30,110,269,49,129,5,76,955,"1,401",...,188,60,179,95,748,"1,218","1,517","1,730",824,68
14,"$50,000 to $74,999",44,78,513,92,133,23,64,"1,274","2,797",...,454,81,326,87,514,"1,677","2,535","2,084","1,150",59
15,"$75,000 to $99,999",37,72,406,73,103,29,79,"1,326","1,685",...,284,49,236,28,415,"1,143","1,349","1,276",737,22
16,"$100,000 to $149,999",75,113,691,39,114,80,22,"1,475","2,091",...,275,84,160,18,484,"1,170","1,403","1,810",924,46
17,"$150,000 to $199,999",21,18,258,2,15,28,8,816,729,...,71,17,164,19,43,358,391,489,655,12
18,"$200,000 or more",22,49,408,0,16,15,0,383,829,...,49,2,133,7,71,408,215,238,590,11
19,Median household income (dollars),"89,773","64,531","88,875","56,250","56,528","137,917","45,833","80,740","57,915",...,"68,022","42,955","62,388","24,067","42,250","55,010","52,395","55,929","65,984","44,500"

In [31]:
def get_zip(string):
    L = string.split()
    L2 = L[1]
    L3 = L2.split('!!')
    zip = L3[0]
    return(zip)

In [32]:
cols = list(dp03_new.columns)
cols

['Label (Grouping)',
 'ZCTA5 50001!!Estimate',
 'ZCTA5 50002!!Estimate',
 'ZCTA5 50003!!Estimate',
 'ZCTA5 50005!!Estimate',
 'ZCTA5 50006!!Estimate',
 'ZCTA5 50007!!Estimate',
 'ZCTA5 50008!!Estimate',
 'ZCTA5 50009!!Estimate',
 'ZCTA5 50010!!Estimate',
 'ZCTA5 50011!!Estimate',
 'ZCTA5 50012!!Estimate',
 'ZCTA5 50014!!Estimate',
 'ZCTA5 50020!!Estimate',
 'ZCTA5 50021!!Estimate',
 'ZCTA5 50022!!Estimate',
 'ZCTA5 50023!!Estimate',
 'ZCTA5 50025!!Estimate',
 'ZCTA5 50026!!Estimate',
 'ZCTA5 50027!!Estimate',
 'ZCTA5 50028!!Estimate',
 'ZCTA5 50029!!Estimate',
 'ZCTA5 50032!!Estimate',
 'ZCTA5 50033!!Estimate',
 'ZCTA5 50034!!Estimate',
 'ZCTA5 50035!!Estimate',
 'ZCTA5 50036!!Estimate',
 'ZCTA5 50038!!Estimate',
 'ZCTA5 50039!!Estimate',
 'ZCTA5 50041!!Estimate',
 'ZCTA5 50042!!Estimate',
 'ZCTA5 50044!!Estimate',
 'ZCTA5 50046!!Estimate',
 'ZCTA5 50047!!Estimate',
 'ZCTA5 50048!!Estimate',
 'ZCTA5 50049!!Estimate',
 'ZCTA5 50050!!Estimate',
 'ZCTA5 50051!!Estimate',
 'ZCTA5 50052!!Estimate',
 'ZCTA5 50054!!Estimate',
 'ZCTA5 50055!!Estimate',
 'ZCTA5 50056!!Estimate',
 'ZCTA5 50057!!Estimate',
 'ZCTA5 50058!!Estimate',
 'ZCTA5 50060!!Estimate',
 'ZCTA5 50061!!Estimate',
 'ZCTA5 50062!!Estimate',
 'ZCTA5 50063!!Estimate',
 'ZCTA5 50064!!Estimate',
 'ZCTA5 50065!!Estimate',
 'ZCTA5 50066!!Estimate',
 'ZCTA5 50067!!Estimate',
 'ZCTA5 50068!!Estimate',
 'ZCTA5 50069!!Estimate',
 'ZCTA5 50070!!Estimate',
 'ZCTA5 50071!!Estimate',
 'ZCTA5 50072!!Estimate',
 'ZCTA5 50073!!Estimate',
 'ZCTA5 50074!!Estimate',
 'ZCTA5 50075!!Estimate',
 'ZCTA5 50076!!Estimate',
 'ZCTA5 50078!!Estimate',
 'ZCTA5 50101!!Estimate',
 'ZCTA5 50102!!Estimate',
 'ZCTA5 50103!!Estimate',
 'ZCTA5 50104!!Estimate',
 'ZCTA5 50105!!Estimate',
 'ZCTA5 50106!!Estimate',
 'ZCTA5 50107!!Estimate',
 'ZCTA5 50108!!Estimate',
 'ZCTA5 50109!!Estimate',
 'ZCTA5 50111!!Estimate',
 'ZCTA5 50112!!Estimate',
 'ZCTA5 50115!!Estimate',
 'ZCTA5 50116!!Estimate',
 'ZCTA5 50117!!Estimate',
 'ZCTA5 50118!!Estimate',
 'ZCTA5 50119!!Estimate',
 'ZCTA5 50120!!Estimate',
 'ZCTA5 50122!!Estimate',
 'ZCTA5 50123!!Estimate',
 'ZCTA5 50124!!Estimate',
 'ZCTA5 50125!!Estimate',
 'ZCTA5 50126!!Estimate',
 'ZCTA5 50127!!Estimate',
 'ZCTA5 50128!!Estimate',
 'ZCTA5 50129!!Estimate',
 'ZCTA5 50130!!Estimate',
 'ZCTA5 50131!!Estimate',
 'ZCTA5 50132!!Estimate',
 'ZCTA5 50133!!Estimate',
 'ZCTA5 50134!!Estimate',
 'ZCTA5 50135!!Estimate',
 'ZCTA5 50136!!Estimate',
 'ZCTA5 50138!!Estimate',
 'ZCTA5 50139!!Estimate',
 'ZCTA5 50140!!Estimate',
 'ZCTA5 50141!!Estimate',
 'ZCTA5 50142!!Estimate',
 'ZCTA5 50143!!Estimate',
 'ZCTA5 50144!!Estimate',
 'ZCTA5 50146!!Estimate',
 'ZCTA5 50147!!Estimate',
 'ZCTA5 50148!!Estimate',
 'ZCTA5 50149!!Estimate',
 'ZCTA5 50150!!Estimate',
 'ZCTA5 50151!!Estimate',
 'ZCTA5 50153!!Estimate',
 'ZCTA5 50154!!Estimate',
 'ZCTA5 50155!!Estimate',
 'ZCTA5 50156!!Estimate',
 'ZCTA5 50157!!Estimate',
 'ZCTA5 50158!!Estimate',
 'ZCTA5 50160!!Estimate',
 'ZCTA5 50161!!Estimate',
 'ZCTA5 50162!!Estimate',
 'ZCTA5 50163!!Estimate',
 'ZCTA5 50164!!Estimate',
 'ZCTA5 50165!!Estimate',
 'ZCTA5 50166!!Estimate',
 'ZCTA5 50167!!Estimate',
 'ZCTA5 50168!!Estimate',
 'ZCTA5 50169!!Estimate',
 'ZCTA5 50170!!Estimate',
 'ZCTA5 50171!!Estimate',
 'ZCTA5 50173!!Estimate',
 'ZCTA5 50174!!Estimate',
 'ZCTA5 50201!!Estimate',
 'ZCTA5 50206!!Estimate',
 'ZCTA5 50207!!Estimate',
 'ZCTA5 50208!!Estimate',
 'ZCTA5 50210!!Estimate',
 'ZCTA5 50211!!Estimate',
 'ZCTA5 50212!!Estimate',
 'ZCTA5 50213!!Estimate',
 'ZCTA5 50214!!Estimate',
 'ZCTA5 50216!!Estimate',
 'ZCTA5 50217!!Estimate',
 'ZCTA5 50218!!Estimate',
 'ZCTA5 50219!!Estimate',
 'ZCTA5 50220!!Estimate',
 'ZCTA5 50222!!Estimate',
 'ZCTA5 50223!!Estimate',
 'ZCTA5 50225!!Estimate',
 'ZCTA5 50226!!Estimate',
 'ZCTA5 50227!!Estimate',
 'ZCTA5 50228!!Estimate',
 'ZCTA5 50229!!Estimate',
 'ZCTA5 50230!!Estimate',
 'ZCTA5 50231!!Estimate',
 'ZCTA5 50232!!Estimate',
 'ZCTA5 50233!!Estimate',
 'ZCTA5 50234!!Estimate',
 'ZCTA5 50235!!Estimate',
 'ZCTA5 50236!!Estimate',
 'ZCTA5 50237!!Estimate',
 'ZCTA5 50238!!Estimate',
 'ZCTA5 50239!!Estimate',
 'ZCTA5 50240!!Estimate',
 'ZCTA5 50242!!Estimate',
 'ZCTA5 50243!!Estimate',
 'ZCTA5 50244!!Estimate',
 'ZCTA5 50246!!Estimate',
 'ZCTA5 50247!!Estimate',
 'ZCTA5 50248!!Estimate',
 'ZCTA5 50249!!Estimate',
 'ZCTA5 50250!!Estimate',
 'ZCTA5 50251!!Estimate',
 'ZCTA5 50252!!Estimate',
 'ZCTA5 50254!!Estimate',
 'ZCTA5 50255!!Estimate',
 'ZCTA5 50256!!Estimate',
 'ZCTA5 50257!!Estimate',
 'ZCTA5 50258!!Estimate',
 'ZCTA5 50261!!Estimate',
 'ZCTA5 50262!!Estimate',
 'ZCTA5 50263!!Estimate',
 'ZCTA5 50264!!Estimate',
 'ZCTA5 50265!!Estimate',
 'ZCTA5 50266!!Estimate',
 'ZCTA5 50268!!Estimate',
 'ZCTA5 50271!!Estimate',
 'ZCTA5 50272!!Estimate',
 'ZCTA5 50273!!Estimate',
 'ZCTA5 50274!!Estimate',
 'ZCTA5 50275!!Estimate',
 'ZCTA5 50276!!Estimate',
 'ZCTA5 50277!!Estimate',
 'ZCTA5 50278!!Estimate',
 'ZCTA5 50309!!Estimate',
 'ZCTA5 50310!!Estimate',
 'ZCTA5 50311!!Estimate',
 'ZCTA5 50312!!Estimate',
 'ZCTA5 50313!!Estimate',
 'ZCTA5 50314!!Estimate',
 'ZCTA5 50315!!Estimate',
 'ZCTA5 50316!!Estimate',
 'ZCTA5 50317!!Estimate',
 'ZCTA5 50319!!Estimate',
 'ZCTA5 50320!!Estimate',
 'ZCTA5 50321!!Estimate',
 'ZCTA5 50322!!Estimate',
 'ZCTA5 50323!!Estimate',
 'ZCTA5 50324!!Estimate',
 'ZCTA5 50325!!Estimate',
 'ZCTA5 50327!!Estimate',
 'ZCTA5 50401!!Estimate',
 'ZCTA5 50420!!Estimate',
 'ZCTA5 50421!!Estimate',
 'ZCTA5 50423!!Estimate',
 'ZCTA5 50424!!Estimate',
 'ZCTA5 50426!!Estimate',
 'ZCTA5 50428!!Estimate',
 'ZCTA5 50430!!Estimate',
 'ZCTA5 50431!!Estimate',
 'ZCTA5 50432!!Estimate',
 'ZCTA5 50433!!Estimate',
 'ZCTA5 50434!!Estimate',
 'ZCTA5 50435!!Estimate',
 'ZCTA5 50436!!Estimate',
 'ZCTA5 50438!!Estimate',
 'ZCTA5 50439!!Estimate',
 'ZCTA5 50440!!Estimate',
 'ZCTA5 50441!!Estimate',
 'ZCTA5 50444!!Estimate',
 'ZCTA5 50446!!Estimate',
 'ZCTA5 50447!!Estimate',
 'ZCTA5 50448!!Estimate',
 'ZCTA5 50449!!Estimate',
 'ZCTA5 50450!!Estimate',
 'ZCTA5 50451!!Estimate',
 'ZCTA5 50452!!Estimate',
 'ZCTA5 50453!!Estimate',
 'ZCTA5 50454!!Estimate',
 'ZCTA5 50455!!Estimate',
 'ZCTA5 50456!!Estimate',
 'ZCTA5 50457!!Estimate',
 'ZCTA5 50458!!Estimate',
 'ZCTA5 50459!!Estimate',
 'ZCTA5 50460!!Estimate',
 'ZCTA5 50461!!Estimate',
 'ZCTA5 50464!!Estimate',
 'ZCTA5 50465!!Estimate',
 'ZCTA5 50466!!Estimate',
 'ZCTA5 50467!!Estimate',
 'ZCTA5 50468!!Estimate',
 'ZCTA5 50469!!Estimate',
 'ZCTA5 50470!!Estimate',
 'ZCTA5 50471!!Estimate',
 'ZCTA5 50472!!Estimate',
 'ZCTA5 50473!!Estimate',
 'ZCTA5 50475!!Estimate',
 'ZCTA5 50476!!Estimate',
 'ZCTA5 50477!!Estimate',
 'ZCTA5 50478!!Estimate',
 'ZCTA5 50479!!Estimate',
 'ZCTA5 50480!!Estimate',
 'ZCTA5 50482!!Estimate',
 'ZCTA5 50483!!Estimate',
 'ZCTA5 50484!!Estimate',
 'ZCTA5 50501!!Estimate',
 'ZCTA5 50510!!Estimate',
 'ZCTA5 50511!!Estimate',
 'ZCTA5 50514!!Estimate',
 'ZCTA5 50515!!Estimate',
 'ZCTA5 50516!!Estimate',
 'ZCTA5 50517!!Estimate',
 'ZCTA5 50518!!Estimate',
 'ZCTA5 50519!!Estimate',
 'ZCTA5 50520!!Estimate',
 'ZCTA5 50521!!Estimate',
 'ZCTA5 50522!!Estimate',
 'ZCTA5 50523!!Estimate',
 'ZCTA5 50524!!Estimate',
 'ZCTA5 50525!!Estimate',
 'ZCTA5 50527!!Estimate',
 'ZCTA5 50528!!Estimate',
 'ZCTA5 50529!!Estimate',
 'ZCTA5 50530!!Estimate',
 'ZCTA5 50531!!Estimate',
 'ZCTA5 50532!!Estimate',
 'ZCTA5 50533!!Estimate',
 'ZCTA5 50535!!Estimate',
 'ZCTA5 50536!!Estimate',
 'ZCTA5 50538!!Estimate',
 'ZCTA5 50539!!Estimate',
 'ZCTA5 50540!!Estimate',
 'ZCTA5 50541!!Estimate',
 'ZCTA5 50542!!Estimate',
 'ZCTA5 50543!!Estimate',
 'ZCTA5 50544!!Estimate',
 'ZCTA5 50545!!Estimate',
 'ZCTA5 50546!!Estimate',
 'ZCTA5 50548!!Estimate',
 'ZCTA5 50551!!Estimate',
 'ZCTA5 50554!!Estimate',
 'ZCTA5 50556!!Estimate',
 'ZCTA5 50557!!Estimate',
 'ZCTA5 50558!!Estimate',
 'ZCTA5 50559!!Estimate',
 'ZCTA5 50560!!Estimate',
 'ZCTA5 50561!!Estimate',
 'ZCTA5 50562!!Estimate',
 'ZCTA5 50563!!Estimate',
 'ZCTA5 50565!!Estimate',
 'ZCTA5 50566!!Estimate',
 'ZCTA5 50567!!Estimate',
 'ZCTA5 50568!!Estimate',
 'ZCTA5 50569!!Estimate',
 'ZCTA5 50570!!Estimate',
 'ZCTA5 50571!!Estimate',
 'ZCTA5 50573!!Estimate',
 'ZCTA5 50574!!Estimate',
 'ZCTA5 50575!!Estimate',
 'ZCTA5 50576!!Estimate',
 'ZCTA5 50577!!Estimate',
 'ZCTA5 50578!!Estimate',
 'ZCTA5 50579!!Estimate',
 'ZCTA5 50581!!Estimate',
 'ZCTA5 50582!!Estimate',
 'ZCTA5 50583!!Estimate',
 'ZCTA5 50585!!Estimate',
 'ZCTA5 50586!!Estimate',
 'ZCTA5 50588!!Estimate',
 'ZCTA5 50590!!Estimate',
 'ZCTA5 50591!!Estimate',
 'ZCTA5 50593!!Estimate',
 'ZCTA5 50594!!Estimate',
 'ZCTA5 50595!!Estimate',
 'ZCTA5 50597!!Estimate',
 'ZCTA5 50598!!Estimate',
 'ZCTA5 50599!!Estimate',
 'ZCTA5 50601!!Estimate',
 'ZCTA5 50602!!Estimate',
 'ZCTA5 50603!!Estimate',
 'ZCTA5 50604!!Estimate',
 'ZCTA5 50605!!Estimate',
 'ZCTA5 50606!!Estimate',
 'ZCTA5 50607!!Estimate',
 'ZCTA5 50609!!Estimate',
 'ZCTA5 50611!!Estimate',
 'ZCTA5 50612!!Estimate',
 'ZCTA5 50613!!Estimate',
 'ZCTA5 50616!!Estimate',
 'ZCTA5 50619!!Estimate',
 'ZCTA5 50620!!Estimate',
 'ZCTA5 50621!!Estimate',
 'ZCTA5 50622!!Estimate',
 'ZCTA5 50624!!Estimate',
 'ZCTA5 50625!!Estimate',
 'ZCTA5 50626!!Estimate',
 'ZCTA5 50627!!Estimate',
 'ZCTA5 50628!!Estimate',
 'ZCTA5 50629!!Estimate',
 'ZCTA5 50630!!Estimate',
 'ZCTA5 50632!!Estimate',
 'ZCTA5 50633!!Estimate',
 'ZCTA5 50634!!Estimate',
 'ZCTA5 50635!!Estimate',
 'ZCTA5 50636!!Estimate',
 'ZCTA5 50638!!Estimate',
 'ZCTA5 50641!!Estimate',
 'ZCTA5 50642!!Estimate',
 'ZCTA5 50643!!Estimate',
 'ZCTA5 50644!!Estimate',
 'ZCTA5 50645!!Estimate',
 'ZCTA5 50647!!Estimate',
 'ZCTA5 50648!!Estimate',
 'ZCTA5 50650!!Estimate',
 'ZCTA5 50651!!Estimate',
 'ZCTA5 50652!!Estimate',
 'ZCTA5 50653!!Estimate',
 'ZCTA5 50654!!Estimate',
 'ZCTA5 50655!!Estimate',
 'ZCTA5 50658!!Estimate',
 'ZCTA5 50659!!Estimate',
 'ZCTA5 50660!!Estimate',
 'ZCTA5 50662!!Estimate',
 'ZCTA5 50664!!Estimate',
 'ZCTA5 50665!!Estimate',
 'ZCTA5 50666!!Estimate',
 'ZCTA5 50667!!Estimate',
 'ZCTA5 50668!!Estimate',
 'ZCTA5 50669!!Estimate',
 'ZCTA5 50670!!Estimate',
 'ZCTA5 50671!!Estimate',
 'ZCTA5 50672!!Estimate',
 'ZCTA5 50673!!Estimate',
 'ZCTA5 50674!!Estimate',
 'ZCTA5 50675!!Estimate',
 'ZCTA5 50676!!Estimate',
 'ZCTA5 50677!!Estimate',
 'ZCTA5 50680!!Estimate',
 'ZCTA5 50681!!Estimate',
 'ZCTA5 50682!!Estimate',
 'ZCTA5 50701!!Estimate',
 'ZCTA5 50702!!Estimate',
 'ZCTA5 50703!!Estimate',
 'ZCTA5 50707!!Estimate',
 'ZCTA5 50801!!Estimate',
 'ZCTA5 50830!!Estimate',
 'ZCTA5 50833!!Estimate',
 'ZCTA5 50835!!Estimate',
 'ZCTA5 50836!!Estimate',
 'ZCTA5 50837!!Estimate',
 'ZCTA5 50839!!Estimate',
 'ZCTA5 50840!!Estimate',
 'ZCTA5 50841!!Estimate',
 'ZCTA5 50842!!Estimate',
 'ZCTA5 50843!!Estimate',
 'ZCTA5 50845!!Estimate',
 'ZCTA5 50846!!Estimate',
 'ZCTA5 50847!!Estimate',
 'ZCTA5 50848!!Estimate',
 'ZCTA5 50849!!Estimate',
 'ZCTA5 50851!!Estimate',
 'ZCTA5 50853!!Estimate',
 'ZCTA5 50854!!Estimate',
 'ZCTA5 50857!!Estimate',
 'ZCTA5 50858!!Estimate',
 'ZCTA5 50859!!Estimate',
 'ZCTA5 50860!!Estimate',
 'ZCTA5 50861!!Estimate',
 'ZCTA5 50862!!Estimate',
 'ZCTA5 50863!!Estimate',
 'ZCTA5 50864!!Estimate',
 'ZCTA5 51001!!Estimate',
 'ZCTA5 51002!!Estimate',
 'ZCTA5 51003!!Estimate',
 'ZCTA5 51004!!Estimate',
 'ZCTA5 51005!!Estimate',
 'ZCTA5 51006!!Estimate',
 'ZCTA5 51007!!Estimate',
 'ZCTA5 51008!!Estimate',
 'ZCTA5 51009!!Estimate',
 'ZCTA5 51010!!Estimate',
 'ZCTA5 51011!!Estimate',
 'ZCTA5 51012!!Estimate',
 'ZCTA5 51014!!Estimate',
 'ZCTA5 51016!!Estimate',
 'ZCTA5 51018!!Estimate',
 'ZCTA5 51019!!Estimate',
 'ZCTA5 51020!!Estimate',
 'ZCTA5 51022!!Estimate',
 'ZCTA5 51023!!Estimate',
 'ZCTA5 51024!!Estimate',
 'ZCTA5 51025!!Estimate',
 'ZCTA5 51026!!Estimate',
 'ZCTA5 51027!!Estimate',
 'ZCTA5 51028!!Estimate',
 'ZCTA5 51029!!Estimate',
 'ZCTA5 51030!!Estimate',
 'ZCTA5 51031!!Estimate',
 'ZCTA5 51033!!Estimate',
 'ZCTA5 51034!!Estimate',
 'ZCTA5 51035!!Estimate',
 'ZCTA5 51036!!Estimate',
 'ZCTA5 51037!!Estimate',
 'ZCTA5 51038!!Estimate',
 'ZCTA5 51039!!Estimate',
 'ZCTA5 51040!!Estimate',
 'ZCTA5 51041!!Estimate',
 'ZCTA5 51044!!Estimate',
 'ZCTA5 51046!!Estimate',
 'ZCTA5 51047!!Estimate',
 'ZCTA5 51048!!Estimate',
 'ZCTA5 51049!!Estimate',
 'ZCTA5 51050!!Estimate',
 'ZCTA5 51051!!Estimate',
 'ZCTA5 51052!!Estimate',
 'ZCTA5 51053!!Estimate',
 'ZCTA5 51054!!Estimate',
 'ZCTA5 51055!!Estimate',
 'ZCTA5 51056!!Estimate',
 'ZCTA5 51058!!Estimate',
 'ZCTA5 51060!!Estimate',
 'ZCTA5 51061!!Estimate',
 'ZCTA5 51062!!Estimate',
 'ZCTA5 51063!!Estimate',
 'ZCTA5 51101!!Estimate',
 'ZCTA5 51103!!Estimate',
 'ZCTA5 51104!!Estimate',
 'ZCTA5 51105!!Estimate',
 'ZCTA5 51106!!Estimate',
 'ZCTA5 51108!!Estimate',
 'ZCTA5 51109!!Estimate',
 'ZCTA5 51111!!Estimate',
 'ZCTA5 51201!!Estimate',
 'ZCTA5 51230!!Estimate',
 'ZCTA5 51231!!Estimate',
 'ZCTA5 51232!!Estimate',
 'ZCTA5 51234!!Estimate',
 'ZCTA5 51235!!Estimate',
 'ZCTA5 51237!!Estimate',
 'ZCTA5 51238!!Estimate',
 'ZCTA5 51239!!Estimate',
 'ZCTA5 51240!!Estimate',
 'ZCTA5 51241!!Estimate',
 'ZCTA5 51242!!Estimate',
 'ZCTA5 51243!!Estimate',
 'ZCTA5 51244!!Estimate',
 'ZCTA5 51245!!Estimate',
 'ZCTA5 51246!!Estimate',
 'ZCTA5 51247!!Estimate',
 'ZCTA5 51248!!Estimate',
 'ZCTA5 51249!!Estimate',
 'ZCTA5 51250!!Estimate',
 'ZCTA5 51301!!Estimate',
 'ZCTA5 51331!!Estimate',
 'ZCTA5 51333!!Estimate',
 'ZCTA5 51334!!Estimate',
 'ZCTA5 51338!!Estimate',
 'ZCTA5 51341!!Estimate',
 'ZCTA5 51342!!Estimate',
 'ZCTA5 51343!!Estimate',
 'ZCTA5 51345!!Estimate',
 'ZCTA5 51346!!Estimate',
 'ZCTA5 51347!!Estimate',
 'ZCTA5 51350!!Estimate',
 'ZCTA5 51351!!Estimate',
 'ZCTA5 51354!!Estimate',
 'ZCTA5 51355!!Estimate',
 'ZCTA5 51357!!Estimate',
 'ZCTA5 51358!!Estimate',
 'ZCTA5 51360!!Estimate',
 'ZCTA5 51363!!Estimate',
 'ZCTA5 51364!!Estimate',
 'ZCTA5 51365!!Estimate',
 'ZCTA5 51366!!Estimate',
 'ZCTA5 51401!!Estimate',
 'ZCTA5 51430!!Estimate',
 'ZCTA5 51431!!Estimate',
 'ZCTA5 51433!!Estimate',
 'ZCTA5 51436!!Estimate',
 'ZCTA5 51439!!Estimate',
 'ZCTA5 51440!!Estimate',
 'ZCTA5 51441!!Estimate',
 'ZCTA5 51442!!Estimate',
 'ZCTA5 51443!!Estimate',
 'ZCTA5 51444!!Estimate',
 'ZCTA5 51445!!Estimate',
 'ZCTA5 51446!!Estimate',
 'ZCTA5 51447!!Estimate',
 'ZCTA5 51448!!Estimate',
 'ZCTA5 51449!!Estimate',
 'ZCTA5 51450!!Estimate',
 'ZCTA5 51451!!Estimate',
 'ZCTA5 51453!!Estimate',
 'ZCTA5 51454!!Estimate',
 'ZCTA5 51455!!Estimate',
 'ZCTA5 51458!!Estimate',
 'ZCTA5 51459!!Estimate',
 'ZCTA5 51461!!Estimate',
 'ZCTA5 51462!!Estimate',
 'ZCTA5 51463!!Estimate',
 'ZCTA5 51465!!Estimate',
 'ZCTA5 51466!!Estimate',
 'ZCTA5 51467!!Estimate',
 'ZCTA5 51501!!Estimate',
 'ZCTA5 51503!!Estimate',
 'ZCTA5 51510!!Estimate',
 'ZCTA5 51520!!Estimate',
 'ZCTA5 51521!!Estimate',
 'ZCTA5 51523!!Estimate',
 'ZCTA5 51525!!Estimate',
 'ZCTA5 51526!!Estimate',
 'ZCTA5 51527!!Estimate',
 'ZCTA5 51528!!Estimate',
 'ZCTA5 51529!!Estimate',
 'ZCTA5 51530!!Estimate',
 'ZCTA5 51531!!Estimate',
 'ZCTA5 51532!!Estimate',
 'ZCTA5 51533!!Estimate',
 'ZCTA5 51534!!Estimate',
 'ZCTA5 51535!!Estimate',
 'ZCTA5 51536!!Estimate',
 'ZCTA5 51537!!Estimate',
 'ZCTA5 51540!!Estimate',
 'ZCTA5 51541!!Estimate',
 'ZCTA5 51542!!Estimate',
 'ZCTA5 51543!!Estimate',
 'ZCTA5 51544!!Estimate',
 'ZCTA5 51545!!Estimate',
 'ZCTA5 51546!!Estimate',
 'ZCTA5 51548!!Estimate',
 'ZCTA5 51549!!Estimate',
 'ZCTA5 51550!!Estimate',
 'ZCTA5 51551!!Estimate',
 'ZCTA5 51552!!Estimate',
 'ZCTA5 51553!!Estimate',
 'ZCTA5 51554!!Estimate',
 'ZCTA5 51555!!Estimate',
 'ZCTA5 51556!!Estimate',
 'ZCTA5 51557!!Estimate',
 'ZCTA5 51558!!Estimate',
 'ZCTA5 51559!!Estimate',
 'ZCTA5 51560!!Estimate',
 'ZCTA5 51561!!Estimate',
 'ZCTA5 51562!!Estimate',
 'ZCTA5 51563!!Estimate',
 'ZCTA5 51564!!Estimate',
 'ZCTA5 51565!!Estimate',
 'ZCTA5 51566!!Estimate',
 'ZCTA5 51570!!Estimate',
 'ZCTA5 51571!!Estimate',
 'ZCTA5 51572!!Estimate',
 'ZCTA5 51573!!Estimate',
 'ZCTA5 51575!!Estimate',
 'ZCTA5 51576!!Estimate',
 'ZCTA5 51577!!Estimate',
 'ZCTA5 51578!!Estimate',
 'ZCTA5 51579!!Estimate',
 'ZCTA5 51601!!Estimate',
 'ZCTA5 51630!!Estimate',
 'ZCTA5 51631!!Estimate',
 'ZCTA5 51632!!Estimate',
 'ZCTA5 51636!!Estimate',
 'ZCTA5 51637!!Estimate',
 'ZCTA5 51638!!Estimate',
 'ZCTA5 51639!!Estimate',
 'ZCTA5 51640!!Estimate',
 'ZCTA5 51645!!Estimate',
 'ZCTA5 51646!!Estimate',
 'ZCTA5 51647!!Estimate',
 'ZCTA5 51648!!Estimate',
 'ZCTA5 51649!!Estimate',
 'ZCTA5 51650!!Estimate',
 'ZCTA5 51652!!Estimate',
 'ZCTA5 51653!!Estimate',
 'ZCTA5 51654!!Estimate',
 'ZCTA5 51656!!Estimate',
 'ZCTA5 52001!!Estimate',
 'ZCTA5 52002!!Estimate',
 'ZCTA5 52003!!Estimate',
 'ZCTA5 52030!!Estimate',
 'ZCTA5 52031!!Estimate',
 'ZCTA5 52032!!Estimate',
 'ZCTA5 52033!!Estimate',
 'ZCTA5 52035!!Estimate',
 'ZCTA5 52037!!Estimate',
 'ZCTA5 52038!!Estimate',
 'ZCTA5 52039!!Estimate',
 'ZCTA5 52040!!Estimate',
 'ZCTA5 52041!!Estimate',
 'ZCTA5 52042!!Estimate',
 'ZCTA5 52043!!Estimate',
 'ZCTA5 52044!!Estimate',
 'ZCTA5 52045!!Estimate',
 'ZCTA5 52046!!Estimate',
 'ZCTA5 52047!!Estimate',
 'ZCTA5 52048!!Estimate',
 'ZCTA5 52049!!Estimate',
 'ZCTA5 52050!!Estimate',
 'ZCTA5 52052!!Estimate',
 'ZCTA5 52053!!Estimate',
 'ZCTA5 52054!!Estimate',
 'ZCTA5 52057!!Estimate',
 'ZCTA5 52060!!Estimate',
 'ZCTA5 52064!!Estimate',
 'ZCTA5 52065!!Estimate',
 'ZCTA5 52066!!Estimate',
 'ZCTA5 52068!!Estimate',
 'ZCTA5 52069!!Estimate',
 'ZCTA5 52070!!Estimate',
 'ZCTA5 52072!!Estimate',
 'ZCTA5 52073!!Estimate',
 'ZCTA5 52074!!Estimate',
 'ZCTA5 52076!!Estimate',
 'ZCTA5 52077!!Estimate',
 'ZCTA5 52078!!Estimate',
 'ZCTA5 52079!!Estimate',
 'ZCTA5 52101!!Estimate',
 'ZCTA5 52132!!Estimate',
 'ZCTA5 52133!!Estimate',
 'ZCTA5 52134!!Estimate',
 'ZCTA5 52135!!Estimate',
 'ZCTA5 52136!!Estimate',
 'ZCTA5 52140!!Estimate',
 'ZCTA5 52141!!Estimate',
 'ZCTA5 52142!!Estimate',
 'ZCTA5 52144!!Estimate',
 'ZCTA5 52146!!Estimate',
 'ZCTA5 52147!!Estimate',
 'ZCTA5 52151!!Estimate',
 'ZCTA5 52154!!Estimate',
 'ZCTA5 52155!!Estimate',
 'ZCTA5 52156!!Estimate',
 'ZCTA5 52157!!Estimate',
 'ZCTA5 52158!!Estimate',
 'ZCTA5 52159!!Estimate',
 'ZCTA5 52160!!Estimate',
 'ZCTA5 52161!!Estimate',
 'ZCTA5 52162!!Estimate',
 'ZCTA5 52163!!Estimate',
 'ZCTA5 52164!!Estimate',
 'ZCTA5 52165!!Estimate',
 'ZCTA5 52166!!Estimate',
 'ZCTA5 52168!!Estimate',
 'ZCTA5 52169!!Estimate',
 'ZCTA5 52170!!Estimate',
 'ZCTA5 52171!!Estimate',
 'ZCTA5 52172!!Estimate',
 'ZCTA5 52175!!Estimate',
 'ZCTA5 52201!!Estimate',
 'ZCTA5 52202!!Estimate',
 'ZCTA5 52203!!Estimate',
 'ZCTA5 52205!!Estimate',
 'ZCTA5 52206!!Estimate',
 'ZCTA5 52207!!Estimate',
 'ZCTA5 52208!!Estimate',
 'ZCTA5 52209!!Estimate',
 'ZCTA5 52210!!Estimate',
 'ZCTA5 52211!!Estimate',
 'ZCTA5 52212!!Estimate',
 'ZCTA5 52213!!Estimate',
 'ZCTA5 52214!!Estimate',
 'ZCTA5 52215!!Estimate',
 'ZCTA5 52216!!Estimate',
 'ZCTA5 52217!!Estimate',
 'ZCTA5 52218!!Estimate',
 'ZCTA5 52219!!Estimate',
 'ZCTA5 52220!!Estimate',
 'ZCTA5 52221!!Estimate',
 'ZCTA5 52222!!Estimate',
 'ZCTA5 52223!!Estimate',
 'ZCTA5 52224!!Estimate',
 'ZCTA5 52225!!Estimate',
 'ZCTA5 52227!!Estimate',
 'ZCTA5 52228!!Estimate',
 'ZCTA5 52229!!Estimate',
 'ZCTA5 52231!!Estimate',
 'ZCTA5 52232!!Estimate',
 'ZCTA5 52233!!Estimate',
 'ZCTA5 52235!!Estimate',
 'ZCTA5 52236!!Estimate',
 'ZCTA5 52237!!Estimate',
 'ZCTA5 52240!!Estimate',
 'ZCTA5 52241!!Estimate',
 'ZCTA5 52242!!Estimate',
 'ZCTA5 52245!!Estimate',
 'ZCTA5 52246!!Estimate',
 'ZCTA5 52247!!Estimate',
 'ZCTA5 52248!!Estimate',
 'ZCTA5 52249!!Estimate',
 'ZCTA5 52251!!Estimate',
 'ZCTA5 52253!!Estimate',
 'ZCTA5 52254!!Estimate',
 'ZCTA5 52255!!Estimate',
 'ZCTA5 52257!!Estimate',
 'ZCTA5 52301!!Estimate',
 'ZCTA5 52302!!Estimate',
 'ZCTA5 52305!!Estimate',
 'ZCTA5 52306!!Estimate',
 'ZCTA5 52307!!Estimate',
 'ZCTA5 52308!!Estimate',
 'ZCTA5 52309!!Estimate',
 'ZCTA5 52310!!Estimate',
 'ZCTA5 52312!!Estimate',
 'ZCTA5 52313!!Estimate',
 'ZCTA5 52314!!Estimate',
 'ZCTA5 52315!!Estimate',
 'ZCTA5 52316!!Estimate',
 'ZCTA5 52317!!Estimate',
 'ZCTA5 52318!!Estimate',
 'ZCTA5 52320!!Estimate',
 'ZCTA5 52321!!Estimate',
 'ZCTA5 52322!!Estimate',
 'ZCTA5 52323!!Estimate',
 'ZCTA5 52324!!Estimate',

In [33]:
new_cols = ['Label' if 'Label' in col_name   else get_zip(col_name) for col_name in cols]

In [34]:
new_cols

['Label',
 '50001',
 '50002',
 '50003',
 '50005',
 '50006',
 '50007',
 '50008',
 '50009',
 '50010',
 '50011',
 '50012',
 '50014',
 '50020',
 '50021',
 '50022',
 '50023',
 '50025',
 '50026',
 '50027',
 '50028',
 '50029',
 '50032',
 '50033',
 '50034',
 '50035',
 '50036',
 '50038',
 '50039',
 '50041',
 '50042',
 '50044',
 '50046',
 '50047',
 '50048',
 '50049',
 '50050',
 '50051',
 '50052',
 '50054',
 '50055',
 '50056',
 '50057',
 '50058',
 '50060',
 '50061',
 '50062',
 '50063',
 '50064',
 '50065',
 '50066',
 '50067',
 '50068',
 '50069',
 '50070',
 '50071',
 '50072',
 '50073',
 '50074',
 '50075',
 '50076',
 '50078',
 '50101',
 '50102',
 '50103',
 '50104',
 '50105',
 '50106',
 '50107',
 '50108',
 '50109',
 '50111',
 '50112',
 '50115',
 '50116',
 '50117',
 '50118',
 '50119',
 '50120',
 '50122',
 '50123',
 '50124',
 '50125',
 '50126',
 '50127',
 '50128',
 '50129',
 '50130',
 '50131',
 '50132',
 '50133',
 '50134',
 '50135',
 '50136',
 '50138',
 '50139',
 '50140',
 '50141',
 '50142',
 '50143',
 '50144',
 '50146',
 '50147',
 '50148',
 '50149',
 '50150',
 '50151',
 '50153',
 '50154',
 '50155',
 '50156',
 '50157',
 '50158',
 '50160',
 '50161',
 '50162',
 '50163',
 '50164',
 '50165',
 '50166',
 '50167',
 '50168',
 '50169',
 '50170',
 '50171',
 '50173',
 '50174',
 '50201',
 '50206',
 '50207',
 '50208',
 '50210',
 '50211',
 '50212',
 '50213',
 '50214',
 '50216',
 '50217',
 '50218',
 '50219',
 '50220',
 '50222',
 '50223',
 '50225',
 '50226',
 '50227',
 '50228',
 '50229',
 '50230',
 '50231',
 '50232',
 '50233',
 '50234',
 '50235',
 '50236',
 '50237',
 '50238',
 '50239',
 '50240',
 '50242',
 '50243',
 '50244',
 '50246',
 '50247',
 '50248',
 '50249',
 '50250',
 '50251',
 '50252',
 '50254',
 '50255',
 '50256',
 '50257',
 '50258',
 '50261',
 '50262',
 '50263',
 '50264',
 '50265',
 '50266',
 '50268',
 '50271',
 '50272',
 '50273',
 '50274',
 '50275',
 '50276',
 '50277',
 '50278',
 '50309',
 '50310',
 '50311',
 '50312',
 '50313',
 '50314',
 '50315',
 '50316',
 '50317',
 '50319',
 '50320',
 '50321',
 '50322',
 '50323',
 '50324',
 '50325',
 '50327',
 '50401',
 '50420',
 '50421',
 '50423',
 '50424',
 '50426',
 '50428',
 '50430',
 '50431',
 '50432',
 '50433',
 '50434',
 '50435',
 '50436',
 '50438',
 '50439',
 '50440',
 '50441',
 '50444',
 '50446',
 '50447',
 '50448',
 '50449',
 '50450',
 '50451',
 '50452',
 '50453',
 '50454',
 '50455',
 '50456',
 '50457',
 '50458',
 '50459',
 '50460',
 '50461',
 '50464',
 '50465',
 '50466',
 '50467',
 '50468',
 '50469',
 '50470',
 '50471',
 '50472',
 '50473',
 '50475',
 '50476',
 '50477',
 '50478',
 '50479',
 '50480',
 '50482',
 '50483',
 '50484',
 '50501',
 '50510',
 '50511',
 '50514',
 '50515',
 '50516',
 '50517',
 '50518',
 '50519',
 '50520',
 '50521',
 '50522',
 '50523',
 '50524',
 '50525',
 '50527',
 '50528',
 '50529',
 '50530',
 '50531',
 '50532',
 '50533',
 '50535',
 '50536',
 '50538',
 '50539',
 '50540',
 '50541',
 '50542',
 '50543',
 '50544',
 '50545',
 '50546',
 '50548',
 '50551',
 '50554',
 '50556',
 '50557',
 '50558',
 '50559',
 '50560',
 '50561',
 '50562',
 '50563',
 '50565',
 '50566',
 '50567',
 '50568',
 '50569',
 '50570',
 '50571',
 '50573',
 '50574',
 '50575',
 '50576',
 '50577',
 '50578',
 '50579',
 '50581',
 '50582',
 '50583',
 '50585',
 '50586',
 '50588',
 '50590',
 '50591',
 '50593',
 '50594',
 '50595',
 '50597',
 '50598',
 '50599',
 '50601',
 '50602',
 '50603',
 '50604',
 '50605',
 '50606',
 '50607',
 '50609',
 '50611',
 '50612',
 '50613',
 '50616',
 '50619',
 '50620',
 '50621',
 '50622',
 '50624',
 '50625',
 '50626',
 '50627',
 '50628',
 '50629',
 '50630',
 '50632',
 '50633',
 '50634',
 '50635',
 '50636',
 '50638',
 '50641',
 '50642',
 '50643',
 '50644',
 '50645',
 '50647',
 '50648',
 '50650',
 '50651',
 '50652',
 '50653',
 '50654',
 '50655',
 '50658',
 '50659',
 '50660',
 '50662',
 '50664',
 '50665',
 '50666',
 '50667',
 '50668',
 '50669',
 '50670',
 '50671',
 '50672',
 '50673',
 '50674',
 '50675',
 '50676',
 '50677',
 '50680',
 '50681',
 '50682',
 '50701',
 '50702',
 '50703',
 '50707',
 '50801',
 '50830',
 '50833',
 '50835',
 '50836',
 '50837',
 '50839',
 '50840',
 '50841',
 '50842',
 '50843',
 '50845',
 '50846',
 '50847',
 '50848',
 '50849',
 '50851',
 '50853',
 '50854',
 '50857',
 '50858',
 '50859',
 '50860',
 '50861',
 '50862',
 '50863',
 '50864',
 '51001',
 '51002',
 '51003',
 '51004',
 '51005',
 '51006',
 '51007',
 '51008',
 '51009',
 '51010',
 '51011',
 '51012',
 '51014',
 '51016',
 '51018',
 '51019',
 '51020',
 '51022',
 '51023',
 '51024',
 '51025',
 '51026',
 '51027',
 '51028',
 '51029',
 '51030',
 '51031',
 '51033',
 '51034',
 '51035',
 '51036',
 '51037',
 '51038',
 '51039',
 '51040',
 '51041',
 '51044',
 '51046',
 '51047',
 '51048',
 '51049',
 '51050',
 '51051',
 '51052',
 '51053',
 '51054',
 '51055',
 '51056',
 '51058',
 '51060',
 '51061',
 '51062',
 '51063',
 '51101',
 '51103',
 '51104',
 '51105',
 '51106',
 '51108',
 '51109',
 '51111',
 '51201',
 '51230',
 '51231',
 '51232',
 '51234',
 '51235',
 '51237',
 '51238',
 '51239',
 '51240',
 '51241',
 '51242',
 '51243',
 '51244',
 '51245',
 '51246',
 '51247',
 '51248',
 '51249',
 '51250',
 '51301',
 '51331',
 '51333',
 '51334',
 '51338',
 '51341',
 '51342',
 '51343',
 '51345',
 '51346',
 '51347',
 '51350',
 '51351',
 '51354',
 '51355',
 '51357',
 '51358',
 '51360',
 '51363',
 '51364',
 '51365',
 '51366',
 '51401',
 '51430',
 '51431',
 '51433',
 '51436',
 '51439',
 '51440',
 '51441',
 '51442',
 '51443',
 '51444',
 '51445',
 '51446',
 '51447',
 '51448',
 '51449',
 '51450',
 '51451',
 '51453',
 '51454',
 '51455',
 '51458',
 '51459',
 '51461',
 '51462',
 '51463',
 '51465',
 '51466',
 '51467',
 '51501',
 '51503',
 '51510',
 '51520',
 '51521',
 '51523',
 '51525',
 '51526',
 '51527',
 '51528',
 '51529',
 '51530',
 '51531',
 '51532',
 '51533',
 '51534',
 '51535',
 '51536',
 '51537',
 '51540',
 '51541',
 '51542',
 '51543',
 '51544',
 '51545',
 '51546',
 '51548',
 '51549',
 '51550',
 '51551',
 '51552',
 '51553',
 '51554',
 '51555',
 '51556',
 '51557',
 '51558',
 '51559',
 '51560',
 '51561',
 '51562',
 '51563',
 '51564',
 '51565',
 '51566',
 '51570',
 '51571',
 '51572',
 '51573',
 '51575',
 '51576',
 '51577',
 '51578',
 '51579',
 '51601',
 '51630',
 '51631',
 '51632',
 '51636',
 '51637',
 '51638',
 '51639',
 '51640',
 '51645',
 '51646',
 '51647',
 '51648',
 '51649',
 '51650',
 '51652',
 '51653',
 '51654',
 '51656',
 '52001',
 '52002',
 '52003',
 '52030',
 '52031',
 '52032',
 '52033',
 '52035',
 '52037',
 '52038',
 '52039',
 '52040',
 '52041',
 '52042',
 '52043',
 '52044',
 '52045',
 '52046',
 '52047',
 '52048',
 '52049',
 '52050',
 '52052',
 '52053',
 '52054',
 '52057',
 '52060',
 '52064',
 '52065',
 '52066',
 '52068',
 '52069',
 '52070',
 '52072',
 '52073',
 '52074',
 '52076',
 '52077',
 '52078',
 '52079',
 '52101',
 '52132',
 '52133',
 '52134',
 '52135',
 '52136',
 '52140',
 '52141',
 '52142',
 '52144',
 '52146',
 '52147',
 '52151',
 '52154',
 '52155',
 '52156',
 '52157',
 '52158',
 '52159',
 '52160',
 '52161',
 '52162',
 '52163',
 '52164',
 '52165',
 '52166',
 '52168',
 '52169',
 '52170',
 '52171',
 '52172',
 '52175',
 '52201',
 '52202',
 '52203',
 '52205',
 '52206',
 '52207',
 '52208',
 '52209',
 '52210',
 '52211',
 '52212',
 '52213',
 '52214',
 '52215',
 '52216',
 '52217',
 '52218',
 '52219',
 '52220',
 '52221',
 '52222',
 '52223',
 '52224',
 '52225',
 '52227',
 '52228',
 '52229',
 '52231',
 '52232',
 '52233',
 '52235',
 '52236',
 '52237',
 '52240',
 '52241',
 '52242',
 '52245',
 '52246',
 '52247',
 '52248',
 '52249',
 '52251',
 '52253',
 '52254',
 '52255',
 '52257',
 '52301',
 '52302',
 '52305',
 '52306',
 '52307',
 '52308',
 '52309',
 '52310',
 '52312',
 '52313',
 '52314',
 '52315',
 '52316',
 '52317',
 '52318',
 '52320',
 '52321',
 '52322',
 '52323',
 '52324',
 '52325',
 '52326',
 '52327',
 '52328',
 '52329',
 '52330',
 '52332',
 '52333',
 '52334',
 '52335',
 '52336',
 '52337',
 '52338',
 '52339',
 '52340',
 '52341',
 '52342',
 '52345',
 '52346',
 '52347',
 '52348',
 '52349',
 '52351',
 '52352',
 '52353',
 '52354',
 '52355',
 '52356',
 '52358',
 '52359',
 '52361',
 '52362',
 '52401',
 '52402',
 '52403',
 '52404',
 '52405',
 '52411',
 '52501',
 '52530',
 '52531',
 '52533',
 '52534',
 '52535',
 '52536',
 '52537',
 '52540',
 '52542',
 '52543',
 '52544',
 '52548',
 '52549',
 '52550',
 '52551',
 '52552',
 '52553',
 '52554',
 '52555',
 '52556',
 '52557',
 '52560',
 '52561',
 '52563',
 '52565',
 '52566',
 '52567',
 '52569',
 '52570',
 '52571',
 '52572',
 '52573',
 '52574',
 '52576',
 '52577',
 '52580',
 '52581',
 '52583',
 '52584',
 '52585',
 '52586',
 '52588',
 '52590',
 '52591',
 '52593',
 '52594',
 '52595',
 '52601',
 '52619',
 '52620',
 '52621',
 '52623',
 '52624',
 '52625',
 '52626',
 '52627',
 '52630',
 '52632',
 '52635',
 '52637',
 '52638',
 '52639',
 '52640',
 '52641',
 '52644',
 '52645',
 '52646',
 '52647',
 '52649',
 '52650',
 '52651',
 '52653',
 '52654',
 '52655',
 '52656',
 '52657',
 '52658',
 '52659',
 '52660',
 '52701',
 '52720',
 '52721',
 '52722',
 '52726',
 '52727',
 '52728',
 '52729',
 '52730',
 '52731',
 '52732',
 '52737',
 '52738',
 '52739',
 '52742',
 '52745',
 '52746',
 '52747',
 '52748',
 '52749',
 '52750',
 '52751',
 '52752',
 '52753',
 '52754',
 '52755',
 '52756',
 '52757',
 '52758',
 '52760',
 '52761',
 '52765',
 '52766',
 '52767',
 '52768',
 '52769',
 '52772',
 '52773',
 '52774',
 '52776',
 '52777',
 '52778',
 '52801',
 '52802',
 '52803',
 '52804',
 '52806',
 '52807',
 '56027']

In [35]:
dp03_new.columns = new_cols

In [40]:
dp03_new= dp03_new.set_index('Label').T

In [41]:
dp03_new

Label,OCCUPATION,Civilian employed population 16 years and over,"Management, business, science, and arts occupations",Service occupations,Sales and office occupations,"Natural resources, construction, and maintenance occupations","Production, transportation, and material moving occupations",INCOME AND BENEFITS (IN 2020 INFLATION-ADJUSTED DOLLARS),Total households,"Less than $10,000","$10,000 to $14,999","$15,000 to $24,999","$25,000 to $34,999","$35,000 to $49,999","$50,000 to $74,999","$75,000 to $99,999","$100,000 to $149,999","$150,000 to $199,999","$200,000 or more",Median household income (dollars)
50001,NaN,357,207,24,64,20,42,NaN,266,0,29,3,5,30,44,37,75,21,22,"89,773"
50002,NaN,724,245,77,196,83,123,NaN,595,31,3,39,82,110,78,72,113,18,49,"64,531"
50003,NaN,"4,232","2,073",553,951,429,226,NaN,"3,075",125,72,187,146,269,513,406,691,258,408,"88,875"
50005,NaN,474,59,210,72,22,111,NaN,380,1,0,26,98,49,92,73,39,2,0,"56,250"
50006,NaN,859,268,118,168,153,152,NaN,687,32,22,66,57,129,133,103,114,15,16,"56,528"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52803,NaN,"11,067","4,212","2,051","2,238",940,"1,626",NaN,"8,593",748,420,676,775,"1,218","1,677","1,143","1,170",358,408,"55,010"
52804,NaN,"13,892","3,993","2,916","2,732","1,342","2,909",NaN,"10,782",820,422,"1,053","1,077","1,517","2,535","1,349","1,403",391,215,"52,395"
52806,NaN,"13,154","4,226","2,624","2,712","1,029","2,563",NaN,"10,804",715,495,"1,091",876,"1,730","2,084","1,276","1,810",489,238,"55,929"
52807,NaN,"7,952","3,900",932,"1,945",401,774,NaN,"6,535",234,128,759,534,824,"1,150",737,924,655,590,"65,984"
56027,NaN,325,100,61,40,40,84,NaN,320,8,10,46,38,68,59,22,46,12,11,"44,500"

In [42]:
dp03_new.columns = dp03_new.columns.str.replace(' ','_')

In [43]:
dp03_new

Label,OCCUPATION,Civilian_employed_population_16_years_and_over,"Management,_business,_science,_and_arts_occupations",Service_occupations,Sales_and_office_occupations,"Natural_resources,_construction,_and_maintenance_occupations","Production,_transportation,_and_material_moving_occupations",INCOME_AND_BENEFITS_(IN_2020_INFLATION-ADJUSTED_DOLLARS),Total_households,"Less_than_$10,000","$10,000_to_$14,999","$15,000_to_$24,999","$25,000_to_$34,999","$35,000_to_$49,999","$50,000_to_$74,999","$75,000_to_$99,999","$100,000_to_$149,999","$150,000_to_$199,999","$200,000_or_more",Median_household_income_(dollars)
50001,NaN,357,207,24,64,20,42,NaN,266,0,29,3,5,30,44,37,75,21,22,"89,773"
50002,NaN,724,245,77,196,83,123,NaN,595,31,3,39,82,110,78,72,113,18,49,"64,531"
50003,NaN,"4,232","2,073",553,951,429,226,NaN,"3,075",125,72,187,146,269,513,406,691,258,408,"88,875"
50005,NaN,474,59,210,72,22,111,NaN,380,1,0,26,98,49,92,73,39,2,0,"56,250"
50006,NaN,859,268,118,168,153,152,NaN,687,32,22,66,57,129,133,103,114,15,16,"56,528"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52803,NaN,"11,067","4,212","2,051","2,238",940,"1,626",NaN,"8,593",748,420,676,775,"1,218","1,677","1,143","1,170",358,408,"55,010"
52804,NaN,"13,892","3,993","2,916","2,732","1,342","2,909",NaN,"10,782",820,422,"1,053","1,077","1,517","2,535","1,349","1,403",391,215,"52,395"
52806,NaN,"13,154","4,226","2,624","2,712","1,029","2,563",NaN,"10,804",715,495,"1,091",876,"1,730","2,084","1,276","1,810",489,238,"55,929"
52807,NaN,"7,952","3,900",932,"1,945",401,774,NaN,"6,535",234,128,759,534,824,"1,150",737,924,655,590,"65,984"
56027,NaN,325,100,61,40,40,84,NaN,320,8,10,46,38,68,59,22,46,12,11,"44,500"