In [1]:
import pandas as pd
import numpy as np

In [2]:
dp05_county = pd.read_csv(r'C:\Users\dgarb\OneDrive\Desktop\Capstone Data\census data\ACSDP5Y2020.DP05-2022-03-30T211521 county level.csv')

In [4]:
cols = list(dp05_county.columns)

In [5]:
new_cols = list(filter(lambda col: "Estimate" in col,cols)) 
# new_cols.append('Label (Grouping)')
new_cols = ['Label (Grouping)'] + new_cols

In [9]:
dp05_county_new = dp05_county[new_cols]

In [10]:
pd.set_option('display.max_rows', 95)

dp05_county_new.head(95)

,Label (Grouping),"Adair County, Iowa!!Estimate","Adams County, Iowa!!Estimate","Allamakee County, Iowa!!Estimate","Appanoose County, Iowa!!Estimate","Audubon County, Iowa!!Estimate","Benton County, Iowa!!Estimate","Black Hawk County, Iowa!!Estimate","Boone County, Iowa!!Estimate","Bremer County, Iowa!!Estimate",...,"Wapello County, Iowa!!Estimate","Warren County, Iowa!!Estimate","Washington County, Iowa!!Estimate","Wayne County, Iowa!!Estimate","Webster County, Iowa!!Estimate","Winnebago County, Iowa!!Estimate","Winneshiek County, Iowa!!Estimate","Woodbury County, Iowa!!Estimate","Worth County, Iowa!!Estimate","Wright County, Iowa!!Estimate"
0,SEX AND AGE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Total population,"7,048","3,633","13,761","12,462","5,528","25,558","131,813","26,381","25,032",...,"35,102","50,867","22,100","6,426","36,348","10,474","20,090","102,687","7,422","12,644"
2,Male,"3,510","1,791","6,937","6,090","2,744","12,760","64,715","13,207","12,407",...,"17,473","24,982","10,931","3,133","18,867","5,202","9,960","50,884","3,781","6,297"
3,Female,"3,538","1,842","6,824","6,372","2,784","12,798","67,098","13,174","12,625",...,"17,629","25,885","11,169","3,293","17,481","5,272","10,130","51,803","3,641","6,347"
4,Sex ratio (males per 100 females),99.2,97.2,101.7,95.6,98.6,99.7,96.4,100.3,98.3,...,99.1,96.5,97.9,95.1,107.9,98.7,98.3,98.2,103.8,99.2
5,Under 5 years,402,215,907,671,345,"1,585","8,300","1,454","1,457",...,"2,271","3,056","1,434",471,"2,111",554,893,"7,299",412,817
6,5 to 9 years,464,229,838,809,240,"1,487","7,998","1,609","1,479",...,"2,056","3,605","1,414",445,"2,212",679,959,"7,240",417,775
7,10 to 14 years,388,187,954,836,380,"1,786","7,770","1,539","1,633",...,"2,324","3,662","1,661",450,"2,005",580,"1,112","7,789",411,998
8,15 to 19 years,366,166,728,694,278,"1,683","9,096","1,612","2,059",...,"2,233","3,728","1,437",390,"2,755",860,"1,862","7,397",449,639
9,20 to 24 years,327,186,692,600,273,"1,249","14,879","1,513","1,892",...,"2,204","3,205","1,148",327,"2,715",722,"2,029","6,964",405,628
10,25 to 34 years,826,405,"1,424","1,249",502,"2,621","17,142","3,234","2,578",...,"4,406","5,781","2,458",696,"4,478","1,011","1,867","13,416",812,"1,515"
11,35 to 44 years,738,358,"1,387","1,277",561,"3,074","14,947","3,303","3,088",...,"3,997","6,746","2,739",622,"3,996","1,099","1,925","12,525",882,"1,335"
12,45 to 54 years,818,424,"1,602","1,578",631,"3,510","13,851","3,307","2,807",...,"4,386","6,517","2,665",658,"4,089","1,145","2,253","12,025",948,"1,283"
13,55 to 59 years,474,290,"1,131",849,487,"1,995","7,621","2,019","1,711",...,"2,148","3,349","1,618",559,"2,677",800,"1,473","6,601",619,720
14,60 to 64 years,668,337,987,"1,014",467,"1,871","8,479","2,010","1,386",...,"2,867","3,170","1,329",418,"2,598",807,"1,570","5,979",512,"1,126"
15,65 to 74 years,777,450,"1,718","1,557",666,"2,513","12,355","2,790","2,620",...,"3,425","4,724","2,266",680,"3,744","1,144","2,198","9,058",840,"1,408"
16,75 to 84 years,499,285,857,871,459,"1,470","6,637","1,408","1,619",...,"1,812","2,198","1,174",514,"1,960",769,"1,279","4,596",502,838
17,85 years and over,301,101,536,457,239,714,"2,738",583,703,...,973,"1,126",757,196,"1,008",304,670,"1,798",213,562
18,Median age (years),45.2,47.2,44.2,45.8,48.5,43.1,35.4,42.1,39.2,...,39.6,38.5,40.5,41.8,39.3,41.9,41.9,35.8,43.6,42.3
19,Under 18 years,"1,507",747,"3,182","2,783","1,148","5,971","28,562","5,665","5,611",...,"7,972","12,534","5,470","1,638","7,709","2,281","3,705","26,767","1,520","3,052"
20,16 years and over,"5,697","2,956","10,902","10,011","4,493","20,303","106,241","21,534","20,141",...,"27,988","39,863","17,334","4,982","29,657","8,534","16,912","78,697","6,077","9,891"
21,18 years and over,"5,541","2,886","10,579","9,679","4,380","19,587","103,251","20,716","19,421",...,"27,130","38,333","16,630","4,788","28,639","8,193","16,385","75,920","5,902","9,592"
22,21 years and over,"5,387","2,794","10,244","9,260","4,279","18,817","94,663","19,969","18,000",...,"25,614","35,758","16,036","4,617","26,673","7,633","14,674","71,268","5,648","9,326"
23,62 years and over,"1,964","1,057","3,676","3,451","1,644","5,739","27,266","5,928","5,732",...,"8,048","9,737","4,962","1,636","8,149","2,748","4,934","19,102","1,838","3,507"
24,65 years and over,"1,577",836,"3,111","2,885","1,364","4,697","21,730","4,781","4,942",...,"6,210","8,048","4,197","1,390","6,712","2,217","4,147","15,452","1,555","2,808"
25,18 years and over,"5,541","2,886","10,579","9,679","4,380","19,587","103,251","20,716","19,421",...,"27,130","38,333","16,630","4,788","28,639","8,193","16,385","75,920","5,902","9,592"
26,Male,"2,744","1,413","5,308","4,685","2,106","9,734","50,265","10,257","9,495",...,"13,406","18,522","8,094","2,326","14,962","4,074","8,030","37,352","2,986","4,756"
27,Female,"2,797","1,473","5,271","4,994","2,274","9,853","52,986","10,459","9,926",...,"13,724","19,811","8,536","2,462","13,677","4,119","8,355","38,568","2,916","4,836"
28,Sex ratio (males per 100 females),98.1,95.9,100.7,93.8,92.6,98.8,94.9,98.1,95.7,...,97.7,93.5,94.8,94.5,109.4,98.9,96.1,96.8,102.4,98.3
29,65 years and over,"1,577",836,"3,111","2,885","1,364","4,697","21,730","4,781","4,942",...,"6,210","8,048","4,197","1,390","6,712","2,217","4,147","15,452","1,555","2,808"
30,Male,718,384,"1,472","1,329",598,"2,181","9,721","2,195","2,262",...,"2,768","3,586","1,885",618,"3,032",977,"1,930","6,852",730,"1,279"
31,Female,859,452,"1,639","1,556",766,"2,516","12,009","2,586","2,680",...,"3,442","4,462","2,312",772,"3,680","1,240","2,217","8,600",825,"1,529"
32,Sex ratio (males per 100 females),83.6,85.0,89.8,85.4,78.1,86.7,80.9,84.9,84.4,...,80.4,80.4,81.5,80.1,82.4,78.8,87.1,79.7,88.5,83.6
33,RACE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,Total population,"7,048","3,633","13,761","12,462","5,528","25,558","131,813","26,381","25,032",...,"35,102","50,867","22,100","6,426","36,348","10,474","20,090","102,687","7,422","12,644"
35,One race,"6,931","3,584","13,569","12,227","5,367","25,071","128,012","26,002","24,651",...,"34,033","49,773","21,664","6,248","35,269","10,327","19,936","97,093","7,197","12,242"
36,Two or more races,117,49,192,235,161,487,"3,801",379,381,...,"1,069","1,094",436,178,"1,079",147,154,"5,594",225,402
37,One race,"6,931","3,584","13,569","12,227","5,367","25,071","128,012","26,002","24,651",...,"34,033","49,773","21,664","6,248","35,269","10,327","19,936","97,093","7,197","12,242"
38,White,"6,820","3,515","13,129","12,051","5,343","24,651","109,478","25,259","23,942",...,"30,517","48,594","20,790","6,165","32,516","9,920","19,347","85,615","7,065","11,829"
39,Black or African American,34,4,164,77,2,94,"12,674",299,263,...,"1,298",301,147,12,"1,567",162,183,"3,860",60,19
40,American Indian and Alaska Native,0,8,151,49,0,40,523,133,66,...,86,24,45,31,114,31,67,"1,872",0,2
41,Cherokee tribal grouping,0,8,0,3,0,0,50,8,0,...,0,0,1,11,4,0,0,2,0,0
42,Chippewa tribal grouping,0,0,0,0,0,0,26,5,1,...,0,0,0,0,0,0,0,14,0,0
43,Navajo tribal grouping,0,0,0,0,0,0,28,0,0,...,0,0,0,0,16,0,0,11,0,0
44,Sioux tribal grouping,0,0,25,0,0,15,0,12,65,...,0,0,32,0,19,0,3,320,0,0
45,Asian,55,23,69,35,2,100,"3,558",68,279,...,507,388,97,5,494,132,183,"2,664",31,12
46,Asian Indian,13,0,11,6,0,70,712,0,66,...,38,24,0,0,0,0,0,49,4,0
47,Chinese,4,0,15,0,0,1,263,0,115,...,39,25,46,0,104,9,32,59,0,3
48,Filipino,19,0,25,9,0,4,64,0,25,...,64,64,26,0,60,88,4,141,8,0
49,Japanese,5,14,0,0,0,0,78,0,0,...,6,0,0,0,23,0,12,15,0,0
50,Korean,0,0,18,16,2,8,397,42,21,...,43,68,6,0,152,4,83,117,9,0
51,Vietnamese,0,9,0,4,0,15,72,25,0,...,0,104,0,0,10,24,0,"1,178",10,0
52,Other Asian,14,0,0,0,0,2,"1,972",1,52,...,317,103,19,5,145,7,52,"1,105",0,9
53,Native Hawaiian and Other Pacific ...,0,0,0,0,0,0,367,69,15,...,303,141,6,0,5,0,2,413,2,0
54,Native Hawaiian,0,0,0,0,0,0,90,0,0,...,37,139,3,0,4,0,0,162,0,0
55,Chamorro,0,0,0,0,0,0,37,67,0,...,0,2,0,0,0,0,0,71,0,0
56,Samoan,0,0,0,0,0,0,58,0,0,...,0,0,3,0,0,0,2,0,0,0
57,Other Pacific Islander,0,0,0,0,0,0,182,2,15,...,266,0,0,0,1,0,0,180,2,0
58,Some other race,22,34,56,15,20,186,"1,412",174,86,...,"1,322",325,579,35,573,82,154,"2,669",39,380
59,Two or more races,117,49,192,235,161,487,"3,801",379,381,...,"1,069","1,094",436,178,"1,079",147,154,"5,594",225,402
60,White and Black or African American,9,0,41,81,68,192,"1,560",133,178,...,321,330,163,37,548,86,40,"1,631",109,11
61,White and American Indian and Alas...,65,45,14,68,91,80,313,191,47,...,169,247,64,26,245,2,12,730,16,3
62,White and Asian,7,0,14,84,1,45,426,21,56,...,47,150,101,40,16,11,17,642,35,41
63,Black or African American and Amer...,0,0,0,0,0,1,313,0,13,...,6,0,3,0,16,0,0,132,0,0
64,Race alone or in combination with one or more ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65,Total population,"7,048","3,633","13,761","12,462","5,528","25,558","131,813","26,381","25,032",...,"35,102","50,867","22,100","6,426","36,348","10,474","20,090","102,687","7,422","12,644"
66,White,"6,922","3,564","13,321","12,286","5,504","25,137","112,878","25,632","24,304",...,"31,523","49,682","21,187","6,343","33,557","10,055","19,469","90,902","7,290","12,231"
67,Black or African American,43,4,205,158,70,324,"14,690",453,460,...,"1,640",653,364,49,"2,207",273,251,"5,803",169,30
68,American Indian and Alaska Native,65,55,165,117,91,151,"1,446",339,126,...,294,287,116,57,437,74,79,"2,917",16,5
69,Asian,77,25,83,119,4,152,"4,156",89,335,...,579,560,198,45,536,143,214,"3,478",66,53
70,Native Hawaiian and Other Pacific Isla...,0,0,0,0,1,0,581,69,26,...,337,225,6,0,5,9,24,513,7,0
71,Some other race,58,36,179,17,20,318,"2,162",193,168,...,"1,814",592,684,110,747,96,207,"4,864",99,727
72,HISPANIC OR LATINO AND RACE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
73,Total population,"7,048","3,633","13,761","12,462","5,528","25,558","131,813","26,381","25,032",...,"35,102","50,867","22,100","6,426","36,348","10,474","20,090","102,687","7,422","12,644"
74,Hispanic or Latino (of any race),157,53,945,264,45,394,"5,952",719,407,...,"3,844","1,503","1,432",105,"1,978",520,463,"17,583",226,"1,584"
75,Mexican,101,41,672,162,40,283,"4,273",634,213,...,"2,889","1,158","1,183",72,"1,430",346,317,"14,088",196,"1,223"
76,Puerto Rican,32,0,35,0,5,3,386,31,45,...,92,31,5,26,118,132,27,346,5,84
77,Cuban,0,0,0,3,0,12,7,8,31,...,135,17,2,0,4,0,0,207,0,0
78,Other Hispanic or Latino,24,12,238,99,0,96,"1,286",46,118,...,728,297,242,7,426,42,119,"2,942",25,277
79,Not Hispanic or Latino,"6,891","3,580","12,816","12,198","5,483","25,164","125,861","25,662","24,625",...,"31,258","49,364","20,668","6,321","34,370","9,954","19,627","85,104","7,196","11,060"
80,White alone,"6,717","3,496","12,371","11,828","5,315","24,439","105,929","24,858","23,735",...,"28,586","47,769","19,998","6,096","31,309","9,549","19,072","73,746","6,988","10,865"
81,Black or African American alone,34,4,164,77,2,84,"12,513",299,251,...,"1,222",287,147,12,"1,551",148,183,"3,494",59,19
82,American Indian and Alaska Native ...,0,8,119,49,0,40,368,25,33,...,46,13,38,31,111,29,67,"1,580",0,2
83,Asian alone,39,23,60,35,2,100,"3,548",68,279,...,479,368,97,5,494,132,183,"2,664",31,12
84,Native Hawaiian and Other Pacific ...,0,0,0,0,0,0,334,69,15,...,303,141,6,0,5,0,2,377,2,0
85,Some other race alone,22,0,0,0,4,65,119,0,8,...,8,7,0,0,71,0,19,52,0,91
86,Two or more races,79,49,102,209,160,436,"3,050",343,304,...,614,779,382,177,829,96,101,"3,191",116,71
87,Two races including Some other...,0,2,33,2,0,81,366,0,12,...,21,16,57,74,89,6,0,228,1,16
88,Two races excluding Some other...,79,47,69,207,160,355,"2,684",343,292,...,593,763,325,103,740,90,101,"2,963",115,55
89,Total housing units,"3,709","2,011","7,816","6,639","2,988","11,187","58,187","12,017","10,503",...,"16,080","20,340","9,777","3,200","17,056","5,197","9,008","42,455","3,519","6,499"
90,"CITIZEN, VOTING AGE POPULATION",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
91,"Citizen, 18 and over population","5,471","2,877","10,271","9,642","4,366","19,498","98,620","20,527","19,237",...,"25,723","38,096","16,123","4,757","27,986","8,116","16,123","71,632","5,885","9,299"
92,Male,"2,694","1,412","5,105","4,654","2,106","9,692","47,621","10,181","9,411",...,"12,508","18,441","7,780","2,302","14,591","4,024","7,885","35,143","2,983","4,643"
93,Female,"2,777","1,465","5,166","4,988","2,260","9,806","50,999","10,346","9,826",...,"13,215","19,655","8,343","2,455","13,395","4,092","8,238","36,489","2,902","4,656"

In [12]:
# dp05_new = dp05_new.drop([0])
dp05_county_new = dp05_county_new.drop([0])

In [13]:
dp05_county_new

,Label (Grouping),"Adair County, Iowa!!Estimate","Adams County, Iowa!!Estimate","Allamakee County, Iowa!!Estimate","Appanoose County, Iowa!!Estimate","Audubon County, Iowa!!Estimate","Benton County, Iowa!!Estimate","Black Hawk County, Iowa!!Estimate","Boone County, Iowa!!Estimate","Bremer County, Iowa!!Estimate",...,"Wapello County, Iowa!!Estimate","Warren County, Iowa!!Estimate","Washington County, Iowa!!Estimate","Wayne County, Iowa!!Estimate","Webster County, Iowa!!Estimate","Winnebago County, Iowa!!Estimate","Winneshiek County, Iowa!!Estimate","Woodbury County, Iowa!!Estimate","Worth County, Iowa!!Estimate","Wright County, Iowa!!Estimate"
1,Total population,"7,048","3,633","13,761","12,462","5,528","25,558","131,813","26,381","25,032",...,"35,102","50,867","22,100","6,426","36,348","10,474","20,090","102,687","7,422","12,644"
2,Male,"3,510","1,791","6,937","6,090","2,744","12,760","64,715","13,207","12,407",...,"17,473","24,982","10,931","3,133","18,867","5,202","9,960","50,884","3,781","6,297"
3,Female,"3,538","1,842","6,824","6,372","2,784","12,798","67,098","13,174","12,625",...,"17,629","25,885","11,169","3,293","17,481","5,272","10,130","51,803","3,641","6,347"
4,Sex ratio (males per 100 females),99.2,97.2,101.7,95.6,98.6,99.7,96.4,100.3,98.3,...,99.1,96.5,97.9,95.1,107.9,98.7,98.3,98.2,103.8,99.2
5,Under 5 years,402,215,907,671,345,"1,585","8,300","1,454","1,457",...,"2,271","3,056","1,434",471,"2,111",554,893,"7,299",412,817
6,5 to 9 years,464,229,838,809,240,"1,487","7,998","1,609","1,479",...,"2,056","3,605","1,414",445,"2,212",679,959,"7,240",417,775
7,10 to 14 years,388,187,954,836,380,"1,786","7,770","1,539","1,633",...,"2,324","3,662","1,661",450,"2,005",580,"1,112","7,789",411,998
8,15 to 19 years,366,166,728,694,278,"1,683","9,096","1,612","2,059",...,"2,233","3,728","1,437",390,"2,755",860,"1,862","7,397",449,639
9,20 to 24 years,327,186,692,600,273,"1,249","14,879","1,513","1,892",...,"2,204","3,205","1,148",327,"2,715",722,"2,029","6,964",405,628
10,25 to 34 years,826,405,"1,424","1,249",502,"2,621","17,142","3,234","2,578",...,"4,406","5,781","2,458",696,"4,478","1,011","1,867","13,416",812,"1,515"
11,35 to 44 years,738,358,"1,387","1,277",561,"3,074","14,947","3,303","3,088",...,"3,997","6,746","2,739",622,"3,996","1,099","1,925","12,525",882,"1,335"
12,45 to 54 years,818,424,"1,602","1,578",631,"3,510","13,851","3,307","2,807",...,"4,386","6,517","2,665",658,"4,089","1,145","2,253","12,025",948,"1,283"
13,55 to 59 years,474,290,"1,131",849,487,"1,995","7,621","2,019","1,711",...,"2,148","3,349","1,618",559,"2,677",800,"1,473","6,601",619,720
14,60 to 64 years,668,337,987,"1,014",467,"1,871","8,479","2,010","1,386",...,"2,867","3,170","1,329",418,"2,598",807,"1,570","5,979",512,"1,126"
15,65 to 74 years,777,450,"1,718","1,557",666,"2,513","12,355","2,790","2,620",...,"3,425","4,724","2,266",680,"3,744","1,144","2,198","9,058",840,"1,408"
16,75 to 84 years,499,285,857,871,459,"1,470","6,637","1,408","1,619",...,"1,812","2,198","1,174",514,"1,960",769,"1,279","4,596",502,838
17,85 years and over,301,101,536,457,239,714,"2,738",583,703,...,973,"1,126",757,196,"1,008",304,670,"1,798",213,562
18,Median age (years),45.2,47.2,44.2,45.8,48.5,43.1,35.4,42.1,39.2,...,39.6,38.5,40.5,41.8,39.3,41.9,41.9,35.8,43.6,42.3
19,Under 18 years,"1,507",747,"3,182","2,783","1,148","5,971","28,562","5,665","5,611",...,"7,972","12,534","5,470","1,638","7,709","2,281","3,705","26,767","1,520","3,052"
20,16 years and over,"5,697","2,956","10,902","10,011","4,493","20,303","106,241","21,534","20,141",...,"27,988","39,863","17,334","4,982","29,657","8,534","16,912","78,697","6,077","9,891"
21,18 years and over,"5,541","2,886","10,579","9,679","4,380","19,587","103,251","20,716","19,421",...,"27,130","38,333","16,630","4,788","28,639","8,193","16,385","75,920","5,902","9,592"
22,21 years and over,"5,387","2,794","10,244","9,260","4,279","18,817","94,663","19,969","18,000",...,"25,614","35,758","16,036","4,617","26,673","7,633","14,674","71,268","5,648","9,326"
23,62 years and over,"1,964","1,057","3,676","3,451","1,644","5,739","27,266","5,928","5,732",...,"8,048","9,737","4,962","1,636","8,149","2,748","4,934","19,102","1,838","3,507"
24,65 years and over,"1,577",836,"3,111","2,885","1,364","4,697","21,730","4,781","4,942",...,"6,210","8,048","4,197","1,390","6,712","2,217","4,147","15,452","1,555","2,808"
25,18 years and over,"5,541","2,886","10,579","9,679","4,380","19,587","103,251","20,716","19,421",...,"27,130","38,333","16,630","4,788","28,639","8,193","16,385","75,920","5,902","9,592"
26,Male,"2,744","1,413","5,308","4,685","2,106","9,734","50,265","10,257","9,495",...,"13,406","18,522","8,094","2,326","14,962","4,074","8,030","37,352","2,986","4,756"
27,Female,"2,797","1,473","5,271","4,994","2,274","9,853","52,986","10,459","9,926",...,"13,724","19,811","8,536","2,462","13,677","4,119","8,355","38,568","2,916","4,836"
28,Sex ratio (males per 100 females),98.1,95.9,100.7,93.8,92.6,98.8,94.9,98.1,95.7,...,97.7,93.5,94.8,94.5,109.4,98.9,96.1,96.8,102.4,98.3
29,65 years and over,"1,577",836,"3,111","2,885","1,364","4,697","21,730","4,781","4,942",...,"6,210","8,048","4,197","1,390","6,712","2,217","4,147","15,452","1,555","2,808"
30,Male,718,384,"1,472","1,329",598,"2,181","9,721","2,195","2,262",...,"2,768","3,586","1,885",618,"3,032",977,"1,930","6,852",730,"1,279"
31,Female,859,452,"1,639","1,556",766,"2,516","12,009","2,586","2,680",...,"3,442","4,462","2,312",772,"3,680","1,240","2,217","8,600",825,"1,529"
32,Sex ratio (males per 100 females),83.6,85.0,89.8,85.4,78.1,86.7,80.9,84.9,84.4,...,80.4,80.4,81.5,80.1,82.4,78.8,87.1,79.7,88.5,83.6
33,RACE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,Total population,"7,048","3,633","13,761","12,462","5,528","25,558","131,813","26,381","25,032",...,"35,102","50,867","22,100","6,426","36,348","10,474","20,090","102,687","7,422","12,644"
35,One race,"6,931","3,584","13,569","12,227","5,367","25,071","128,012","26,002","24,651",...,"34,033","49,773","21,664","6,248","35,269","10,327","19,936","97,093","7,197","12,242"
36,Two or more races,117,49,192,235,161,487,"3,801",379,381,...,"1,069","1,094",436,178,"1,079",147,154,"5,594",225,402
37,One race,"6,931","3,584","13,569","12,227","5,367","25,071","128,012","26,002","24,651",...,"34,033","49,773","21,664","6,248","35,269","10,327","19,936","97,093","7,197","12,242"
38,White,"6,820","3,515","13,129","12,051","5,343","24,651","109,478","25,259","23,942",...,"30,517","48,594","20,790","6,165","32,516","9,920","19,347","85,615","7,065","11,829"
39,Black or African American,34,4,164,77,2,94,"12,674",299,263,...,"1,298",301,147,12,"1,567",162,183,"3,860",60,19
40,American Indian and Alaska Native,0,8,151,49,0,40,523,133,66,...,86,24,45,31,114,31,67,"1,872",0,2
41,Cherokee tribal grouping,0,8,0,3,0,0,50,8,0,...,0,0,1,11,4,0,0,2,0,0
42,Chippewa tribal grouping,0,0,0,0,0,0,26,5,1,...,0,0,0,0,0,0,0,14,0,0
43,Navajo tribal grouping,0,0,0,0,0,0,28,0,0,...,0,0,0,0,16,0,0,11,0,0
44,Sioux tribal grouping,0,0,25,0,0,15,0,12,65,...,0,0,32,0,19,0,3,320,0,0
45,Asian,55,23,69,35,2,100,"3,558",68,279,...,507,388,97,5,494,132,183,"2,664",31,12
46,Asian Indian,13,0,11,6,0,70,712,0,66,...,38,24,0,0,0,0,0,49,4,0
47,Chinese,4,0,15,0,0,1,263,0,115,...,39,25,46,0,104,9,32,59,0,3
48,Filipino,19,0,25,9,0,4,64,0,25,...,64,64,26,0,60,88,4,141,8,0
49,Japanese,5,14,0,0,0,0,78,0,0,...,6,0,0,0,23,0,12,15,0,0
50,Korean,0,0,18,16,2,8,397,42,21,...,43,68,6,0,152,4,83,117,9,0
51,Vietnamese,0,9,0,4,0,15,72,25,0,...,0,104,0,0,10,24,0,"1,178",10,0
52,Other Asian,14,0,0,0,0,2,"1,972",1,52,...,317,103,19,5,145,7,52,"1,105",0,9
53,Native Hawaiian and Other Pacific ...,0,0,0,0,0,0,367,69,15,...,303,141,6,0,5,0,2,413,2,0
54,Native Hawaiian,0,0,0,0,0,0,90,0,0,...,37,139,3,0,4,0,0,162,0,0
55,Chamorro,0,0,0,0,0,0,37,67,0,...,0,2,0,0,0,0,0,71,0,0
56,Samoan,0,0,0,0,0,0,58,0,0,...,0,0,3,0,0,0,2,0,0,0
57,Other Pacific Islander,0,0,0,0,0,0,182,2,15,...,266,0,0,0,1,0,0,180,2,0
58,Some other race,22,34,56,15,20,186,"1,412",174,86,...,"1,322",325,579,35,573,82,154,"2,669",39,380
59,Two or more races,117,49,192,235,161,487,"3,801",379,381,...,"1,069","1,094",436,178,"1,079",147,154,"5,594",225,402
60,White and Black or African American,9,0,41,81,68,192,"1,560",133,178,...,321,330,163,37,548,86,40,"1,631",109,11
61,White and American Indian and Alas...,65,45,14,68,91,80,313,191,47,...,169,247,64,26,245,2,12,730,16,3
62,White and Asian,7,0,14,84,1,45,426,21,56,...,47,150,101,40,16,11,17,642,35,41
63,Black or African American and Amer...,0,0,0,0,0,1,313,0,13,...,6,0,3,0,16,0,0,132,0,0
64,Race alone or in combination with one or more ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65,Total population,"7,048","3,633","13,761","12,462","5,528","25,558","131,813","26,381","25,032",...,"35,102","50,867","22,100","6,426","36,348","10,474","20,090","102,687","7,422","12,644"
66,White,"6,922","3,564","13,321","12,286","5,504","25,137","112,878","25,632","24,304",...,"31,523","49,682","21,187","6,343","33,557","10,055","19,469","90,902","7,290","12,231"
67,Black or African American,43,4,205,158,70,324,"14,690",453,460,...,"1,640",653,364,49,"2,207",273,251,"5,803",169,30
68,American Indian and Alaska Native,65,55,165,117,91,151,"1,446",339,126,...,294,287,116,57,437,74,79,"2,917",16,5
69,Asian,77,25,83,119,4,152,"4,156",89,335,...,579,560,198,45,536,143,214,"3,478",66,53
70,Native Hawaiian and Other Pacific Isla...,0,0,0,0,1,0,581,69,26,...,337,225,6,0,5,9,24,513,7,0
71,Some other race,58,36,179,17,20,318,"2,162",193,168,...,"1,814",592,684,110,747,96,207,"4,864",99,727
72,HISPANIC OR LATINO AND RACE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
73,Total population,"7,048","3,633","13,761","12,462","5,528","25,558","131,813","26,381","25,032",...,"35,102","50,867","22,100","6,426","36,348","10,474","20,090","102,687","7,422","12,644"
74,Hispanic or Latino (of any race),157,53,945,264,45,394,"5,952",719,407,...,"3,844","1,503","1,432",105,"1,978",520,463,"17,583",226,"1,584"
75,Mexican,101,41,672,162,40,283,"4,273",634,213,...,"2,889","1,158","1,183",72,"1,430",346,317,"14,088",196,"1,223"
76,Puerto Rican,32,0,35,0,5,3,386,31,45,...,92,31,5,26,118,132,27,346,5,84
77,Cuban,0,0,0,3,0,12,7,8,31,...,135,17,2,0,4,0,0,207,0,0
78,Other Hispanic or Latino,24,12,238,99,0,96,"1,286",46,118,...,728,297,242,7,426,42,119,"2,942",25,277
79,Not Hispanic or Latino,"6,891","3,580","12,816","12,198","5,483","25,164","125,861","25,662","24,625",...,"31,258","49,364","20,668","6,321","34,370","9,954","19,627","85,104","7,196","11,060"
80,White alone,"6,717","3,496","12,371","11,828","5,315","24,439","105,929","24,858","23,735",...,"28,586","47,769","19,998","6,096","31,309","9,549","19,072","73,746","6,988","10,865"
81,Black or African American alone,34,4,164,77,2,84,"12,513",299,251,...,"1,222",287,147,12,"1,551",148,183,"3,494",59,19
82,American Indian and Alaska Native ...,0,8,119,49,0,40,368,25,33,...,46,13,38,31,111,29,67,"1,580",0,2
83,Asian alone,39,23,60,35,2,100,"3,548",68,279,...,479,368,97,5,494,132,183,"2,664",31,12
84,Native Hawaiian and Other Pacific ...,0,0,0,0,0,0,334,69,15,...,303,141,6,0,5,0,2,377,2,0
85,Some other race alone,22,0,0,0,4,65,119,0,8,...,8,7,0,0,71,0,19,52,0,91
86,Two or more races,79,49,102,209,160,436,"3,050",343,304,...,614,779,382,177,829,96,101,"3,191",116,71
87,Two races including Some other...,0,2,33,2,0,81,366,0,12,...,21,16,57,74,89,6,0,228,1,16
88,Two races excluding Some other...,79,47,69,207,160,355,"2,684",343,292,...,593,763,325,103,740,90,101,"2,963",115,55
89,Total housing units,"3,709","2,011","7,816","6,639","2,988","11,187","58,187","12,017","10,503",...,"16,080","20,340","9,777","3,200","17,056","5,197","9,008","42,455","3,519","6,499"
90,"CITIZEN, VOTING AGE POPULATION",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
91,"Citizen, 18 and over population","5,471","2,877","10,271","9,642","4,366","19,498","98,620","20,527","19,237",...,"25,723","38,096","16,123","4,757","27,986","8,116","16,123","71,632","5,885","9,299"
92,Male,"2,694","1,412","5,105","4,654","2,106","9,692","47,621","10,181","9,411",...,"12,508","18,441","7,780","2,302","14,591","4,024","7,885","35,143","2,983","4,643"
93,Female,"2,777","1,465","5,166","4,988","2,260","9,806","50,999","10,346","9,826",...,"13,215","19,655","8,343","2,455","13,395","4,092","8,238","36,489","2,902","4,656"

In [15]:
dp05_county_new = dp05_county_new.drop(range(2,94))

In [16]:
dp05_county_new

,Label (Grouping),"Adair County, Iowa!!Estimate","Adams County, Iowa!!Estimate","Allamakee County, Iowa!!Estimate","Appanoose County, Iowa!!Estimate","Audubon County, Iowa!!Estimate","Benton County, Iowa!!Estimate","Black Hawk County, Iowa!!Estimate","Boone County, Iowa!!Estimate","Bremer County, Iowa!!Estimate",...,"Wapello County, Iowa!!Estimate","Warren County, Iowa!!Estimate","Washington County, Iowa!!Estimate","Wayne County, Iowa!!Estimate","Webster County, Iowa!!Estimate","Winnebago County, Iowa!!Estimate","Winneshiek County, Iowa!!Estimate","Woodbury County, Iowa!!Estimate","Worth County, Iowa!!Estimate","Wright County, Iowa!!Estimate"
1,Total population,"7,048","3,633","13,761","12,462","5,528","25,558","131,813","26,381","25,032",...,"35,102","50,867","22,100","6,426","36,348","10,474","20,090","102,687","7,422","12,644"

In [20]:
# string = 'Adair County, Iowa!!Estimate'
def get_county(string):
    L= string.split(',')
    county = L[0]
    return county

In [21]:
cols = list(dp05_county_new.columns)

In [23]:
# cols

In [24]:
new_cols = ['Label' if 'Label' in col_name   else get_county(col_name) for col_name in cols]

In [25]:
new_cols

['Label',
 'Adair County',
 'Adams County',
 'Allamakee County',
 'Appanoose County',
 'Audubon County',
 'Benton County',
 'Black Hawk County',
 'Boone County',
 'Bremer County',
 'Buchanan County',
 'Buena Vista County',
 'Butler County',
 'Calhoun County',
 'Carroll County',
 'Cass County',
 'Cedar County',
 'Cerro Gordo County',
 'Cherokee County',
 'Chickasaw County',
 'Clarke County',
 'Clay County',
 'Clayton County',
 'Clinton County',
 'Crawford County',
 'Dallas County',
 'Davis County',
 'Decatur County',
 'Delaware County',
 'Des Moines County',
 'Dickinson County',
 'Dubuque County',
 'Emmet County',
 'Fayette County',
 'Floyd County',
 'Franklin County',
 'Fremont County',
 'Greene County',
 'Grundy County',
 'Guthrie County',
 'Hamilton County',
 'Hancock County',
 'Hardin County',
 'Harrison County',
 'Henry County',
 'Howard County',
 'Humboldt County',
 'Ida County',
 'Iowa County',
 'Jackson County',
 'Jasper County',
 'Jefferson County',
 'Johnson County',
 'Jones County',
 'Keokuk County',
 'Kossuth County',
 'Lee County',
 'Linn County',
 'Louisa County',
 'Lucas County',
 'Lyon County',
 'Madison County',
 'Mahaska County',
 'Marion County',
 'Marshall County',
 'Mills County',
 'Mitchell County',
 'Monona County',
 'Monroe County',
 'Montgomery County',
 'Muscatine County',
 "O'Brien County",
 'Osceola County',
 'Page County',
 'Palo Alto County',
 'Plymouth County',
 'Pocahontas County',
 'Polk County',
 'Pottawattamie County',
 'Poweshiek County',
 'Ringgold County',
 'Sac County',
 'Scott County',
 'Shelby County',
 'Sioux County',
 'Story County',
 'Tama County',
 'Taylor County',
 'Union County',
 'Van Buren County',
 'Wapello County',
 'Warren County',
 'Washington County',
 'Wayne County',
 'Webster County',
 'Winnebago County',
 'Winneshiek County',
 'Woodbury County',
 'Worth County',
 'Wright County']

In [26]:
dp05_county_new.columns = new_cols

In [27]:
dp05_county_new

,Label,Adair County,Adams County,Allamakee County,Appanoose County,Audubon County,Benton County,Black Hawk County,Boone County,Bremer County,...,Wapello County,Warren County,Washington County,Wayne County,Webster County,Winnebago County,Winneshiek County,Woodbury County,Worth County,Wright County
1,Total population,"7,048","3,633","13,761","12,462","5,528","25,558","131,813","26,381","25,032",...,"35,102","50,867","22,100","6,426","36,348","10,474","20,090","102,687","7,422","12,644"