In [1]:
from dask import dataframe as dd

In [2]:
from dask import delayed as delayed

In [3]:
import pandas as pd
import numpy as np

In [144]:
from freq_pd import proc_freq

In [148]:
from missing_columns_pd import miss_cols

In [4]:
dict_dtypes ={'Invoice/Item Number':str,
 'Date':str,
 'Store Number':str,
 'Store Name':str,
 'Address':str,
 'City':str,
 'Zip Code':str,
 'Store Location':str,
 'County Number':str,
 'County':str,
 'Category':str,
 'Category Name':str,
 'Vendor Number':str,
 'Vendor Name':str,
 'Item Number':str,
 'Item Description':str,
 'Pack':int,
 'Bottle Volume (ml)':int,
 'State Bottle Cost':float,
 'State Bottle Retail':float,
 'Bottles Sold':int,
 'Sale (Dollars)':float,
 'Volume Sold (Liters)':float,
 'Volume Sold (Gallons)':float}

In [5]:
df_17_22 = dd.read_csv(r'C:\Users\dgarb\OneDrive\Desktop\Capstone Data\liquor_2017_to_2022.csv', dtype= dict_dtypes)

In [203]:
dir(df_17_22)

['Address',
 'Category',
 'City',
 'County',
 'Date',
 'Pack',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_ufunc__',
 '__array_wrap__',
 '__await__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__dask_graph__',
 '__dask_keys__',
 '__dask_layers__',
 '__dask_optimize__',
 '__dask_postcompute__',
 '__dask_postpersist__',
 '__dask_scheduler__',
 '__dask_tokenize__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__iter__',
 '__le__',
 '__len__',
 '__long__',
 '__lt__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__setitem__',
 '__setstate__',
 '__sizeof__',
 '__slots__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__weakref__',
 '__xor__',
 '_accessors',
 '_args',
 '_bind_comparison_method',
 '_bind_operator',
 '_bind_operator_method',
 '_constructor',
 '_contains_index_name',
 '_cum_agg',
 '_describe_1d',
 '_describe_nonnumeric_1d',
 '_describe_numeric',
 '_elemwise',
 '_get_binary_operator',
 '_get_numeric_data',
 '_get_unary_operator',
 '_head',
 '_ipython_key_completions_',
 '_is_column_label_reference',
 '_is_index_level_reference',
 '_is_partition_type',
 '_kurtosis_1d',
 '_kurtosis_numeric',
 '_meta',
 '_meta_nonempty',
 '_name',
 '_partition_type',
 '_partitions',
 '_rebuild',
 '_reduction_agg',
 '_repr_data',
 '_repr_divisions',
 '_repr_html_',
 '_scalarfunc',
 '_select_columns_or_index',
 '_skew_1d',
 '_skew_numeric',
 '_token_prefix',
 '_validate_axis',
 '_validate_chunks',
 '_var_1d',
 '_var_mixed',
 '_var_numeric',
 '_var_timedeltas',
 'abs',
 'add',
 'add_prefix',
 'add_suffix',
 'align',
 'all',
 'any',
 'append',
 'apply',
 'applymap',
 'assign',
 'astype',
 'attrs',
 'axes',
 'bfill',
 'categorize',
 'clear_divisions',
 'clip',
 'clip_lower',
 'clip_upper',
 'columns',
 'combine',
 'combine_first',
 'compute',
 'copy',
 'corr',
 'count',
 'cov',
 'cummax',
 'cummin',
 'cumprod',
 'cumsum',
 'dask',
 'dd_date',
 'dd_date2',
 'describe',
 'diff',
 'div',
 'divide',
 'divisions',
 'dot',
 'drop',
 'drop_duplicates',
 'dropna',
 'dtypes',
 'empty',
 'eq',
 'eval',
 'explode',
 'ffill',
 'fillna',
 'first',
 'floordiv',
 'ge',
 'get_dtype_counts',
 'get_ftype_counts',
 'get_partition',
 'groupby',
 'gt',
 'head',
 'idxmax',
 'idxmin',
 'iloc',
 'index',
 'info',
 'isin',
 'isna',
 'isnull',
 'items',
 'iterrows',
 'itertuples',
 'join',
 'known_divisions',
 'kurtosis',
 'last',
 'le',
 'loc',
 'lt',
 'map_overlap',
 'map_partitions',
 'mask',
 'max',
 'mean',
 'melt',
 'memory_usage',
 'memory_usage_per_partition',
 'merge',
 'min',
 'mod',
 'mode',
 'mul',
 'ndim',
 'ne',
 'nlargest',
 'notnull',
 'npartitions',
 'nsmallest',
 'nunique_approx',
 'partitions',
 'persist',
 'pipe',
 'pivot_table',
 'pop',
 'pow',
 'prod',
 'product',
 'quantile',
 'query',
 'radd',
 'random_split',
 'rdiv',
 'reduction',
 'rename',
 'repartition',
 'replace',
 'resample',
 'reset_index',
 'rfloordiv',
 'rmod',
 'rmul',
 'rolling',
 'round',
 'rpow',
 'rsub',
 'rtruediv',
 'sample',
 'select_dtypes',
 'sem',
 'set_index',
 'shape',
 'shift',
 'shuffle',
 'size',
 'skew',
 'sort_values',
 'squeeze',
 'std',
 'sub',
 'sum',
 'tail',
 'to_bag',
 'to_csv',
 'to_dask_array',
 'to_delayed',
 'to_hdf',
 'to_html',
 'to_json',
 'to_orc',
 'to_parquet',
 'to_records',
 'to_sql',
 'to_string',
 'to_timestamp',
 'truediv',
 'values',
 'var',
 'visualize',
 'where',
 'year']

In [15]:
pd.set_option('display.max_columns', None)
df_17_22.head()

,Invoice/Item Number,Date,Store Number,Store Name,Address,City,Zip Code,Store Location,County Number,County,Category,Category Name,Vendor Number,Vendor Name,Item Number,Item Description,Pack,Bottle Volume (ml),State Bottle Cost,State Bottle Retail,Bottles Sold,Sale (Dollars),Volume Sold (Liters),Volume Sold (Gallons),dd_date,volume
0,INV-16608300016,12/28/2018,4932,B and B West,3105 Hudson Rd,Cedar Falls,50613,POINT (-92.465838 42.509248),7,BLACK HAWK,1031100,American Vodkas,300,McCormick Distilling Co.,36908,Mccormick Vodka Pet,6,1750,7.47,11.21,6,67.26,10.5,2.77,2018-12-28,1.750
1,INV-16607200030,12/28/2018,5656,Cody Mart Gas & Liquor,1220 N Cody Rd,Le Claire,52753,POINT (-90.34429 41.611036),82,SCOTT,1081600,Whiskey Liqueur,421,SAZERAC COMPANY INC,86881,Southern Comfort Mini,10,600,5.65,8.48,10,84.80,6.0,1.58,2018-12-28,0.600
2,INV-16607600007,12/28/2018,2106,Hillstreet News and Tobacco,2217 College,Cedar Falls,50613,POINT (-92.455796 42.517182),7,BLACK HAWK,1032100,Imported Vodkas,035,BACARDI USA INC,34433,Grey Goose,12,750,18.49,27.74,12,332.88,9.0,2.37,2018-12-28,0.750
3,INV-16607800025,12/28/2018,5155,New Star / Ansborough Ave,"1459, Ansborough Ave",Waterloo,50701,POINT (-92.376863 42.493091),7,BLACK HAWK,1031100,American Vodkas,300,McCormick Distilling Co.,36904,Mccormick Vodka Pet,24,375,1.80,2.70,24,64.80,9.0,2.37,2018-12-28,0.375
4,INV-16607100031,12/28/2018,3540,Super Target T-0533 / Davenport,5225 Elmore Ave,Davenport,52807,POINT (-90.528585 41.573196),82,SCOTT,1701100,Temporary & Specialty Packages,420,MOET HENNESSY USA,1258,Glenmorangie Taster Pack,6,100,14.99,22.49,6,134.94,0.6,0.15,2018-12-28,0.100

create year

In [36]:
def get_year(date):
    return int(date[-4:])

In [62]:

year = df_17_22['Date'].apply(get_year, meta= int).compute().reset_index()

In [63]:
year[year.index.duplicated(keep = False)].sort_index()

Empty DataFrame
Columns: [index, 0]
Index: []

In [64]:
year.index.unique()

RangeIndex(start=0, stop=12638094, step=1)

merge year with DataFrame df_17_22



combine_dd = dd.merge(df_17_22,year, left_index=True, right_index=True)

In [70]:
pd.set_option('display.max_columns', None)
combine_dd .head()

,Invoice/Item Number,Date,Store Number,Store Name,Address,City,Zip Code,Store Location,County Number,County,Category,Category Name,Vendor Number,Vendor Name,Item Number,Item Description,Pack,Bottle Volume (ml),State Bottle Cost,State Bottle Retail,Bottles Sold,Sale (Dollars),Volume Sold (Liters),Volume Sold (Gallons),dd_date,year,index,0
0,INV-16608300016,12/28/2018,4932,B and B West,3105 Hudson Rd,Cedar Falls,50613,POINT (-92.465838 42.509248),7,BLACK HAWK,1031100,American Vodkas,300,McCormick Distilling Co.,36908,Mccormick Vodka Pet,6,1750,7.47,11.21,6,67.26,10.5,2.77,2018-12-28,2018,0,2018
1,INV-16607200030,12/28/2018,5656,Cody Mart Gas & Liquor,1220 N Cody Rd,Le Claire,52753,POINT (-90.34429 41.611036),82,SCOTT,1081600,Whiskey Liqueur,421,SAZERAC COMPANY INC,86881,Southern Comfort Mini,10,600,5.65,8.48,10,84.80,6.0,1.58,2018-12-28,2018,1,2018
2,INV-16607600007,12/28/2018,2106,Hillstreet News and Tobacco,2217 College,Cedar Falls,50613,POINT (-92.455796 42.517182),7,BLACK HAWK,1032100,Imported Vodkas,035,BACARDI USA INC,34433,Grey Goose,12,750,18.49,27.74,12,332.88,9.0,2.37,2018-12-28,2018,2,2018
3,INV-16607800025,12/28/2018,5155,New Star / Ansborough Ave,"1459, Ansborough Ave",Waterloo,50701,POINT (-92.376863 42.493091),7,BLACK HAWK,1031100,American Vodkas,300,McCormick Distilling Co.,36904,Mccormick Vodka Pet,24,375,1.80,2.70,24,64.80,9.0,2.37,2018-12-28,2018,3,2018
4,INV-16607100031,12/28/2018,3540,Super Target T-0533 / Davenport,5225 Elmore Ave,Davenport,52807,POINT (-90.528585 41.573196),82,SCOTT,1701100,Temporary & Specialty Packages,420,MOET HENNESSY USA,1258,Glenmorangie Taster Pack,6,100,14.99,22.49,6,134.94,0.6,0.15,2018-12-28,2018,4,2018

determine columns with missing values

In [130]:
from dask.diagnostics import ProgressBar
ProgressBar().register()

In [134]:
missing_values = df_17_22.isnull().sum()

with ProgressBar():
    percent_missing = ((missing_values / df_17_22.index.size) * 100).compute()
percent_missing

[########################################] | 100% Completed |  1min 28.7s
[########################################] | 100% Completed |  1min 28.7s

Invoice/Item Number       0.000000
Date                      0.000000
Store Number              0.000000
Store Name                0.000000
Address                   0.398201
City                      0.398193
Zip Code                  0.398193
Store Location           10.216912
County Number             0.398209
County                    0.398193
Category                  0.069243
Category Name             0.069243
Vendor Number             0.000055
Vendor Name               0.000055
Item Number               0.000000
Item Description          0.000000
Pack                      0.000000
Bottle Volume (ml)        0.000000
State Bottle Cost         0.000000
State Bottle Retail       0.000000
Bottles Sold              0.000000
Sale (Dollars)            0.000000
Volume Sold (Liters)      0.000000
Volume Sold (Gallons)     0.000000
dd_date                   0.000000
year                      0.000000
dd_date2                  0.000000
dtype: float64

In [114]:
print('the length of df_17_22 is: ', len(df_17_22))

the length of df_17_22 is:  12638094

In [59]:
dir(df_17_22.index)

['__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_ufunc__',
 '__array_wrap__',
 '__await__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__dask_graph__',
 '__dask_keys__',
 '__dask_layers__',
 '__dask_optimize__',
 '__dask_postcompute__',
 '__dask_postpersist__',
 '__dask_scheduler__',
 '__dask_tokenize__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__iter__',
 '__le__',
 '__len__',
 '__long__',
 '__lt__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__slots__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__weakref__',
 '__xor__',
 '_accessors',
 '_args',
 '_bind_comparison_method',
 '_bind_operator',
 '_bind_operator_method',
 '_cat_attributes',
 '_constructor',
 '_contains_index_name',
 '_cum_agg',
 '_describe_1d',
 '_describe_nonnumeric_1d',
 '_describe_numeric',
 '_dt_attributes',
 '_elemwise',
 '_get_binary_operator',
 '_get_numeric_data',
 '_get_unary_operator',
 '_head',
 '_is_index_level_reference',
 '_is_partition_type',
 '_kurtosis_1d',
 '_kurtosis_numeric',
 '_meta',
 '_meta_nonempty',
 '_name',
 '_partition_type',
 '_partitions',
 '_rebuild',
 '_reduction_agg',
 '_repartition_quantiles',
 '_repr_data',
 '_repr_divisions',
 '_scalarfunc',
 '_skew_1d',
 '_skew_numeric',
 '_token_prefix',
 '_validate_axis',
 '_validate_chunks',
 '_var_1d',
 '_var_mixed',
 '_var_numeric',
 '_var_timedeltas',
 'abs',
 'add',
 'add_prefix',
 'add_suffix',
 'align',
 'all',
 'any',
 'append',
 'apply',
 'astype',
 'attrs',
 'autocorr',
 'axes',
 'between',
 'bfill',
 'clear_divisions',
 'clip',
 'clip_lower',
 'clip_upper',
 'combine',
 'combine_first',
 'compute',
 'copy',
 'corr',
 'count',
 'cov',
 'cummax',
 'cummin',
 'cumprod',
 'cumsum',
 'dask',
 'day',
 'dayofweek',
 'dayofyear',
 'describe',
 'diff',
 'div',
 'divide',
 'divisions',
 'dot',
 'drop_duplicates',
 'dropna',
 'dt',
 'dtype',
 'eq',
 'explode',
 'ffill',
 'fillna',
 'first',
 'floordiv',
 'ge',
 'get_partition',
 'groupby',
 'gt',
 'head',
 'hour',
 'idxmax',
 'idxmin',
 'index',
 'isin',
 'isna',
 'isnull',
 'iteritems',
 'known_divisions',
 'kurtosis',
 'last',
 'le',
 'loc',
 'lt',
 'map',
 'map_overlap',
 'map_partitions',
 'mask',
 'max',
 'mean',
 'memory_usage',
 'memory_usage_per_partition',
 'microsecond',
 'millisecond',
 'min',
 'minute',
 'mod',
 'mode',
 'month',
 'mul',
 'name',
 'nanosecond',
 'nbytes',
 'ndim',
 'ne',
 'nlargest',
 'notnull',
 'npartitions',
 'nsmallest',
 'nunique',
 'nunique_approx',
 'partitions',
 'persist',
 'pipe',
 'pow',
 'prod',
 'product',
 'quantile',
 'quarter',
 'radd',
 'random_split',
 'rdiv',
 'reduction',
 'rename',
 'repartition',
 'replace',
 'resample',
 'reset_index',
 'rfloordiv',
 'rmod',
 'rmul',
 'rolling',
 'round',
 'rpow',
 'rsub',
 'rtruediv',
 'sample',
 'second',
 'sem',
 'shape',
 'shift',
 'shuffle',
 'size',
 'skew',
 'squeeze',
 'std',
 'sub',
 'sum',
 'tail',
 'to_bag',
 'to_csv',
 'to_dask_array',
 'to_delayed',
 'to_frame',
 'to_hdf',
 'to_json',
 'to_series',
 'to_sql',
 'to_string',
 'to_timestamp',
 'truediv',
 'unique',
 'value_counts',
 'values',
 'var',
 'visualize',
 'week',
 'weekday',
 'weekofyear',
 'where',
 'year']

In [77]:
combine_dd['dd_date2'] = dd.to_datetime(combine_dd['Date'])

In [218]:
combine_dd.compute().to_csv(r'C:\Users\dgarb\OneDrive\Desktop\Capstone Data\combine_dd.csv')

[########################################] | 100% Completed |  1min 35.1s

In [221]:
dict_dtypes ={'Invoice/Item Number':str,
 'Date':str,
 'Store Number':str,
 'Store Name':str,
 'Address':str,
 'City':str,
 'Zip Code':str,
 'Store Location':str,
 'County Number':str,
 'County':str,
 'Category':str,
 'Category Name':str,
 'Vendor Number':str,
 'Vendor Name':str,
 'Item Number':str,
 'Item Description':str,
 'Pack':int,
 'Bottle Volume (ml)':int,
 'State Bottle Cost':float,
 'State Bottle Retail':float,
 'Bottles Sold':int,
 'Sale (Dollars)':float,
 'Volume Sold (Liters)':float,
 'Volume Sold (Gallons)':float,
 'year':int,
 'dd_date':str,
 'dd_date2':str           }

In [228]:
combine_dd = dd.read_csv(r'C:\Users\dgarb\OneDrive\Desktop\Capstone Data\combine_dd.csv', dtype=dict_dtypes)

In [225]:
combine_dd.head()

[########################################] | 100% Completed |  1.9s

,Unnamed: 0,Invoice/Item Number,Date,Store Number,Store Name,Address,City,Zip Code,Store Location,County Number,County,Category,Category Name,Vendor Number,Vendor Name,Item Number,Item Description,Pack,Bottle Volume (ml),State Bottle Cost,State Bottle Retail,Bottles Sold,Sale (Dollars),Volume Sold (Liters),Volume Sold (Gallons),dd_date,year,index,0,dd_date2
0,0,INV-16608300016,12/28/2018,4932,B and B West,3105 Hudson Rd,Cedar Falls,50613,POINT (-92.465838 42.509248),7,BLACK HAWK,1031100,American Vodkas,300,McCormick Distilling Co.,36908,Mccormick Vodka Pet,6,1750,7.47,11.21,6,67.26,10.5,2.77,2018-12-28,2018,0,2018,2018-12-28
1,1,INV-16607200030,12/28/2018,5656,Cody Mart Gas & Liquor,1220 N Cody Rd,Le Claire,52753,POINT (-90.34429 41.611036),82,SCOTT,1081600,Whiskey Liqueur,421,SAZERAC COMPANY INC,86881,Southern Comfort Mini,10,600,5.65,8.48,10,84.80,6.0,1.58,2018-12-28,2018,1,2018,2018-12-28
2,2,INV-16607600007,12/28/2018,2106,Hillstreet News and Tobacco,2217 College,Cedar Falls,50613,POINT (-92.455796 42.517182),7,BLACK HAWK,1032100,Imported Vodkas,035,BACARDI USA INC,34433,Grey Goose,12,750,18.49,27.74,12,332.88,9.0,2.37,2018-12-28,2018,2,2018,2018-12-28
3,3,INV-16607800025,12/28/2018,5155,New Star / Ansborough Ave,"1459, Ansborough Ave",Waterloo,50701,POINT (-92.376863 42.493091),7,BLACK HAWK,1031100,American Vodkas,300,McCormick Distilling Co.,36904,Mccormick Vodka Pet,24,375,1.80,2.70,24,64.80,9.0,2.37,2018-12-28,2018,3,2018,2018-12-28
4,4,INV-16607100031,12/28/2018,3540,Super Target T-0533 / Davenport,5225 Elmore Ave,Davenport,52807,POINT (-90.528585 41.573196),82,SCOTT,1701100,Temporary & Specialty Packages,420,MOET HENNESSY USA,1258,Glenmorangie Taster Pack,6,100,14.99,22.49,6,134.94,0.6,0.15,2018-12-28,2018,4,2018,2018-12-28

In [231]:
combine_dd = combine_dd.drop(['Unnamed: 0','index','dd_date','0' ], axis = 1)

In [232]:
combine_dd.head()

[########################################] | 100% Completed |  1.9s

,Invoice/Item Number,Date,Store Number,Store Name,Address,City,Zip Code,Store Location,County Number,County,Category,Category Name,Vendor Number,Vendor Name,Item Number,Item Description,Pack,Bottle Volume (ml),State Bottle Cost,State Bottle Retail,Bottles Sold,Sale (Dollars),Volume Sold (Liters),Volume Sold (Gallons),year,dd_date2
0,INV-16608300016,12/28/2018,4932,B and B West,3105 Hudson Rd,Cedar Falls,50613,POINT (-92.465838 42.509248),7,BLACK HAWK,1031100,American Vodkas,300,McCormick Distilling Co.,36908,Mccormick Vodka Pet,6,1750,7.47,11.21,6,67.26,10.5,2.77,2018,2018-12-28
1,INV-16607200030,12/28/2018,5656,Cody Mart Gas & Liquor,1220 N Cody Rd,Le Claire,52753,POINT (-90.34429 41.611036),82,SCOTT,1081600,Whiskey Liqueur,421,SAZERAC COMPANY INC,86881,Southern Comfort Mini,10,600,5.65,8.48,10,84.80,6.0,1.58,2018,2018-12-28
2,INV-16607600007,12/28/2018,2106,Hillstreet News and Tobacco,2217 College,Cedar Falls,50613,POINT (-92.455796 42.517182),7,BLACK HAWK,1032100,Imported Vodkas,035,BACARDI USA INC,34433,Grey Goose,12,750,18.49,27.74,12,332.88,9.0,2.37,2018,2018-12-28
3,INV-16607800025,12/28/2018,5155,New Star / Ansborough Ave,"1459, Ansborough Ave",Waterloo,50701,POINT (-92.376863 42.493091),7,BLACK HAWK,1031100,American Vodkas,300,McCormick Distilling Co.,36904,Mccormick Vodka Pet,24,375,1.80,2.70,24,64.80,9.0,2.37,2018,2018-12-28
4,INV-16607100031,12/28/2018,3540,Super Target T-0533 / Davenport,5225 Elmore Ave,Davenport,52807,POINT (-90.528585 41.573196),82,SCOTT,1701100,Temporary & Specialty Packages,420,MOET HENNESSY USA,1258,Glenmorangie Taster Pack,6,100,14.99,22.49,6,134.94,0.6,0.15,2018,2018-12-28

 master dataframe called transactions, which records the vendor number, store number, product (item number),
 transaction date, bottles sold, volume (either in gallons or in liters), sales amount.

In [234]:
df_transactions = combine_dd[['Vendor Number', 'Store Number','Item Number', 'Date','dd_date2','year', 'Volume Sold (Liters)', 'Bottles Sold','Sale (Dollars)','State Bottle Cost','State Bottle Retail']]

In [115]:
print('the length of df_transactions is: ', len(df_transactions))

the length of df_transactions is:  12638094

In [235]:
df_transactions.compute().to_csv(r'C:\Users\dgarb\OneDrive\Desktop\Capstone Data\df_transactions.csv')

[########################################] | 100% Completed |  1min 10.3s

In [215]:
print('the length of two_year_trans is: ', len(two_year_trans))

[########################################] | 100% Completed |  1min 38.2s
the length of two_year_trans is:  0

In [72]:
dir(df_17_22)

['Address',
 'Category',
 'City',
 'County',
 'Date',
 'Pack',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_ufunc__',
 '__array_wrap__',
 '__await__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__dask_graph__',
 '__dask_keys__',
 '__dask_layers__',
 '__dask_optimize__',
 '__dask_postcompute__',
 '__dask_postpersist__',
 '__dask_scheduler__',
 '__dask_tokenize__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__iter__',
 '__le__',
 '__len__',
 '__long__',
 '__lt__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__setitem__',
 '__setstate__',
 '__sizeof__',
 '__slots__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__weakref__',
 '__xor__',
 '_accessors',
 '_args',
 '_bind_comparison_method',
 '_bind_operator',
 '_bind_operator_method',
 '_constructor',
 '_contains_index_name',
 '_cum_agg',
 '_describe_1d',
 '_describe_nonnumeric_1d',
 '_describe_numeric',
 '_elemwise',
 '_get_binary_operator',
 '_get_numeric_data',
 '_get_unary_operator',
 '_head',
 '_ipython_key_completions_',
 '_is_column_label_reference',
 '_is_index_level_reference',
 '_is_partition_type',
 '_kurtosis_1d',
 '_kurtosis_numeric',
 '_meta',
 '_meta_nonempty',
 '_name',
 '_partition_type',
 '_partitions',
 '_rebuild',
 '_reduction_agg',
 '_repr_data',
 '_repr_divisions',
 '_repr_html_',
 '_scalarfunc',
 '_select_columns_or_index',
 '_skew_1d',
 '_skew_numeric',
 '_token_prefix',
 '_validate_axis',
 '_validate_chunks',
 '_var_1d',
 '_var_mixed',
 '_var_numeric',
 '_var_timedeltas',
 'abs',
 'add',
 'add_prefix',
 'add_suffix',
 'align',
 'all',
 'any',
 'append',
 'apply',
 'applymap',
 'assign',
 'astype',
 'attrs',
 'axes',
 'bfill',
 'categorize',
 'clear_divisions',
 'clip',
 'clip_lower',
 'clip_upper',
 'columns',
 'combine',
 'combine_first',
 'compute',
 'copy',
 'corr',
 'count',
 'cov',
 'cummax',
 'cummin',
 'cumprod',
 'cumsum',
 'dask',
 'dd_date',
 'describe',
 'diff',
 'div',
 'divide',
 'divisions',
 'dot',
 'drop',
 'drop_duplicates',
 'dropna',
 'dtypes',
 'empty',
 'eq',
 'eval',
 'explode',
 'ffill',
 'fillna',
 'first',
 'floordiv',
 'ge',
 'get_dtype_counts',
 'get_ftype_counts',
 'get_partition',
 'groupby',
 'gt',
 'head',
 'idxmax',
 'idxmin',
 'iloc',
 'index',
 'info',
 'isin',
 'isna',
 'isnull',
 'items',
 'iterrows',
 'itertuples',
 'join',
 'known_divisions',
 'kurtosis',
 'last',
 'le',
 'loc',
 'lt',
 'map_overlap',
 'map_partitions',
 'mask',
 'max',
 'mean',
 'melt',
 'memory_usage',
 'memory_usage_per_partition',
 'merge',
 'min',
 'mod',
 'mode',
 'mul',
 'ndim',
 'ne',
 'nlargest',
 'notnull',
 'npartitions',
 'nsmallest',
 'nunique_approx',
 'partitions',
 'persist',
 'pipe',
 'pivot_table',
 'pop',
 'pow',
 'prod',
 'product',
 'quantile',
 'query',
 'radd',
 'random_split',
 'rdiv',
 'reduction',
 'rename',
 'repartition',
 'replace',
 'resample',
 'reset_index',
 'rfloordiv',
 'rmod',
 'rmul',
 'rolling',
 'round',
 'rpow',
 'rsub',
 'rtruediv',
 'sample',
 'select_dtypes',
 'sem',
 'set_index',
 'shape',
 'shift',
 'shuffle',
 'size',
 'skew',
 'sort_values',
 'squeeze',
 'std',
 'sub',
 'sum',
 'tail',
 'to_bag',
 'to_csv',
 'to_dask_array',
 'to_delayed',
 'to_hdf',
 'to_html',
 'to_json',
 'to_orc',
 'to_parquet',
 'to_records',
 'to_sql',
 'to_string',
 'to_timestamp',
 'truediv',
 'values',
 'var',
 'visualize',
 'where',
 'year']

create products file -  keep most recent item number so get most recent description

In [92]:
df_prod1 = combine_dd.sort_values(by=['dd_date2']).drop_duplicates(['Item Number'],keep='last')

In [93]:
df_prod1.shape[0]

Delayed('int-e534129c-00b2-4be2-8323-65197c4eb56c')

In [94]:
df_products = df_prod1[['Item Number', 'Item Description', 'Date', 'dd_date2', 'year', 'Category']]

In [116]:
print('the length of df_products is: ', len(df_products))

the length of df_products is:  7766

write df_products to csv

In [101]:
df_products.compute().to_csv(r'C:\Users\dgarb\OneDrive\Desktop\Capstone Data\df_products.csv')

In [200]:
pd_df_products = pd.read_csv(r'C:\Users\dgarb\OneDrive\Desktop\Capstone Data\df_products.csv')

In [201]:
pd_df_products.shape

(7766, 7)

In [95]:
type(df_prod1)
df_prod1.head()

,Invoice/Item Number,Date,Store Number,Store Name,Address,City,Zip Code,Store Location,County Number,County,Category,Category Name,Vendor Number,Vendor Name,Item Number,Item Description,Pack,Bottle Volume (ml),State Bottle Cost,State Bottle Retail,Bottles Sold,Sale (Dollars),Volume Sold (Liters),Volume Sold (Gallons),dd_date,year,index,0,dd_date2
68666,INV-02503200001,01/03/2017,2590,Hy-Vee Food Store #5 / Cedar Rapids,3235 Oakland Road NE,Cedar Rapids,52402,POINT (-91.658105 42.010971),57,LINN,NaN,NaN,305,Mhw LTD,965015,Galliano L'Autentico,12,750,19.05,28.58,12,342.96,9.00,2.38,2017-01-03,2017,68666,2018,2017-01-03
92800,INV-02542600017,01/04/2017,4025,Karam Kaur Khasriya Llc,702 13th St,Belle Plaine,52208,POINT (-92.277759 41.897052),6,BENTON,NaN,NaN,212,Shand Import LLC,28638,Indian Summer,6,750,15.85,23.78,1,23.78,0.75,0.20,2017-01-04,2017,92800,2018,2017-01-04
105163,INV-02540000018,01/04/2017,5351,Downtown Liquor,1203 5th St.,Sioux City,51101,POINT (-96.394671 42.495324),97,WOODBURY,NaN,NaN,313,Vision Wine & Spirit LLC,28656,Master's Gin,6,750,17.17,25.76,1,25.76,0.75,0.20,2017-01-04,2017,105163,2018,2017-01-04
75823,INV-02529800017,01/04/2017,5237,World Liquor & Tobacco + Vape,"606, N 15th St",Fort Dodge,50501,POINT (-94.17795 42.512182),48,Iowa,NaN,NaN,420,MOET HENNESSY USA,48182,Hennessy Master Blender's Selection,12,375,22.49,33.74,1,33.74,0.38,0.10,2017-01-04,2017,75823,2018,2017-01-04
109092,INV-02563100315,01/05/2017,2587,Hy-Vee Food Store / Johnston,5750 Merle Hay Road,Johnston,50131,POINT (-93.697731 41.665172),77,POLK,NaN,NaN,085,Brown Forman Corp.,64674,Chambord Liqueur Royale De France,12,375,11.41,17.12,1,17.12,0.38,0.10,2017-01-05,2017,109092,2018,2017-01-05

In [96]:
df_prod1.tail(5)

,Invoice/Item Number,Date,Store Number,Store Name,Address,City,Zip Code,Store Location,County Number,County,Category,Category Name,Vendor Number,Vendor Name,Item Number,Item Description,Pack,Bottle Volume (ml),State Bottle Cost,State Bottle Retail,Bottles Sold,Sale (Dollars),Volume Sold (Liters),Volume Sold (Gallons),dd_date,year,index,0,dd_date2
178509,INV-45119300012,02/28/2022,5692,Locust Mart / Davenport,11423 160th St,Davenport,52804,POINT (-90.680408 41.538169),82,SCOTT,1031100,American Vodkas,421,SAZERAC COMPANY INC,38088,Platinum 7x Vodka,6,1750,9.44,14.16,6,84.96,10.50,2.77,2022-02-28,2022,178509,2018,2022-02-28
178506,INV-45125600135,02/28/2022,2552,Hy-Vee Food Store #3 / Cedar Rapids,20 Wilson Avenue West,Cedar Rapids,52404,POINT (-91.658576 41.955859),57,LINN,1032200,Imported Flavored Vodka,115,CONSTELLATION BRANDS INC,36576,Svedka Blue Raspberry,12,750,8.00,12.00,4,48.00,3.00,0.79,2022-02-28,2022,178506,2018,2022-02-28
178505,INV-45118700012,02/28/2022,2625,Hy-Vee Wine & Spirits #2 / Davenport,3301 W Kimberly Rd,Davenport,52804,NaN,82,SCOTT,1031200,American Flavored Vodka,260,DIAGEO AMERICAS,77647,Smirnoff Citrus,12,750,8.25,12.38,12,148.56,9.00,2.37,2022-02-28,2022,178505,2018,2022-02-28
186294,INV-45151400008,02/28/2022,6000,Porters Convenience 66 / Clinton,1512 Lincoln Way,Clinton,52732,POINT (-90.221831 41.817449),23,CLINTON,1051100,American Brandies,205,E & J Gallo Winery,52594,E & J VS,24,375,3.50,5.25,3,15.75,1.12,0.29,2022-02-28,2022,186294,2018,2022-02-28
186715,INV-45149700011,02/28/2022,4562,Casey's General Store #2989 / Mechanicsville,206 Short St,Mechanicsville,52306,NaN,16,CEDAR,1012100,Canadian Whiskies,259,Heaven Hill Brands,10550,Black Velvet Toasted Caramel,12,750,5.23,7.85,12,94.20,9.00,2.37,2022-02-28,2022,186715,2018,2022-02-28

create stores file

In [97]:
df_store1 = combine_dd.sort_values(by=['dd_date2']).drop_duplicates(['Store Number'],keep='last')

In [98]:
df_store1.head()

,Invoice/Item Number,Date,Store Number,Store Name,Address,City,Zip Code,Store Location,County Number,County,Category,Category Name,Vendor Number,Vendor Name,Item Number,Item Description,Pack,Bottle Volume (ml),State Bottle Cost,State Bottle Retail,Bottles Sold,Sale (Dollars),Volume Sold (Liters),Volume Sold (Gallons),dd_date,year,index,0,dd_date2
147629,INV-02642100005,01/10/2017,4176,Todds On The Go,235 Edgewood Rd NE,Cedar Rapids,52405,NaN,57,LINN,1051100,American Brandies,205,E & J Gallo Winery,52591,E & J Vs Brandy Mini,10,500,7.68,11.52,1,9.60,0.50,0.13,2017-01-10,2017,147629,2018,2017-01-10
134077,INV-02715900009,01/16/2017,5121,Liquor Beer & Tobacco Outlet / Char,"1908, Clark St",Charles City,50616,POINT (-92.661881 43.05913400000001),34,FLOYD,1031100,American Vodkas,205,E & J Gallo Winery,36968,New Amsterdam Vodka,24,375,3.50,5.25,24,126.00,9.00,2.38,2017-01-16,2017,134077,2018,2017-01-16
150456,INV-02719600017,01/16/2017,5019,Riverside Quick Shop,"802, S Riverview",Bellevue,52031,POINT (-90.420558 42.252688),49,JACKSON,1081300,American Cordials & Liqueur,421,SAZERAC COMPANY INC,64870,Fireball Cinnamon,48,100,0.90,1.35,48,64.80,4.80,1.27,2017-01-16,2017,150456,2018,2017-01-16
176954,INV-02837900006,01/23/2017,4538,K & S Grocery,402 North Main St,Clarksville,50619,POINT (-92.667833 42.787434),12,BUTLER,1081400,American Schnapps,434,LUXCO INC,81206,Paramount Peppermint Schnapps,12,750,4.00,6.00,12,67.56,9.00,2.38,2017-01-23,2017,176954,2018,2017-01-23
160730,INV-02862400062,01/23/2017,3576,Liquor Store / Hartley,10 3rd St NW,Hartley,51346,POINT (-95.477367 43.184821),71,OBRIEN,1012200,Scotch Whiskies,260,DIAGEO AMERICAS,5346,Johnnie Walker Red,12,750,13.50,20.25,1,20.25,0.75,0.20,2017-01-23,2017,160730,2018,2017-01-23

In [99]:
df_store1.tail()

,Invoice/Item Number,Date,Store Number,Store Name,Address,City,Zip Code,Store Location,County Number,County,Category,Category Name,Vendor Number,Vendor Name,Item Number,Item Description,Pack,Bottle Volume (ml),State Bottle Cost,State Bottle Retail,Bottles Sold,Sale (Dollars),Volume Sold (Liters),Volume Sold (Gallons),dd_date,year,index,0,dd_date2
181528,INV-45126300015,02/28/2022,5462,7Star Liquor & Tobacco Outlet,502 E Ave NW,Cedar Rapids,52405,POINT (-91.680323 41.977958),57,LINN,1081600,Whiskey Liqueur,421,SAZERAC COMPANY INC,100413,Fireball Cinnamon Whiskey Party Bucket,1,50,51.60,77.40,1,77.40,0.05,0.01,2022-02-28,2022,181528,2018,2022-02-28
169694,INV-45118700017,02/28/2022,2625,Hy-Vee Wine & Spirits #2 / Davenport,3301 W Kimberly Rd,Davenport,52804,NaN,82,SCOTT,1011100,Blended Whiskies,260,DIAGEO AMERICAS,25608,Seagrams 7 Crown,6,1750,12.96,19.44,6,116.64,10.50,2.77,2022-02-28,2022,169694,2018,2022-02-28
169696,INV-45130100002,02/28/2022,3806,Target Store T-1901 / Wdm,5405 Mills Civic Pkwy,West Des Moines,50266,POINT (-93.779582 41.559274),77,POLK,1011200,Straight Bourbon Whiskies,065,Jim Beam Brands,16685,Basil Hayden Toast,6,750,25.00,37.50,6,225.00,4.50,1.18,2022-02-28,2022,169696,2018,2022-02-28
169670,INV-45123100088,02/28/2022,2633,Hy-Vee #3 / BDI / Des Moines,3221 SE 14th St,Des Moines,50320,POINT (-93.596756 41.553941),77,POLK,1081600,Whiskey Liqueur,421,SAZERAC COMPANY INC,67267,Yukon Jack,12,1000,11.75,17.63,12,211.56,12.00,3.17,2022-02-28,2022,169670,2018,2022-02-28
189106,INV-45147800008,02/28/2022,5620,Casey's General Store #2874 / Riceville,208 W Main St,Riceville,50466,POINT (-92.55645 43.363838),45,HOWARD,1031100,American Vodkas,626,JDSO INC / Red Boot Distillery,36873,Blue Ox Vodka,12,750,3.41,5.12,12,61.44,9.00,2.37,2022-02-28,2022,189106,2018,2022-02-28

In [102]:
df_stores = df_store1[['Date','Store Number', 'Store Name', 'Address', 'City', 'Zip Code', 'Store Location', 'County Number', 'County' ,'year','dd_date2']]

In [117]:
print('the length of df_stores is: ', len(df_stores))

the length of df_stores is:  2317

write stores to csv

In [103]:
df_stores.compute().to_csv(r'C:\Users\dgarb\OneDrive\Desktop\Capstone Data\df_stores.csv')

read in df_stores since with small data sets pandas is quicker and easier

In [149]:
pd_df_stores = pd.read_csv(r'C:\Users\dgarb\OneDrive\Desktop\Capstone Data\df_stores.csv')

In [151]:
miss_cols(pd_df_stores)

[('Store Location', 178, 0.0768),
 ('Address', 5, 0.0022),
 ('County Number', 5, 0.0022),
 ('City', 4, 0.0017),
 ('Zip Code', 4, 0.0017),
 ('County', 4, 0.0017)]

create vendors file

In [104]:
df_vendor1 =  combine_dd.sort_values(by=['dd_date2']).drop_duplicates(['Vendor Number'],keep='last')

In [105]:
df_vendor1.head()

,Invoice/Item Number,Date,Store Number,Store Name,Address,City,Zip Code,Store Location,County Number,County,Category,Category Name,Vendor Number,Vendor Name,Item Number,Item Description,Pack,Bottle Volume (ml),State Bottle Cost,State Bottle Retail,Bottles Sold,Sale (Dollars),Volume Sold (Liters),Volume Sold (Gallons),dd_date,year,index,0,dd_date2
179755,INV-03738700003,03/13/2017,3773,Benz Distributing,501 7th Ave SE,Cedar Rapids,52401,POINT (-91.659875 41.97574),57,LINN,NaN,NaN,349,Doc Herson's Natural Spirits,994873,Green Absinthe,6,375,35.00,52.50,6,315.00,2.25,0.59,2017-03-13,2017,179755,2018,2017-03-13
90910,INV-04197200001,04/05/2017,3869,Bootleggin' Barzini's Fin,412 1st Ave,Coralville,52241,POINT (-91.565517 41.672672),52,JOHNSON,1062500,Flavored Rum,318,RJ Importers LLC,995539,Caribbean's Finest Rum Grapefruit,12,750,9.17,13.76,12,165.12,9.00,2.38,2017-04-05,2017,90910,2018,2017-04-05
242060,INV-04723500109,05/03/2017,2625,Hy-Vee Wine and Spirits #2,3301 W Kimberly Rd,Davenport,52804,NaN,82,SCOTT,1011100,Blended Whiskies,234,Eastside Distilling,27824,Barrel Hitch Oregon Oak American Whiskey,6,750,12.00,18.00,2,36.00,1.50,0.40,2017-05-03,2017,242060,2018,2017-05-03
100612,INV-05020600001,05/18/2017,2648,Hy-Vee #4 / Wdm,555 S 51st St,West Des Moines,50265,POINT (-93.773557 41.561197),77,POLK,1062500,Flavored Rum,969,A V BRANDS INC,977058,Prichards Peach Mango Rum,6,750,16.66,24.99,6,149.94,4.50,1.19,2017-05-18,2017,100612,2018,2017-05-18
143629,INV-05181400001,05/26/2017,3698,Ingersoll Wine Merchants,1300 50th St,West Des Moines,50266,POINT (-93.771159 41.590871),77,POLK,1092100,Imported Distilled Spirit Specialty,436,The House of Burgundy Inc,994648,Sari Zeybek,12,750,18.00,27.00,12,324.00,9.00,2.38,2017-05-26,2017,143629,2018,2017-05-26

In [106]:
df_vendor1.tail()

,Invoice/Item Number,Date,Store Number,Store Name,Address,City,Zip Code,Store Location,County Number,County,Category,Category Name,Vendor Number,Vendor Name,Item Number,Item Description,Pack,Bottle Volume (ml),State Bottle Cost,State Bottle Retail,Bottles Sold,Sale (Dollars),Volume Sold (Liters),Volume Sold (Gallons),dd_date,year,index,0,dd_date2
169693,INV-45133100008,02/28/2022,5929,D&T's / Odebolt,417 1st St,Odebolt,51458,POINT (-95.470844 42.345702),81,SAC,1062500,Flavored Rum,035,BACARDI USA INC,43138,Bacardi Limon,6,1750,15.00,22.50,6,135.00,10.5,2.77,2022-02-28,2022,169693,2018,2022-02-28
169694,INV-45118700017,02/28/2022,2625,Hy-Vee Wine & Spirits #2 / Davenport,3301 W Kimberly Rd,Davenport,52804,NaN,82,SCOTT,1011100,Blended Whiskies,260,DIAGEO AMERICAS,25608,Seagrams 7 Crown,6,1750,12.96,19.44,6,116.64,10.5,2.77,2022-02-28,2022,169694,2018,2022-02-28
169696,INV-45130100002,02/28/2022,3806,Target Store T-1901 / Wdm,5405 Mills Civic Pkwy,West Des Moines,50266,POINT (-93.779582 41.559274),77,POLK,1011200,Straight Bourbon Whiskies,065,Jim Beam Brands,16685,Basil Hayden Toast,6,750,25.00,37.50,6,225.00,4.5,1.18,2022-02-28,2022,169696,2018,2022-02-28
169670,INV-45123100088,02/28/2022,2633,Hy-Vee #3 / BDI / Des Moines,3221 SE 14th St,Des Moines,50320,POINT (-93.596756 41.553941),77,POLK,1081600,Whiskey Liqueur,421,SAZERAC COMPANY INC,67267,Yukon Jack,12,1000,11.75,17.63,12,211.56,12.0,3.17,2022-02-28,2022,169670,2018,2022-02-28
189106,INV-45147800008,02/28/2022,5620,Casey's General Store #2874 / Riceville,208 W Main St,Riceville,50466,POINT (-92.55645 43.363838),45,HOWARD,1031100,American Vodkas,626,JDSO INC / Red Boot Distillery,36873,Blue Ox Vodka,12,750,3.41,5.12,12,61.44,9.0,2.37,2022-02-28,2022,189106,2018,2022-02-28

In [108]:
df_vendors = df_vendor1[['Vendor Number', 'Vendor Name','Date', 'dd_date2', 'year' ]]

In [118]:
print('the length of df_vendors is: ', len(df_vendors))

the length of df_vendors is:  319

write vendors file to csv

In [109]:
df_vendors.compute().to_csv(r'C:\Users\dgarb\OneDrive\Desktop\Capstone Data\df_vendors.csv')

write vendors to sql

 dask.dataframe.to_sql(df, name: str, uri: str, schema=None, if_exists: str = 'fail', index: bool = True, index_label=None, chunksize=None, dtype=None, method=None, compute=True, parallel=False, engine_kwargs=None)[source]

In [207]:
df_vendors = df_vendor1[['Vendor Number', 'Vendor Name','Date', 'dd_date2', 'year' ]]

In [209]:
df_vendors.to_sql(df_vendors,{name:'vendors'},dtype={'Vendor Number':str,'Vendor Name':str, 'Date':str,'year':int })

NameError: name 'name' is not defined

In [213]:
from dask.utils import tmpfile
from sqlalchemy import create_engine
with tmpfile() as f:
    db = 'C:\Users\dgarb\OneDrive\Documents\Data Science Bootcamp August\Capstone - Copy\sqlite\db'
    df_vendors.to_sql('vendors', db)
    engine = create_engine(db, echo=False)
    result = engine.execute("SELECT * FROM test").fetchall()
result

SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape (Temp/ipykernel_24196/2434054610.py, line 4)

create product_n_proof file

In [190]:
dytype_dict = {'Item Number':str, 'Vendor':str, 'Proof':int, 'Vendor Name':str, 'Age':int}

In [195]:
Iowa_Liquor_Products = pd.read_csv(r'C:\Users\dgarb\OneDrive\Desktop\Capstone Data\Iowa_Liquor_Products.csv', dtype=dytype_dict )

In [196]:
Iowa_Liquor_Products.head(2)

,Item Number,Category Name,Item Description,Vendor,Vendor Name,Bottle Volume (ml),Pack,Inner Pack,Age,Proof,List Date,UPC,SCC,State Bottle Cost,State Case Cost,State Bottle Retail,Report Date
0,901141,Special Order Items,Libertine Absinthe(French Absinthe) Mini,885,YAHARA BAY DISTILLERS INC,50,6,1,0,114,04/20/2012,NaN,10892060104050,4.82,28.9,7.23,03/01/2022
1,65017,Imported Cordials & Liqueurs,Galliano Liqueur,305,Mhw LTD,375,12,1,0,84,10/01/2012,8.091511e+10,10892060104050,10.75,129.0,16.13,03/01/2022

In [199]:
Iowa_Liquor_Products.shape

(10443, 17)

In [197]:
product_n_proof = Iowa_Liquor_Products.drop(['UPC', 'SCC'],axis=1)

In [198]:
product_n_proof.to_csv(r'C:\Users\dgarb\OneDrive\Desktop\Capstone Data\product_n_proof.csv')

create categories file

In [107]:
df_categ1 = combine_dd.sort_values(by=['dd_date2']).drop_duplicates(['Category'],keep='last')

In [110]:
df_categ1.head()

,Invoice/Item Number,Date,Store Number,Store Name,Address,City,Zip Code,Store Location,County Number,County,Category,Category Name,Vendor Number,Vendor Name,Item Number,Item Description,Pack,Bottle Volume (ml),State Bottle Cost,State Bottle Retail,Bottles Sold,Sale (Dollars),Volume Sold (Liters),Volume Sold (Gallons),dd_date,year,index,0,dd_date2
120869,INV-08338500007,10/31/2017,5443,1st Stop Beverage Shop,2839 East University Ave.,Des Moines,50317,POINT (-93.561517 41.600476),77,POLK,1701200,Holiday VAP,259,Heaven Hill Brands,59100,Evan Williams Egg Nog,12,750,4.47,6.71,1,80.52,0.75,0.19,2017-10-31,2017,120869,2018,2017-10-31
195713,INV-14721400069,09/28/2018,2228,Rodgers Spirits and More,53 Green St,Winterset,50273,POINT (-94.013374 41.336405),61,MADISON,1091400,Iowa Distilleries,255,Infinium Spirits,27125,Templeton 6YR Rye,6,750,22.75,34.13,1,34.13,0.75,0.19,2018-09-28,2018,195713,2018,2018-09-28
138522,INV-24931300001,01/31/2020,9039,Foundry Distilling Company,111 South 11th St. Ste 100,West Des Moines,50265,POINT (-93.71798 41.568546),77,POLK,1011800,Iowa Distillery Whiskies,566,"Foundry Distilling Company, LLC",926684,Foundry Whiskey Custom,6,750,7.93,11.90,36,428.40,27.00,7.13,2020-01-31,2020,138522,2018,2020-01-31
44111,INV-27570500113,05/29/2020,2505,Hy-Vee Wine and Spirits / Boone,1111 8TH ST,Boone,50036,POINT (-93.876107 42.063831),8,BOONE,NaN,NaN,305,Mhw LTD,80024,Blue Chair Bay Banana Rum Cream,12,750,9.42,14.13,2,28.26,1.50,0.39,2020-05-29,2020,44111,2018,2020-05-29
38980,INV-29108600006,07/30/2020,4129,Cyclone Liquors,626 Lincoln Way,Ames,50010,POINT (-93.618911 42.022854),85,STORY,1900000,Delisted / Special Order Items,625,Middle West Spirits,907699,OYO Honey Vanilla Bean,12,750,18.50,27.75,12,333.00,9.00,2.37,2020-07-30,2020,38980,2018,2020-07-30

In [111]:
df_categ1.tail()

,Invoice/Item Number,Date,Store Number,Store Name,Address,City,Zip Code,Store Location,County Number,County,Category,Category Name,Vendor Number,Vendor Name,Item Number,Item Description,Pack,Bottle Volume (ml),State Bottle Cost,State Bottle Retail,Bottles Sold,Sale (Dollars),Volume Sold (Liters),Volume Sold (Gallons),dd_date,year,index,0,dd_date2
178509,INV-45119300012,02/28/2022,5692,Locust Mart / Davenport,11423 160th St,Davenport,52804,POINT (-90.680408 41.538169),82,SCOTT,1031100,American Vodkas,421,SAZERAC COMPANY INC,38088,Platinum 7x Vodka,6,1750,9.44,14.16,6,84.96,10.50,2.77,2022-02-28,2022,178509,2018,2022-02-28
178506,INV-45125600135,02/28/2022,2552,Hy-Vee Food Store #3 / Cedar Rapids,20 Wilson Avenue West,Cedar Rapids,52404,POINT (-91.658576 41.955859),57,LINN,1032200,Imported Flavored Vodka,115,CONSTELLATION BRANDS INC,36576,Svedka Blue Raspberry,12,750,8.00,12.00,4,48.00,3.00,0.79,2022-02-28,2022,178506,2018,2022-02-28
178505,INV-45118700012,02/28/2022,2625,Hy-Vee Wine & Spirits #2 / Davenport,3301 W Kimberly Rd,Davenport,52804,NaN,82,SCOTT,1031200,American Flavored Vodka,260,DIAGEO AMERICAS,77647,Smirnoff Citrus,12,750,8.25,12.38,12,148.56,9.00,2.37,2022-02-28,2022,178505,2018,2022-02-28
186294,INV-45151400008,02/28/2022,6000,Porters Convenience 66 / Clinton,1512 Lincoln Way,Clinton,52732,POINT (-90.221831 41.817449),23,CLINTON,1051100,American Brandies,205,E & J Gallo Winery,52594,E & J VS,24,375,3.50,5.25,3,15.75,1.12,0.29,2022-02-28,2022,186294,2018,2022-02-28
186715,INV-45149700011,02/28/2022,4562,Casey's General Store #2989 / Mechanicsville,206 Short St,Mechanicsville,52306,NaN,16,CEDAR,1012100,Canadian Whiskies,259,Heaven Hill Brands,10550,Black Velvet Toasted Caramel,12,750,5.23,7.85,12,94.20,9.00,2.37,2022-02-28,2022,186715,2018,2022-02-28

In [112]:
df_categories = df_categ1[['Date', 'Category', 'Category Name', 'year', 'dd_date2']]

In [120]:
print('the length of df_categories is: ', len(df_categories))

the length of df_categories is:  62

write out categories file

In [113]:
df_categories.compute().to_csv(r'C:\Users\dgarb\OneDrive\Desktop\Capstone Data\df_categories.csv') #to_sql

read in df_categories since with small data sets pandas is quicker and easier

In [177]:
dict_dtypes = {'Category':str, 'Category Name':str}
pd_df_categories = pd.read_csv(r'C:\Users\dgarb\OneDrive\Desktop\Capstone Data\df_categories.csv', dtype = dict_dtypes)

In [178]:
pd_df_categories.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 62 entries, 0 to 61
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Unnamed: 0     62 non-null     int64
 1   Date           62 non-null     object
 2   Category       61 non-null     object
 3   Category Name  61 non-null     object
 4   year           62 non-null     int64
 5   dd_date2       62 non-null     object
dtypes: int64(2), object(4)
memory usage: 3.0+ KB

In [180]:
pd_df_categories = pd_df_categories.dropna()

category = list(pd_df_categories['Category'])
category_name = list(pd_df_categories['Category Name'])
 
categ_list = list(zip(category,category_name))
# sorted(categ_list, key = lambda categ: categ[1])
dict_categ = dict(categ_list)

write out cleaned categories file

In [202]:
pd_df_categories.to_csv(r'C:\Users\dgarb\OneDrive\Desktop\Capstone Data\categories_clean.csv')

TypeError: to_sql() missing 1 required positional argument: 'con'

In [185]:
dict_list = sorted(dict_categ.items(), key = lambda kv:(kv[1], kv[0]))

# dict_categ['1081300']='American Cordials & Liqueurs'

# ('1081300', 'American Cordials & Liqueur'),
#  ('1081000', 'American Cordials & Liqueurs'),
# ('1081400', 'American Schnapps')
# ('1081100', 'Coffee Liqueurs')
# ('1081200', 'Cream Liqueurs')

# ('1082100', 'Imported Cordials & Liqueur'),
#  ('1082000', 'Imported Cordials & Liqueurs'),
#     ('1082200', 'Imported Schnapps')
#     ('1081600', 'Whiskey Liqueur')

In [147]:
print(proc_freq(pd_df_categories,'Category Name').to_string())

                           Category Name  Frequency  Percent  Cumulative_Frequency  Cumulative_Percent
0                     100% Agave Tequila          1     1.64                     1                1.64
1                          Aged Dark Rum          1     1.64                     2                3.28
2                      American Brandies          1     1.64                     3                4.92
3            American Cordials & Liqueur          1     1.64                     4                6.56
4           American Cordials & Liqueurs          1     1.64                     5                8.20
5    American Distilled Spirit Specialty          1     1.64                     6                9.84
6   American Distilled Spirits Specialty          1     1.64                     7               11.48
7                      American Dry Gins          1     1.64                     8               13.11
8                American Flavored Vodka          1     1.64                     9               14.75
9                      American Schnapps          1     1.64                    10               16.39
10                    American Sloe Gins          1     1.64                    11               18.03
11                        American Vodka          1     1.64                    12               19.67
12                       American Vodkas          1     1.64                    13               21.31
13                     American Whiskies          1     1.64                    14               22.95
14                      Blended Whiskies          1     1.64                    15               24.59
15               Bottled in Bond Bourbon          1     1.64                    16               26.23
16                     Canadian Whiskies          1     1.64                    17               27.87
17                       Cocktails / RTD          1     1.64                    18               29.51
18                        Cocktails /RTD          1     1.64                    19               31.15
19                       Coffee Liqueurs          1     1.64                    20               32.79
20                         Corn Whiskies          1     1.64                    21               34.43
21                        Cream Liqueurs          1     1.64                    22               36.07
22        Delisted / Special Order Items          1     1.64                    23               37.70
23           Distilled Spirits Specialty          1     1.64                    24               39.34
24                          Flavored Gin          1     1.64                    25               40.98
25                          Flavored Rum          1     1.64                    26               42.62
26                              Gold Rum          1     1.64                    27               44.26
27                           Holiday VAP          1     1.64                    28               45.90
28                     Imported Brandies          1     1.64                    29               47.54
29           Imported Cordials & Liqueur          1     1.64                    30               49.18
30          Imported Cordials & Liqueurs          1     1.64                    31               50.82
31   Imported Distilled Spirit Specialty          1     1.64                    32               52.46
32  Imported Distilled Spirits Specialty          1     1.64                    33               54.10
33                     Imported Dry Gins          1     1.64                    34               55.74
34               Imported Flavored Vodka          1     1.64                    35               57.38
35                         Imported Gins          1     1.64                    36               59.02
36                     Imported Schnapps          1     1.64                    37               60.66
37                        Imported Vodka          1     1.64                    38               62.30
38                       Imported Vodkas          1     1.64                    39               63.93
39                     Imported Whiskies          1     1.64                    40               65.57
40                     Iowa Distilleries          1     1.64                    41               67.21
41              Iowa Distillery Whiskies          1     1.64                    42               68.85
42                        Irish Whiskies          1     1.64                    43               70.49
43                                Mezcal          1     1.64                    44               72.13
44                         Mixto Tequila          1     1.64                    45               73.77
45                 Neutral Grain Spirits          1     1.64                    46               75.41
46        Neutral Grain Spirits Flavored          1     1.64                    47               77.05
47                       Scotch Whiskies          1     1.64                    48               78.69
48        Single Barrel Bourbon Whiskies          1     1.64                    49               80.33
49                    Single Malt Scotch          1     1.64                    50               81.97
50                   Special Order Items          1     1.64                    51               83.61
51                            Spiced Rum          1     1.64                    52               85.25
52             Straight Bourbon Whiskies          1     1.64                    53               86.89
53                 Straight Rye Whiskies          1     1.64                    54               88.52
54       Temporary  & Specialty Packages          1     1.64                    55               90.16
55       Temporary &  Specialty Packages          1     1.64                    56               91.80
56        Temporary & Specialty Packages          1     1.64                    57               93.44
57                    Tennessee Whiskies          1     1.64                    58               95.08
58                            Triple Sec          1     1.64                    59               96.72
59                       Whiskey Liqueur          1     1.64                    60               98.36
60                             White Rum          1     1.64                    61              100.00

toy test

In [48]:

df = pd.DataFrame({'item_no': [1,1,1,1,2,2,2,2], 'descr': ['A','B','C','D','E','F','G','H'], 
                   'date_str': ['1/20/2022','1/30/2022','2/1/2022','2/28/2022','1/5/2022','1/21/2022','2/2/2022','1/3/2022']})
print(df)

   item_no descr   date_str
0        1     A  1/20/2022
1        1     B  1/30/2022
2        1     C   2/1/2022
3        1     D  2/28/2022
4        2     E   1/5/2022
5        2     F  1/21/2022
6        2     G   2/2/2022
7        2     H   1/3/2022

In [49]:
df['date'] = pd.to_datetime(df['date_str'])

In [50]:
df

   item_no descr   date_str       date
0        1     A  1/20/2022 2022-01-20
1        1     B  1/30/2022 2022-01-30
2        1     C   2/1/2022 2022-02-01
3        1     D  2/28/2022 2022-02-28
4        2     E   1/5/2022 2022-01-05
5        2     F  1/21/2022 2022-01-21
6        2     G   2/2/2022 2022-02-02
7        2     H   1/3/2022 2022-01-03

In [51]:
df.sort_values(by=['date']).drop_duplicates(['item_no'],keep='last')

   item_no descr   date_str       date
6        2     G   2/2/2022 2022-02-02
3        1     D  2/28/2022 2022-02-28